### ISSUE TITLE
GPU compile fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by erikrikarddaniel** [voutcn/megahit#100]
I manage to compile 1.0.6 hotfix without gpu support, but get an error when compiling lv2_gpu_functions_4B_sm350_nvvm_7.5_abi_x86_64.o. I'm afraid I'm quite unknowledgeable about gpu, so I might have missed installing a library or two. I have libstdc++-5-dev:amd64 and libstdc++6:amd64 installed, but `ld -lstdc++` gives "ld: cannot find -lstdc++".

[Output from make](https://github.com/voutcn/megahit/files/555849/make.log.txt)

**Comment by voutcn** [comment]
Are you able to compile the CPU-only version?

**Comment by voutcn** [comment]
Please comment out Line [162-164](  https://github.com/voutcn/megahit/blob/master/Makefile#L162-L164) of the Makefile and try again. (For safety, use `make clean` before make again)

**Comment by erikrikarddaniel** [comment]
Commenting out 162-162 didn't work.
Output from make: 
[make.out.txt](https://github.com/voutcn/megahit/files/570915/make.out.txt)

**Comment by voutcn** [comment]
May I know the model of GPU card? Just my guess -- it may not support sm35.

On the other hand, if you have a CPU with 6 cores of more, the speed of the CPU-only counterpart should be closed to that uses GPU. As we do not plan to support GPU in the future (see  https://github.com/voutcn/megahit/issues/95), please just ignore it if it is not necessary.

**Comment by erikrikarddaniel** [comment]
lspci says it's an NVIDIA Corporation Device 1b80 (rev a1)

We have 24 cores, and Megahit is really quick. Using the GPU was mostly for testing.

I'm hence closing this now.
