### ISSUE TITLE
-o should detect incomplete assemblies and overwrite if the assembly is incomplete

### ISSUE THREAD

**Issue by ctb** [voutcn/megahit#101]
Right now, '-o' will say exit with an error if the output directory already exists, but I think it'd be a fair change to overwrite an incomplete assembly -- often I have a mistake in my input parameters or input files that breaks the assembly, and then I have to deal with this error when I try to rerun! It's not a big deal but it's mildly annoying and it's bad when teaching...

this is the current error message:
```
megahit: Output directory assembly/ already exists, please change the parameter -o to another value to avoid overwriting.
````

**Comment by voutcn** [comment]
It doesn't overwrite the directory to because one may lose their temporary files for using `--continue` option by accident. 

Do you think a `-f` option to force overwrite would be useful?

**Comment by ctb** [comment]
yes, that would also work! thanks!

**Comment by voutcn** [comment]
Added to the master branch. This option will appear in the next stable release (v1.1.1) after testing v1.1-beta (current pre-release) thoroughly.
