### ISSUE TITLE
"forbidden"

### ISSUE THREAD

**Issue by jmbraverman** [voutcn/megahit#102]
I get the following error when trying to wget the files as described:

wget http://www.bio8.cs.hku.hk/dataset/MEGAHIT/SRR341725_2.fastq.gz
--2016-12-15 13:29:45--  http://www.bio8.cs.hku.hk/dataset/MEGAHIT/SRR341725_2.fastq.gz
Resolving www.bio8.cs.hku.hk... 147.8.179.16
Connecting to www.bio8.cs.hku.hk|147.8.179.16|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2016-12-15 13:29:46 ERROR 403: Forbidden.

**Comment by voutcn** [comment]
Our server is temporary (maybe permanent :( ) down. Please try whatever datasets you have (or find some in NCBI-sra or ENA). I will update the wiki in the near future.
