### ISSUE TITLE
Advice with paired and interleaved files

### ISSUE THREAD

**Issue by davidmartinad200** [voutcn/megahit#103]
Hello,
I have used trimmomatic 0.36 to remove low quality reads of my metagenomics experiment (2*150bp on HiSeq).
After low quality reads removal using trimmomatic i obtain two paired-end files with good quality reads  and singleton files R1 and R2 as well with good quality single reads (only one of the two reads survied to the quality trimming).

How can i use megahit to take into account singletons R1 and R2 that are good quality together with the paired-end files ?

thanks

**Comment by voutcn** [comment]
Yes, you can use all of them, and the PE info will not be missed, by the following syntax:
`-1 paired_1.fq -2 paired_2.fq -r single_1.fq -r single_2.fq`

**Comment by davidmartinad200** [comment]
Great, will do that.

**Comment by bkj** [comment]
Is it possible to get the same result without splitting the file?  Eg, I have a file w/ ids that look like

```
@604:2:120:1785:1612/1
@604:2:120:1785:1612/2
@604:2:120:1785:603/1
@604:2:120:1785:603/2
@604:2:120:1785:1973/1
@604:2:120:1785:1626/1
```

eg. singleton reads in the same file as PE reads.  Would I just pass it w/ the `--12` flag?

Thanks!
~ Ben

**Comment by pdhrati02** [comment]
@voutcn Hi, I have a similar question. I ran kneaddata and the kneaddata output has unmatched_1.fq and unmatched_2.fq which are reads whose mates are lost but they themselves passed both trimmomatic and bowtie2 step. In this case can I use paired1.fq, paired2.fq and also the other two unmatched1.fq and unmatched2.fq files? Would it affect the assembly? Thanks in advance
