### ISSUE TITLE
Quality trimming ??

### ISSUE THREAD

**Issue by davidmartinad200** [voutcn/megahit#105]
Hi ,
Just wondering if Megahit requires metagenomics data to be quality trimmed ?? For instance i have a 2x150bp dataset and i have used trimmomatic to do quality trimming (Q>20 over a window of 4 bases). 
It turns out that for a community mock i reduce the assembly for 97% of the reads down to 92%, so quality trimming seems to loose reads and results in a worse assembly. Tools such as bwa don´t need quality trimming (only adapter trimming).
Is quality trimming required for Megahit assembly (assuming phiX and human contaminants have been removed with bwa withour quality trimming).
Thanks for your comments.

**Comment by voutcn** [comment]
1. Adaptor trimming is highly recommended.
2. Quality trimming may hurt the assembly of low coverage regions but may improve that of high coverage regions. After version 1.1, Megahit can better deal with errors in high coverage regions, so you may skip Q-Trim at all. I used to trim at Q=10 and did not observe obvious "worse assemblies".
