### ISSUE TITLE
Checkpointing support

### ISSUE THREAD

**Issue by ukaraoz** [voutcn/megahit#107]
I am trying to properly invoke the checkpointing support using `--continue` option, so as to start a long cluster job from when the wall clock has run off.

What is the right way of doing this? Should I use --continue and set the --out-dir to the output directory from the previous run?

**Comment by voutcn** [comment]
Yes, you are correct. To make sure the relative path of the input files is correct, please do so under the same working directory where you ran Megahit for the job last time.

**Comment by mb1069** [comment]
Are there any keywords in the log file/ files that I can check in tmp directory that I can use to assert whether the assembly has passed a checkpoint from which it can be restarted? Alternately, what is the expected behaviour if --checkpoint is passed to an assembly job which was not yet started?
