### ISSUE TITLE
Allow injecting of custom linker flags into the Makefile

### ISSUE THREAD

**Issue by tbooth** [voutcn/megahit#109]
On my system I'm trying to build MEGAHIT with a specific GCC version. My command line is:

```
$ cd megahit-master
$ make CXX=/lustre/software/gcc6/gcc-6.3.0/bin/gcc LDFLAGS='-Wl,-rpath -Wl,/lustre/software/gcc6/gcc-6.3.0/lib64 -lstdc++'
```

The override of CXX works already, but in order to add extra LDFLAGS I needed to tweak the Makefile. Attached is my small patch, in case you want to incorporate it in your standard code. It should not affect any users unless they also need to add linker flags.
[makefile.patch.txt](https://github.com/voutcn/megahit/files/699101/makefile.patch.txt)

Many thanks for writing and maintaining MEGAHIT.

TIM

**Comment by voutcn** [comment]
Thank you Tim. You could create a pull request to the dev branch.
