### ISSUE TITLE
can "--continue" option also be used to rerun assembly with additional kmers?

### ISSUE THREAD

**Issue by jvollme** [voutcn/megahit#110]
The "--continue" option was added to enable continuing a run if it has been aborted due to e.g. time limitations of a work-queueing system.
But is it also possible to use this option to rerun an assembly with additional kmers (without having to wait until all previous kmer steps are calculated from the beginning again)?

E.g. If i did an assembly of long MiSeq-reads using a k-mer range from 21-101 (in steps of 10) and wanted to find out how much the assembly improves if i increase the range to 141, could i simply use the "--continue" option together with an increased k-mer range (so the assembly starts at the last checkpoint --> 101, instead of starting again at 21)?

Or do all settings have to be the same as in the previous run?

**Comment by voutcn** [comment]
Not yet supported. `--continue` assumes that all parameters not changed.
I think this feature is meaningful but I am too busy to implement it recently.
I will leave this issue open to see if there are more users in want of this feature.

**Comment by jvollme** [comment]
Thanks, personally I think this would be a very valuable feature. Especially in cases where different libraries of drastically different read lengths are combined (e.g. Hiseq-date with 100bp reads and MiSeq data with >300bp reads).
