### ISSUE TITLE
Retrieving unitigs

### ISSUE THREAD

**Issue by machinegun** [voutcn/megahit#113]
Hi,

Is there any way to get only unitigs instead of contigs from megahit? If yes, can you please let me know the parameters need to be set for this?

Thanks.

**Comment by voutcn** [comment]
What do you mean by unitig here? If you mean contigs without any length filtering (i.e. we can recover the assembly graph, but *after* cleaning like tips removal and bubble popping), please find it at `intermediate_contigs/k*.contig.fa`.
