### ISSUE TITLE
Exit code -6

### ISSUE THREAD

**Issue by wojmaka** [voutcn/megahit#114]
Hi,
I try to run MEGAHIT V1.1.1 on Illumina 100 bp pair reads but it stops at assembling contigs for k = 27. I already tried with --kmin-1pass option but it didn't help.

Here is a log file. I can also provide a core dump file but it's huge (3.9G). I run it on 64-core machine under FreeBSD.

Any suggestions? 

Wojciech

MEGAHIT v1.1.1
--- [Wed Apr 12 02:04:22 2017] Start assembly. Number of CPU threads 64 ---
--- [Wed Apr 12 02:04:22 2017] Available memory: 0, used: 480000000000
--- [Wed Apr 12 02:04:22 2017] Converting reads to binaries ---
/bioappl/src/megahit/megahit-master/megahit_asm_core buildlib ./megahit_out/tmp/reads.lib ./megahit_out/tmp/reads.lib
    [read_lib_functions-inl.h  : 209]     Lib 0 (R1_trimmed.fq,R2_trimmed.fq): pe, 678988626 reads, 100 max length
    [utils.h                   : 126]     Real: 1560.8996	user: 1137.5099	sys: 218.5353	maxrss: 157588
--- [Wed Apr 12 02:30:23 2017] k list: 27,37,47,57 ---
--- [Wed Apr 12 02:30:24 2017] Extracting solid (k+1)-mers for k = 27 ---
cmd: /bioappl/src/megahit/megahit-master/megahit_sdbg_build count -k 27 -m 3 --host_mem 480000000000 --mem_flag 1 --gpu_mem 0 --output_prefix ./megahit_out/tmp/k27/27 --num_cpu_threads 64 --num_output_threads 21 --read_lib_file ./megahit_out/tmp/reads.lib
    [sdbg_builder.cpp          : 112]     Host memory to be used: 480000000000
    [sdbg_builder.cpp          : 113]     Number CPU threads: 64
    [cx1.h                     : 450]     Preparing data...
    [read_lib_functions-inl.h  : 256]     Before reading, sizeof seq_package: 21510014540
    [read_lib_functions-inl.h  : 260]     After reading, sizeof seq_package: 21510014540
    [cx1_kmer_count.cpp        : 136]     678988626 reads, 100 max read length
    [cx1.h                     : 457]     Preparing data... Done. Time elapsed: 320.1557
    [cx1.h                     : 464]     Preparing partitions and initialing global data...
    [cx1_kmer_count.cpp        : 227]     2 words per substring, 3 words per edge
    [cx1_kmer_count.cpp        : 364]     Memory for reads: 22012455364
    [cx1_kmer_count.cpp        : 365]     max # lv.1 items = 6130998508
    [cx1.h                     : 480]     Preparing partitions and initialing global data... Done. Time elapsed: 30.2594
    [cx1.h                     : 486]     Start main loop...
    [cx1.h                     : 515]     Lv1 scanning from bucket 0 to 36
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 29.6679
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 272.3124
    [cx1.h                     : 515]     Lv1 scanning from bucket 36 to 147
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 39.7511
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 64.5522
    [cx1.h                     : 515]     Lv1 scanning from bucket 147 to 774
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 44.4947
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 118.8791
    [cx1.h                     : 515]     Lv1 scanning from bucket 774 to 2530
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 31.3061
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 178.6639
    [cx1.h                     : 515]     Lv1 scanning from bucket 2530 to 5892
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 35.1152
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 204.6592
    [cx1.h                     : 515]     Lv1 scanning from bucket 5892 to 11277
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 33.1786
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 211.8327
    [cx1.h                     : 515]     Lv1 scanning from bucket 11277 to 19433
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 35.4460
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 209.1796
    [cx1.h                     : 515]     Lv1 scanning from bucket 19433 to 32224
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 42.5214
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 192.4329
    [cx1.h                     : 515]     Lv1 scanning from bucket 32224 to 63088
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 51.7007
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 162.0843
    [cx1.h                     : 515]     Lv1 scanning from bucket 63088 to 65536
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 24.4734
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 1.6590
    [cx1.h                     : 607]     Main loop done. Time elapsed: 1983.9115
    [cx1.h                     : 613]     Postprocessing...
    [cx1_kmer_count.cpp        : 861]     Total number of candidate reads: 1657074(4123185)
    [cx1_kmer_count.cpp        : 872]     Total number of solid edges: 290250653
    [cx1.h                     : 621]     Postprocess done. Time elapsed: 15.2887
    [utils.h                   : 126]     Real: 2354.0739	user: 99066.2502	sys: 11072.0698	maxrss: 55472244
--- [Wed Apr 12 03:09:38 2017] Building graph for k = 27 ---
/bioappl/src/megahit/megahit-master/megahit_sdbg_build seq2sdbg --host_mem 480000000000 --mem_flag 1 --gpu_mem 0 --output_prefix ./megahit_out/tmp/k27/27 --num_cpu_threads 64 -k 27 --kmer_from 0 --num_edge_files 21 --input_prefix ./megahit_out/tmp/k27/27
    [sdbg_builder.cpp          : 339]     Host memory to be used: 480000000000
    [sdbg_builder.cpp          : 340]     Number CPU threads: 64
    [cx1.h                     : 450]     Preparing data...
    [cx1_seq2sdbg.cpp          : 406]     Number edges: 290250653
    [cx1_seq2sdbg.cpp          : 446]     Bases to reserve: 8127018284, number contigs: 0, number multiplicity: 290250653
    [cx1_seq2sdbg.cpp          : 452]     Before reading, sizeof seq_package: 2031754580, multiplicity vector: 290250653
    [cx1_seq2sdbg.cpp          : 541]     After reading, sizeof seq_package: 2031754580, multiplicity vector: 290250653
    [cx1.h                     : 457]     Preparing data... Done. Time elapsed: 236.1637
    [cx1.h                     : 464]     Preparing partitions and initialing global data...
    [cx1_seq2sdbg.cpp          : 748]     Memory for sequence: 2675748246
    [cx1_seq2sdbg.cpp          : 749]     max # lv.1 items = 232200522
    [cx1.h                     : 480]     Preparing partitions and initialing global data... Done. Time elapsed: 0.9539
    [cx1.h                     : 486]     Start main loop...
    [cx1.h                     : 515]     Lv1 scanning from bucket 0 to 52
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 1.1224
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 13.1317
    [cx1.h                     : 515]     Lv1 scanning from bucket 52 to 732
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 1.3453
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 3.2530
    [cx1.h                     : 515]     Lv1 scanning from bucket 732 to 3587
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 0.7638
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 2.8326
    [cx1.h                     : 515]     Lv1 scanning from bucket 3587 to 9685
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 1.0124
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 3.0745
    [cx1.h                     : 515]     Lv1 scanning from bucket 9685 to 19839
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 1.0841
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 3.1533
    [cx1.h                     : 515]     Lv1 scanning from bucket 19839 to 35915
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 0.9936
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 4.4195
    [cx1.h                     : 515]     Lv1 scanning from bucket 35915 to 65536
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 1.4382
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 3.1287
    [cx1.h                     : 607]     Main loop done. Time elapsed: 40.7541
    [cx1.h                     : 613]     Postprocessing...
    [cx1_seq2sdbg.cpp          :1147]     Number of $ A C G T A- C- G- T-:
    [cx1_seq2sdbg.cpp          :1150]     5273683 183449886 106456399 106414665 180886716 2761278 1540974 1523915 2739643
    [cx1_seq2sdbg.cpp          :1159]     Total number of edges: 591047159
    [cx1_seq2sdbg.cpp          :1160]     Total number of ONEs: 577207666
    [cx1_seq2sdbg.cpp          :1161]     Total number of $v edges: 5273683
    [cx1.h                     : 621]     Postprocess done. Time elapsed: 0.4566
    [utils.h                   : 126]     Real: 278.9744	user: 1419.3373	sys: 445.7438	maxrss: 3979312
--- [Wed Apr 12 03:14:17 2017] Assembling contigs from SdBG for k = 27 ---
cmd: /bioappl/src/megahit/megahit-master/megahit_asm_core assemble -s ./megahit_out/tmp/k27/27 -o ./megahit_out/intermediate_contigs/k27 -t 64 --min_standalone 200 --prune_level 2 --merge_len 20 --merge_similar 0.95 --low_local_ratio 0.2 --min_depth 2 --bubble_level 2 --max_tip_len -1 --careful_bubble
    [assembler.cpp             : 148]     Loading succinct de Bruijn graph: ./megahit_out/tmp/k27/27 Done. Time elapsed: 60.790796
    [assembler.cpp             : 152]     Number of Edges: 591047159; K value: 27
    [assembler.cpp             : 162]     Number of CPU threads: 64
    [assembly_algorithms.cpp   : 162]     Removing tips with length less than 2; Accumulated tips removed: 1446814; time elapsed: 2.2460
    [assembly_algorithms.cpp   : 162]     Removing tips with length less than 4; Accumulated tips removed: 3462314; time elapsed: 2.4434
    [assembly_algorithms.cpp   : 162]     Removing tips with length less than 8; Accumulated tips removed: 5233611; time elapsed: 3.0295
    [assembly_algorithms.cpp   : 162]     Removing tips with length less than 16; Accumulated tips removed: 7053326; time elapsed: 3.7637
    [assembly_algorithms.cpp   : 162]     Removing tips with length less than 32; Accumulated tips removed: 8704315; time elapsed: 3.7903
    [assembly_algorithms.cpp   : 170]     Removing tips with length less than 54; Accumulated tips removed: 8753375; time elapsed: 2.4069
    [assembler.cpp             : 179]     Tips removal done! Time elapsed(sec): 17.783938
    [assembler.cpp             : 188]     unitig graph size: 6539888, time for building: 185.912234
    [assembler.cpp             : 211]     Number of bubbles removed: 1079674, Time elapsed(sec): 2.531608
    [assembler.cpp             : 225]     Number of complex bubbles removed: 36172, Time elapsed(sec): 2.853239
Assertion failed: (!next_vertex.is_deleted), function Refresh_, file unitig_graph.cpp, line 1151.
Error occurs when assembling contigs for k = 27, please refer to ./megahit_out/log for detail
[Exit code -6]

**Comment by voutcn** [comment]
Did you compile Megahit from the source code? Could Megahit run normally by running command `make test` in its root directory?

**Comment by wojmaka** [comment]
Yes, it was compiled from the source but I didn't run test. Let me try.

**Comment by wojmaka** [comment]
make test doesn't work. I asked my system to have a look at the issue. We may be back with more questions. Thanks for the quick answer.

**Comment by wojmaka** [comment]
So, the test works fine:
./megahit --12 example/readsInterleaved1.fa.gz,example/readsInterleaved2.fa.bz2,example/readsInterleaved3.fa -o example/megahit_out -m 10737418240 -t 1
MEGAHIT v1.1.1
--- [Wed Apr 12 09:20:03 2017] Start assembly. Number of CPU threads 1 ---
--- [Wed Apr 12 09:20:03 2017] Available memory: 0, used: 10737418240
--- [Wed Apr 12 09:20:03 2017] Converting reads to binaries ---
    [read_lib_functions-inl.h  : 209]     Lib 0 (example/readsInterleaved1.fa.gz): interleaved, 200 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 1 (example/readsInterleaved2.fa.bz2): interleaved, 200 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 2 (example/readsInterleaved3.fa): interleaved, 200 reads, 100 max length
    [utils.h                   : 126]     Real: 0.0534  user: 0.0000    sys: 0.0061     maxrss: 2552
--- [Wed Apr 12 09:20:03 2017] k-max reset to: 119 ---
--- [Wed Apr 12 09:20:03 2017] k list: 21,29,39,59,79,99,119 ---
--- [Wed Apr 12 09:20:03 2017] Extracting solid (k+1)-mers for k = 21 ---
--- [Wed Apr 12 09:20:04 2017] Building graph for k = 21 ---
--- [Wed Apr 12 09:20:04 2017] Assembling contigs from SdBG for k = 21 ---
--- [Wed Apr 12 09:20:04 2017] Local assembling k = 21 ---
--- [Wed Apr 12 09:20:05 2017] Extracting iterative edges from k = 21 to 29 ---
--- [Wed Apr 12 09:20:05 2017] Building graph for k = 29 ---
--- [Wed Apr 12 09:20:05 2017] Assembling contigs from SdBG for k = 29 ---
--- [Wed Apr 12 09:20:05 2017] Local assembling k = 29 ---
--- [Wed Apr 12 09:20:05 2017] Extracting iterative edges from k = 29 to 39 ---
--- [Wed Apr 12 09:20:05 2017] Building graph for k = 39 ---
--- [Wed Apr 12 09:20:06 2017] Assembling contigs from SdBG for k = 39 ---
--- [Wed Apr 12 09:20:06 2017] Local assembling k = 39 ---
--- [Wed Apr 12 09:20:06 2017] Extracting iterative edges from k = 39 to 59 ---
--- [Wed Apr 12 09:20:06 2017] Building graph for k = 59 ---
--- [Wed Apr 12 09:20:06 2017] Assembling contigs from SdBG for k = 59 ---
--- [Wed Apr 12 09:20:06 2017] Local assembling k = 59 ---
--- [Wed Apr 12 09:20:07 2017] Extracting iterative edges from k = 59 to 79 ---
--- [Wed Apr 12 09:20:07 2017] Merging to output final contigs ---
--- [STAT] 1 contigs, total 1229 bp, min 1229 bp, max 1229 bp, avg 1229 bp, N50 1229 bp
--- [Wed Apr 12 09:20:07 2017] ALL DONE. Time elapsed: 3.225431 seconds ---
[appl@pyra-work:megahit-master] % ./megahit --12 example/readsInterleaved1.fa.gz,example/readsInterleaved2.fa.bz2,example/readsInterleaved3.fa -o example/megahit_out -m 10737418240 -t 1 --kmin-1pass
MEGAHIT v1.1.1
--- [Wed Apr 12 09:21:12 2017] Start assembly. Number of CPU threads 1 ---
--- [Wed Apr 12 09:21:12 2017] Available memory: 0, used: 10737418240
--- [Wed Apr 12 09:21:12 2017] Converting reads to binaries ---
    [read_lib_functions-inl.h  : 209]     Lib 0 (example/readsInterleaved1.fa.gz): interleaved, 200 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 1 (example/readsInterleaved2.fa.bz2): interleaved, 200 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 2 (example/readsInterleaved3.fa): interleaved, 200 reads, 100 max length
    [utils.h                   : 126]     Real: 0.0124  user: 0.0000    sys: 0.0055     maxrss: 0
--- [Wed Apr 12 09:21:12 2017] k-max reset to: 119 ---
--- [Wed Apr 12 09:21:12 2017] k list: 21,29,39,59,79,99,119 ---
--- [Wed Apr 12 09:21:12 2017] Extracting solid (k+1)-mers and building sdbg for k = 21 ---
--- [Wed Apr 12 09:21:12 2017] Assembling contigs from SdBG for k = 21 ---
--- [Wed Apr 12 09:21:12 2017] Local assembling k = 21 ---
--- [Wed Apr 12 09:21:12 2017] Extracting iterative edges from k = 21 to 29 ---
--- [Wed Apr 12 09:21:12 2017] Building graph for k = 29 ---
--- [Wed Apr 12 09:21:12 2017] Assembling contigs from SdBG for k = 29 ---
--- [Wed Apr 12 09:21:13 2017] Local assembling k = 29 ---
--- [Wed Apr 12 09:21:13 2017] Extracting iterative edges from k = 29 to 39 ---
--- [Wed Apr 12 09:21:13 2017] Building graph for k = 39 ---
--- [Wed Apr 12 09:21:13 2017] Assembling contigs from SdBG for k = 39 ---
--- [Wed Apr 12 09:21:13 2017] Local assembling k = 39 ---
--- [Wed Apr 12 09:21:14 2017] Extracting iterative edges from k = 39 to 59 ---
--- [Wed Apr 12 09:21:14 2017] Building graph for k = 59 ---
--- [Wed Apr 12 09:21:14 2017] Assembling contigs from SdBG for k = 59 ---
--- [Wed Apr 12 09:21:14 2017] Local assembling k = 59 ---
--- [Wed Apr 12 09:21:14 2017] Extracting iterative edges from k = 59 to 79 ---
--- [Wed Apr 12 09:21:14 2017] Merging to output final contigs ---
--- [STAT] 1 contigs, total 1229 bp, min 1229 bp, max 1229 bp, avg 1229 bp, N50 1229 bp
--- [Wed Apr 12 09:21:14 2017] ALL DONE. Time elapsed: 2.626645 seconds ---

Any more idea what goes wrong with the real data?

**Comment by voutcn** [comment]
Any idea why `make test` failed in your first attempt?

**Comment by wojmaka** [comment]
Yes, it was trivial. I didn't have writing permission to the folder :)

**Comment by voutcn** [comment]
It seems that you've run Megahit for at least twice with or without `--kmin-1pass`. Did the two runs halt at the same place? i.e. `Assertion failed: (!next_vertex.is_deleted), function Refresh_, file unitig_graph.cpp, line 1151`

**Comment by wojmaka** [comment]
Yes

**Comment by voutcn** [comment]
I am running out of trivial solutions. I've never tested Megahit under FreeBSD. I am not sure whether it is caused by multi-thread incompatibility.
Could you try the following command in the root directory of Megahit? 
`rm -rf example/megahit_out && ./megahit --12 example/readsInterleaved1.fa.gz,example/readsInterleaved2.fa.bz2,example/readsInterleaved3.fa -o example/megahit_out -m 1e8 -t 64`
