### ISSUE TITLE
Exit code 1

### ISSUE THREAD

**Issue by camillaln** [voutcn/megahit#115]
Heia

I am trying to run Megahit v1.1.1 on a server, but am having problems. I pasted in my log file below. Could you help me figure out what is wrong?
Thanks you very much for your help.
Camilla

MEGAHIT v1.1.1
--- [Wed Apr 12 09:02:18 2017] Start assembly. Number of CPU threads 24 ---
--- [Wed Apr 12 09:02:18 2017] Available memory: 271030964224, used: 243927867801
--- [Wed Apr 12 09:02:18 2017] Converting reads to binaries ---
/global/software/megahit/megahit111/bin/megahit_asm_core buildlib Megahitassemblies/tmp/reads.lib Megahitassemblies/tmp/reads.lib
    [read_lib_functions-inl.h  : 209]     Lib 0 (DG074_161215_NextSeq_trim_paired.good_1.fa,DG074_161215_NextSeq_trim_paired.good_2.fa): pe, 88530380 reads, 151 max length
    [utils.h                   : 126]     Real: 376.0422	user: 113.2728	sys: 8.1698	maxrss: 165920
--- [Wed Apr 12 09:09:39 2017] k list: 21,29,39,59,79,99,119,141 ---
--- [Wed Apr 12 09:09:39 2017] Extracting solid (k+1)-mers for k = 21 ---
cmd: /global/software/megahit/megahit111/bin/megahit_sdbg_build count -k 21 -m 2 --host_mem 243927867801 --mem_flag 1 --gpu_mem 0 --output_prefix Megahitassemblies/tmp/k21/21 --num_cpu_threads 24 --num_output_threads 8 --read_lib_file Megahitassemblies/tmp/reads.lib
    [sdbg_builder.cpp          : 112]     Host memory to be used: 243927867801
    [sdbg_builder.cpp          : 113]     Number CPU threads: 24
    [cx1.h                     : 450]     Preparing data...
    [read_lib_functions-inl.h  : 256]     Before reading, sizeof seq_package: 3839854368
    [read_lib_functions-inl.h  : 260]     After reading, sizeof seq_package: 3839854368
    [cx1_kmer_count.cpp        : 136]     0 reads, 0 max read length
    [cx1.h                     : 457]     Preparing data... Done. Time elapsed: 0.4674
    [cx1.h                     : 464]     Preparing partitions and initialing global data...
    [cx1_kmer_count.cpp        : 227]     2 words per substring, 2 words per edge
    [cx1_kmer_count.cpp        : 364]     Memory for reads: 3839854400
    [cx1_kmer_count.cpp        : 365]     max # lv.1 items = 0
    [cx1.h                     : 480]     Preparing partitions and initialing global data... Done. Time elapsed: 0.1031
    [cx1.h                     : 486]     Start main loop...
Bucket 65536 too large for lv1: 0 > 0
Error occurs when running "sdbg_builder count/read2sdbg", please refer to Megahitassemblies/log for detail
[Exit code 1]

**Comment by voutcn** [comment]
Hmm, could you show me the content of `Megahitassemblies/tmp/reads.lib_info`?

**Comment by camillaln** [comment]
Thanks for getting back to me. 
Here is the info from the tmp/reads.lib
DG074_161215_NextSeq_trim_paired.good_1.fq,DG074_161215_NextSeq_trim_paired.good_2.fq
pe Megahitassemblies/tmp/inpipe.pe1.0 Megahitassemblies/tmp/inpipe.pe2.0

I tried another library from a community I think have lower diversity and it ran longer, and then failed due to "exceeded MEM usage hard limit (13632 > 12390)". So I suspect this is all a memory issue (?). I have asked for more memory. How much do you think I will need. My fastq files are in the range 2x15-30Gb.
Camilla

**Comment by voutcn** [comment]
I want to see the `Megahitassemblies/tmp/reads.lib.lib_info` file :)
And how large is the `Megahitassemblies/tmp/reads.lib.bin`? You can use `ls -l Megahitassemblies/tmp/` to get the size. I am afraid that the file is empty.

For your second question, I guess you submitted the job via some HPC system and the memory is limited by your admin. If the memory limit is L, tried to set a proper size using the `-m` parameter. Please attach the log so that I can confirm my conjecture.

**Comment by camillaln** [comment]
Sorry - there is no such file in my tmp folder.
Only these files:
[nesbo@breezy tmp]$ ls -lt
total 462912
-rw-rw-r-- 1 nesbo nesbo 474013648 Apr 14 15:11 reads.lib.bin
-rw-rw-r-- 1 nesbo nesbo       159 Apr 14 15:10 reads.lib
-rw-rw-r-- 1 nesbo nesbo         7 Apr 14 15:10 cp.txt

And yes I submitted a batch job. I set the -m to 0.9 my memory limit is 250Gb. 

The Log:
MEGAHIT v1.1.1
--- [Wed Apr 12 09:02:18 2017] Start assembly. Number of CPU threads 24 ---
--- [Wed Apr 12 09:02:18 2017] Available memory: 271030964224, used: 243927867801
--- [Wed Apr 12 09:02:18 2017] Converting reads to binaries ---
/global/software/megahit/megahit111/bin/megahit_asm_core buildlib Megahitassemblies/tmp/reads.lib Megahitassemblies/tmp/reads.lib
    [read_lib_functions-inl.h  : 209]     Lib 0 (DG074_161215_NextSeq_trim_paired.good_1.fa,DG074_161215_NextSeq_trim_paired.good_2.fa): pe, 88530380 reads, 151 max length
    [utils.h                   : 126]     Real: 376.0422	user: 113.2728	sys: 8.1698	maxrss: 165920
--- [Wed Apr 12 09:09:39 2017] k list: 21,29,39,59,79,99,119,141 ---
--- [Wed Apr 12 09:09:39 2017] Extracting solid (k+1)-mers for k = 21 ---
cmd: /global/software/megahit/megahit111/bin/megahit_sdbg_build count -k 21 -m 2 --host_mem 243927867801 --mem_flag 1 --gpu_mem 0 --output_prefix Megahitassemblies/tmp/k21/21 --num_cpu_threads 24 --num_output_threads 8 --read_lib_file Megahitassemblies/tmp/reads.lib
    [sdbg_builder.cpp          : 112]     Host memory to be used: 243927867801
    [sdbg_builder.cpp          : 113]     Number CPU threads: 24
    [cx1.h                     : 450]     Preparing data...
    [read_lib_functions-inl.h  : 256]     Before reading, sizeof seq_package: 3839854368
    [read_lib_functions-inl.h  : 260]     After reading, sizeof seq_package: 3839854368
    [cx1_kmer_count.cpp        : 136]     0 reads, 0 max read length
    [cx1.h                     : 457]     Preparing data... Done. Time elapsed: 0.4674
    [cx1.h                     : 464]     Preparing partitions and initialing global data...
    [cx1_kmer_count.cpp        : 227]     2 words per substring, 2 words per edge
    [cx1_kmer_count.cpp        : 364]     Memory for reads: 3839854400
    [cx1_kmer_count.cpp        : 365]     max # lv.1 items = 0
    [cx1.h                     : 480]     Preparing partitions and initialing global data... Done. Time elapsed: 0.1031
    [cx1.h                     : 486]     Start main loop...
Bucket 65536 too large for lv1: 0 > 0
Error occurs when running "sdbg_builder count/read2sdbg", please refer to Megahitassemblies/log for detail
[Exit code 1]

**Comment by camillaln** [comment]
I am now running it on another server with more memory and it is working fine!
