### ISSUE TITLE
GFA output

### ISSUE THREAD

**Issue by russianconcussion** [voutcn/megahit#116]
Hi, I was looking for the graph representation of the assembly and noticed that megahit_toolkit has a contig2fastg function.  Is it possible to implement a function that gets the graph in [Graphical Fragment Assembly](https://github.com/GFA-spec/GFA-spec) format (version 1)? I'd like to add the graph as a reference graph for the [vg](https://github.com/vgteam/vg) variation graph tool. I know that there are utilities for converting from fastg to GFA, but I'm not sure what kind of information would be lost in converting from fastg to GFA format. Thanks for your consideration!

**Comment by aquaskyline** [comment]
fastg2gfa by Heng Li might help you - https://github.com/lh3/gfa1/commit/b5a7c03a134f2f47b368e3d99e2a818c22df068c

**Comment by aquaskyline** [comment]
Basically Megahit is similar to Spades in generating Fastg, so the fastg2gfa (you might have already tried this utility) is suitable in converting Megahit's FASTG to GFA.
