### ISSUE TITLE
Megahit not completing execution in ubuntu 16.04

### ISSUE THREAD

**Issue by quokkamole** [voutcn/megahit#117]
Hi.

I can get megahit (v1.1.1) to work as expected (either by compiling it myself or using precompiled binaries) on a CentOS (6.8) based system.

The same version of megahit initially appears to run on my Ubuntu (16.04) virtual machine but no contigs are assembled and there are no errors displayed. The command I am using for testing purposes is:

`/media/sf_sharez/opt/perl_megahit/megahit_v1.1.1_LINUX_CPUONLY_x86_64-bin/megahit -t 1 -m 1000000000 --verbose -r /media/sf_sharez/opt/perl_megahit/input/readsInterleaved3.fa -o /media/sf_sharez/opt/perl_megahit/output/assembly`

On Ubuntu, STDOUT only displays:

```
MEGAHIT v1.1.1
--- [Sat Apr 22 16:17:24 2017] Start assembly. Number of CPU threads 1 ---
--- [Sat Apr 22 16:17:24 2017] Available memory: 12828946432, used: 1000000000
```

..and the resulting assembly folder contains a tmp folder (with reads.lib and cp.txt). An empty 'intermediate_contigs' folder is also created. No errors are observed.

Up-to-date dependencies are installed (zlib1g-dev is the newest version (1:1.2.8.dfsg-2ubuntu4). Python 2.7.12 is installed. Output of g++ --version is g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609 ). 

Any hints on where this could be going wrong?

**Comment by quokkamole** [comment]
After some testing I have found that this problem only occurs if I attempt to run the program from a shared host folder (Windows 10, NTFS) that is mounted in my Linux guest. Not exactly sure why this program in particular doesn't work under these conditions but the simple workaround is to launch it directly from a folder on the guest file system. Probably not a common enough problem to deserve attention (although I kind of wish it was).

**Comment by voutcn** [comment]
Megahit uses [fifo](https://en.wikipedia.org/wiki/Named_pipe) for gzip or bzip2 input. I am not sure whether there are any compatibility issues on an NTFS directory.

**Comment by aquaskyline** [comment]
NTFS doesn't support unix pipe.

**Comment by rec3141** [comment]
I've also had this problem (for SPAdes too) and in both you can work around it by setting --tmp-dir /tmp (or any other Virtualbox-local directory)
