### ISSUE TITLE
use of multiple pe libaries with -12

### ISSUE THREAD

**Issue by osvatic** [voutcn/megahit#118]
I am attempting to assemble contigs from multiple pe libraries (breifly mentioned in "An example of a real assembly"). I am using multiple -12 options and it does not appear to be working. Is there a correct way to add multiple libraries into the command?

**Comment by celiosantosjr** [comment]
And I'm trying to do a coassembly, using the oposite command, like write several files using unique -12, well it doesnt work also. In my case, megahit just process and assembly the first library.

**Comment by voutcn** [comment]
@osvatic @celiosantosjr 
First the option is `--12` rather than `-12`.
The following usage should work well:
`--12 FILE1 --12 FILE2 --12 FILE3`
or 
`--12 FILE1,FILE2,FILE3`
