### ISSUE TITLE
Error code -11

### ISSUE THREAD

**Issue by richardda96** [voutcn/megahit#120]
Hi,

I'm trying to run megahit using GPU processing (CUDA 7.5.18) and it successfully compiles, however running it on a toy example (~2GB metagenome) I consistently get an 'exit code -11' when it starts assembling contigs. I'm giving it 40GB of ram, which I thought was overkill.
I've attached a copy of my log; doing this 5 or 6 times the program always fails at the same step with the same error. It's worth noting that the compiled megahit fails whether I use the --use-gpu flag or not.

Thanks.
[log.txt](https://github.com/voutcn/megahit/files/1005813/log.txt)

**Comment by voutcn** [comment]
Would you mind sharing me all files in the folder `megahit_CUDA_test5/tmp/k21` to debug?

**Comment by voutcn** [comment]
Or please follow https://github.com/voutcn/megahit/issues/122
