### ISSUE TITLE
Redesign logging system for debugging

### ISSUE THREAD

**Issue by voutcn** [voutcn/megahit#121]
Some users reported that they saw `exit code -11`. The code -11 is segmentation fault. Without data, we need detail logs to debug. Current logging system is not useful enough.

**Comment by epruesse** [comment]
On Linux, you could link against `libSegFault` to get backtraces on segmentation faults (`-lSegFault -Wl,--no-as-needed`. This shouldn't cause performance degradation, it installs a signal handler and acts only once signal 11 is raised. 

For best results, you could add a `--continue-with-debug` option to the python wrapper. If that were to use debug-binaries compiled with `-g -O1` or so in addition to using `libSegFault`, you should get some rather useful logs.

**Comment by alienzj** [comment]
spdlog is a great c++ log library.

**Comment by alienzj** [comment]
https://github.com/gabime/spdlog
