### ISSUE TITLE
General process for reporting "Exit code -11" error

### ISSUE THREAD

**Issue by voutcn** [voutcn/megahit#122]
"Exit code -11" means a segmentation fault. Currently, it is difficult for the develop to localize the crashing point from the log file only. We want the users to launch gdb and provide us more information. The general process is
1. Open the log file in your output directory
2. Find the **last** line that starts with `cmd:`. For example:
```
cmd: /home/my_user/megahit/megahit_asm_core assemble -s megahit_CUDA_test5/tmp/k21/21 -o megahit_CUDA_test5/intermediate_contigs/k21 -t 8 --min_standalone 300.0 --prune_level 2 --merge_len 20 --merge_similar 0.95 --low_local_ratio 0.2 --min_depth 2 --bubble_level 2 --max_tip_len -1 --careful_bubble
```
3. Relaunch this command using gdb, using the example above, you should run:
```
gdb -arg /home/my_user/megahit/megahit_asm_core assemble -s megahit_CUDA_test5/tmp/k21/21 -o megahit_CUDA_test5/intermediate_contigs/k21 -t 8 --min_standalone 300.0 --prune_level 2 --merge_len 20 --merge_similar 0.95 --low_local_ratio 0.2 --min_depth 2 --bubble_level 2 --max_tip_len -1 --careful_bubble
```
4. Enter `r` and press Enter to run gdb, and the problem should crash somewhere. Then enter `bt` and press Enter to print out the traceback path.
5. Attach the output of gdb as well as the log file.

**Comment by epruesse** [comment]
If all you want is the backtrace, try `catchsegv megahit_asm_core assemble ...`. The tool comes with glibc -- it's in the same package as `ldd`, so it should be available everywhere.

> Currently, it is difficult for the develop to localize the crashing point from the log file only. 

`catchsegv` uses `libSegfault` in the background. In theory, you could link against that to get the catching behavior at all times with `-lSegFault -Wl,--no-as-needed` (shouldn't cause performance degradation, it installs a signal handler and acts only once signal 11 is raised). 

For best results, you could add a `--continue-with-debug` option to the python wrapper. If that were to use debug-binaries compiled with `-g -O1` or so in addition to using libSegFault, you should get some rather useful logs.

**Comment by voutcn** [comment]
@epruesse cool! Thx!
