### ISSUE TITLE
Megahit sleeps long while

### ISSUE THREAD

**Issue by jayceejiao** [voutcn/megahit#123]
Hi,

I'm assembling a large genome (5G, 140X) using megahit. I can complete the whole process using single Kmer (127). However, when I included multiple Kmers (33,55,77,99,121,141,169,197) , it has been sleeping for more than one week in the first Kmer (33) extracting step, consuming 52% of the total RAM. Is it normal? Will the program get through the whole process? Do you have any suggestions?

Thanks!

**Comment by voutcn** [comment]
It is not normal. Please attach your log. Also, could you use `top` or `htop` to get the CPU usage of megahit?

**Comment by jayceejiao** [comment]
This the used command line: 
megahit -1 PG1_R1.paired.gz,PG2_R1.paired.gz,PG3_R1.paired.gz,PG4_R1.paired.gz,PG5abcd_R1.paired.gz,PG6a_R1.paired.gz,PG6b_R1.paired.gz -2 PG1_R2.paired.gz,PG2_R2.paired.gz,PG3_R2.paired.gz,PG4_R2.paired.gz,PG5abcd_R2.paired.gz,PG6a_R2.paired.gz,PG6b_R2.paired.gz --min-contig-len 100 -m 0.85 --k-list 33,55,77,99,121,141,169,197 -t 72 -o k_list.megahit_asm 

log file:
[log.txt](https://github.com/voutcn/megahit/files/1056778/log.txt)

It only uses 3 or 2 CPUs for a week :
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
36105 chen      20   0  0.792t 0.502t   1924 S 299.0 51.6  31364:20 megahit_sdbg_bu

Thanks for your help!

**Comment by jayceejiao** [comment]
Hi, when I increased the kmer to 77, I got another error "Exit code -11". Thanks.

**Comment by voutcn** [comment]
I believe the causes of the two errors are the same. Could you follow this post (https://github.com/voutcn/megahit/issues/122) to provide me more information? Thx!
