### ISSUE TITLE
Megahit vs others

### ISSUE THREAD

**Issue by davidvilanova** [voutcn/megahit#124]
Just for your info.
Came across a comparison of assembly tools. The authors claim Megahit and Metaspades/Spades are performing better. However in tems of computing time Megahit is far better than the others.

http://biorxiv.org/content/biorxiv/early/2017/06/06/120154.full.pdf

<img width="1068" alt="screen shot 2017-06-09 at 09 35 13" src="https://user-images.githubusercontent.com/11404840/26965884-1f1b93cc-4cf8-11e7-8f9d-62d2df633b9f.png">

**Comment by aquaskyline** [comment]
Thanks David for the information, we will keep on improving Megahit.
