### ISSUE TITLE
compile errors

### ISSUE THREAD

**Issue by hudenise** [voutcn/megahit#126]
i tried compiling megahit on a linux machine with gcc version 4.8.5 . and it doesn't work:
i get the following error:
make
  g++ -g -O2 -Wall -Wno-unused-function -Wno-array-bounds -D__STDC_FORMAT_MACROS -funroll-loops -fprefetch-loop-arrays -fopenmp -I. -std=c++0x -static-libgcc -m64 -static-libstdc++ -mpopcnt -DPACKAGE_VERSION="\"v1.1.1-2-g02102e1\"" asm_core.o assembler.o local_assemble.o iterate_edges.o build_read_lib.o lib_idba/contig_graph.o lib_idba/contig_graph_branch_group.o lib_idba/contig_info.o lib_idba/hash_graph.o lib_idba/sequence.o succinct_dbg.o assembly_algorithms.o options_description.o unitig_graph.o sequence_manager.o local_assembler.o city.o -lm -lz -lpthread -o megahit_asm_core
/usr/bin/ld: cannot find -lstdc++
  collect2: error: ld returned 1 exit status

I was able to compile with  gcc version 4.4.7

**Comment by aquaskyline** [comment]
You need to install proper version of GLIBCXX for your new gcc before you can use it to compile Megahit.
