### ISSUE TITLE
How to use SOAPdenovo-fusion scaffold the output of MEGAHIT?

### ISSUE THREAD

**Issue by YiweiNiu** [voutcn/megahit#129]
Hi,
I'm using MEGAHIT for genome assembly of an insect (~800Mbp), and I found that the manual of [SOAPdenovo2](https://github.com/aquaskyline/SOAPdenovo2) mentioned that SOAPdenovo-fusion can be used to scaffold the contigs produced by MEGAHIT. But there are few documents about how to do it, such as how can I choose K-mer for SOAPdenovo-fusion? 
Any suggestions or thoughts would be appreciated.

Best,
Yiwei Niu

**Comment by aquaskyline** [comment]
Answered in SOAPdenovo2 repo.
