### ISSUE TITLE
Megahit compilation error on cygwin64

### ISSUE THREAD

**Issue by SRAnalyse** [voutcn/megahit#131]
I have recently downloaded Megahit and have simply entered the following command:

> ./megahit -r ./example/refExample.fa --k-max 99 --k-min 11

However, the returns is as follow:

> Traceback (most recent call last):

> File "./megahit", line 1143, in "<"module>
>   sys.exit(main())

>File "./megahit", line 1067, in main 
>    get_version()

>  File "./megahit", line 526, in
> get_version
  
>  stdout=subprocess.PIPE).communicate()[0].rstrip().decode('utf-8'))

>ValueError: invalid literal for int() with base 10:

The system base I am using is Window 64bit with cygwin64.
I am having python version 2.7.13 from cygwin.

I have tried to directly define the `max_k_allowed` to be 127 instead of `int(subprocess.Popen([opt.bin_dir + "megahit_asm_core", "kmax"],
                                           stdout=subprocess.PIPE).communicate()[0].rstrip().decode('utf-8'))` which leads to the error.

However, this time and error occurred in the buildlib process where message `"Error occurs when running \"megahit_asm_core buildlib\"; please refer to %s for detail"` popped out.

There has already been an error when doing the `make` command on cygwin where the stdio.h file cannot be included and has to be manually included by defining the directory of the stdio.h for most of the cpp file.

Does this seems to be a problem on my cygwin?

Thanks a lot!

**Comment by aquaskyline** [comment]
I have not tested Megahit in Cygwin64, but I'm sure you will run into problems because Megahit relies on several operation system specific functions. We recommend you to run Megahit in a native Linux system.
