### ISSUE TITLE
what's the meanings of  "flag" and "multi" in sequence headers?

### ISSUE THREAD

**Issue by hulqi** [voutcn/megahit#132]
e.g. 
>k149_10 flag=1 multi=2.0000 len=462
what's the meanings of  "flag" and "multi"?  I really appreciate your help.

**Comment by aquaskyline** [comment]
flag=1 means an isolated contig with in-degree and out-degree equals to 0. multi means the multiplicity or the depth of the contig.

**Comment by voutcn** [comment]
https://github.com/voutcn/megahit/issues/54
