### ISSUE TITLE
Error occurs when running "sdbg_builder count/read2sdbg"

### ISSUE THREAD

**Issue by mingjiew** [voutcn/megahit#135]
Hi,

I am using MEGAHIT v1.1.1 and encountered the following error:

MEGAHIT v1.1.1
--- [Thu Aug  3 10:08:43 2017] Start assembly. Number of CPU threads 64 ---
--- [Thu Aug  3 10:08:43 2017] Available memory: 2164212604928, used: 1731370083942
--- [Thu Aug  3 10:08:43 2017] Converting reads to binaries ---
/bioinformatics/sgi/asmopt/bio_bin/megahit/megahit_v1.1.1_LINUX_CPUONLY_x86_64-bin/megahit_asm_core buildlib megahit_KW34_k21_c2_s12/tmp/reads.lib megahit_KW34_k21_c2_s12/tmp/reads.lib
    [read_lib_functions-inl.h  : 209]     Lib 0 (KW34_2017_rerun2_rerun1_2016.trimmed.fasta): interleaved, 1072931172 reads, 151 max length
    [utils.h                   : 126]     Real: 1041.4230	user: 923.8023	sys: 111.8519	maxrss: 162796
--- [Thu Aug  3 10:26:04 2017] k list: 21,33,45,57,69,81,93,105,117,129,141 ---
--- [Thu Aug  3 10:26:04 2017] Extracting solid (k+1)-mers for k = 21 ---
cmd: /bioinformatics/sgi/asmopt/bio_bin/megahit/megahit_v1.1.1_LINUX_CPUONLY_x86_64-bin/megahit_sdbg_build count -k 21 -m 2 --host_mem 1731370083942 --mem_flag 1 --gpu_mem 0 --output_prefix megahit_KW34_k21_c2_s12/tmp/k21/21 --num_cpu_threads 64 --num_output_threads 21 --read_lib_file megahit_KW34_k21_c2_s12/tmp/reads.lib
    [sdbg_builder.cpp          : 112]     Host memory to be used: 1731370083942
    [sdbg_builder.cpp          : 113]     Number CPU threads: 64
    [cx1.h                     : 450]     Preparing data...
    [read_lib_functions-inl.h  : 256]     Before reading, sizeof seq_package: 47258648824
    [read_lib_functions-inl.h  : 260]     After reading, sizeof seq_package: 47258648824
    [cx1_kmer_count.cpp        : 136]     1072931172 reads, 151 max read length
    [cx1.h                     : 457]     Preparing data... Done. Time elapsed: 215.6305
    [cx1.h                     : 464]     Preparing partitions and initialing global data...
    [cx1_kmer_count.cpp        : 227]     2 words per substring, 2 words per edge
    [cx1_kmer_count.cpp        : 364]     Memory for reads: 48467248832
    [cx1_kmer_count.cpp        : 365]     max # lv.1 items = 17622565752
    [cx1.h                     : 480]     Preparing partitions and initialing global data... Done. Time elapsed: 61.5059
    [cx1.h                     : 486]     Start main loop...
    [cx1.h                     : 515]     Lv1 scanning from bucket 0 to 2558
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 61.6746
megahit_sdbg_build: edge_io.h:93: void EdgeWriter::write(uint32_t*, int32_t, int): Assertion `p_rec_[bucket].thread_id == -1' failed.
Error occurs when running "sdbg_builder count/read2sdbg", please refer to megahit_KW34_k21_c2_s12/log for detail
[Exit code -6] 

Does anyone know why this occurred?

Thanks,
Mingjie

**Comment by voutcn** [comment]
Could you try the latest version https://github.com/voutcn/megahit/releases/tag/v1.1.2?
