### ISSUE TITLE
Error occurs when running "sdbg_builder count/read2sdbg" [Exit code 1]

### ISSUE THREAD

**Issue by KarinH5** [voutcn/megahit#139]
Hi,

for assembling my metagenomic data I want to use Megahit. To get familiar with the program, I tried to run "An example of real assembly" as presented on the homepage. It seems quite stright forward and not as difficult. However, I receive an error message while doing the assembly. 

It would be very helpful to receive an answer how to deal with this problem, soon. 

Thanks a lot in advance!

Karin

MEGAHIT v1.1.2
--- [Tue Sep 26 21:34:51 2017] Start assembly. Number of CPU threads 1 ---
--- [Tue Sep 26 21:34:51 2017] Available memory: 1041502208, used: 937351987
--- [Tue Sep 26 21:34:51 2017] Converting reads to binaries ---
/home/qiime/megahit/megahit_asm_core buildlib SRR341725.megahit_asm/tmp/reads.lib SRR341725.megahit_asm/tmp/reads.lib
    [read_lib_functions-inl.h  : 209]     Lib 0 (SRR341725_1.fastq.gz,SRR341725_2.fastq.gz): pe, 25479128 reads, 90 max length
    [utils.h                   : 126]     Real: 116.3790	user: 15.1142	sys: 1.4956	maxrss: 155688
--- [Tue Sep 26 21:36:47 2017] k-max reset to: 109 ---
--- [Tue Sep 26 21:36:47 2017] k list: 21,29,39,59,79,99,109 ---
--- [Tue Sep 26 21:36:47 2017] Extracting solid (k+1)-mers for k = 21 ---
cmd: /home/qiime/megahit/megahit_sdbg_build count -k 21 -m 2 --host_mem 937351987 --mem_flag 1 --gpu_mem 0 --output_prefix SRR341725.megahit_asm/tmp/k21/21 --num_cpu_threads 1 --num_output_threads 1 --read_lib_file SRR341725.megahit_asm/tmp/reads.lib
    [sdbg_builder.cpp          : 112]     Host memory to be used: 937351987
    [sdbg_builder.cpp          : 113]     Number CPU threads: 1
    [cx1.h                     : 450]     Preparing data...
    [read_lib_functions-inl.h  : 256]     Before reading, sizeof seq_package: 777066264
    [read_lib_functions-inl.h  : 260]     After reading, sizeof seq_package: 777066264
    [cx1_kmer_count.cpp        : 136]     25479128 reads, 90 max read length
    [cx1.h                     : 457]     Preparing data... Done. Time elapsed: 17.4682
    [cx1.h                     : 464]     Preparing partitions and initialing global data...
    [cx1_kmer_count.cpp        : 227]     2 words per substring, 2 words per edge
    [cx1_kmer_count.cpp        : 322]     Set: 951144460, 87743883
    [cx1.h                     : 171]     Adjusting memory layout: max_lv1_items=234382831, num_sorting_items=567214, mem_sorting_items=13613136, mem_avail=87743883
    [ERROR] [cx1.h                    : 188]: No enough memory to process CX1.
Error occurs when running "sdbg_builder count/read2sdbg", please refer to SRR341725.megahit_asm/log for detail
[Exit code 1]

**Comment by aquaskyline** [comment]
```
[cx1.h : 171] Adjusting memory layout: max_lv1_items=234382831, num_sorting_items=567214, mem_sorting_items=13613136, mem_avail=87743883
[ERROR] [cx1.h : 188]: No enough memory to process CX1.
```

You ran out of memory.
