### ISSUE TITLE
[ERROR] Too many vertices in the unitig graph

### ISSUE THREAD

**Issue by Sebastien-Raguideau** [voutcn/megahit#141]
Hello, 
I am trying to run Megahit on 45 samples with paired ends amounting to around 200 G in fastq.gz. For this particular assembly, the process stopped due to too many vertices in the unitig graph. I saw that this problem is related to this variable kMaxNumVertices, is there a way to change it in order to allow for this assembly?
I joined the log of the assembly. 
[log.txt](https://github.com/voutcn/megahit/files/1394343/log.txt)
Best
Seb

**Comment by voutcn** [comment]
Changing `typedef uint32_t vertexID_t` to `typedef uint64_t vertexID_t` https://github.com/voutcn/megahit/blob/master/unitig_graph.h#L74 may help (I haven't tried). But I don't think this is a good way. Too many vertices in the unitig graph means that the graph is unexpectedly complex.

A better way is using a larger k_min, say 27 or 31. And you can do this without modifying the source code.

**Comment by Sebastien-Raguideau** [comment]
Thanks I will try with changing k_min and see how it works.

**Comment by Sebastien-Raguideau** [comment]
Late update, just starting with k_min=23 was sufficient to allow for assembly. Quality was similar to expected. So it all worked out. 
Thanks,
Seb
