### ISSUE TITLE
Reads usage

### ISSUE THREAD

**Issue by whynotlih** [voutcn/megahit#143]
Hi!
If I want to find out how many reads were used in the megahit‘s assembly, is there some toolkits in metahit?
Thank!

**Comment by voutcn** [comment]
You will need to align reads to the contigs and see how many of them can be aligned. Though a bit out-dated, [this post](https://github.com/voutcn/megahit/wiki/An-example-of-real-assembly#4-calculate-contig-coverage-and-extract-unassembled-reads) may be helpful.

**Comment by whynotlih** [comment]
OK, I got it, thank you!-------- 原始邮件 --------主题：Re: [voutcn/megahit] Reads usage (#143)发件人：Dinghua Li 收件人：voutcn/megahit 抄送：whynotlih ,Author You will need to align reads to the contigs and see how many of them can be aligned. Though a bit out-dated, this post may be helpful.
