### ISSUE TITLE
co-assembly

### ISSUE THREAD

**Issue by alienzj** [voutcn/megahit#144]
Hello, voutcn,
can I use megahit to do co-assembly?
I have many samples metagenomics sequence, paired-end reads and remove host single reads,  then I want to use megahit to do a co-assembly before binning with MetaBAT, so maybe megahit  need a lot of memory.

Thanks very much
Best wishes

**Comment by voutcn** [comment]
Yes, it can do co-assembly. How big is your data?

**Comment by alienzj** [comment]
285 samples, 2T data.

**Comment by voutcn** [comment]
It is super huge. Hopefully, it can be assembled in 1T RAM. 

If you don't have a server equipped with that much RAM, please try to use BBNorm or khmer to normalize the dataset first. It should be okay to normalize the depth to 70x.

If the data comes from "wild" environment like soil or wetland, the option `--preset meta-large` is recommended.

**Comment by alienzj** [comment]
Thanks very much!
I will try it!
