### ISSUE TITLE
exit code 1 : unrecognized option '--bubble_level' with --presets meta-large

### ISSUE THREAD

**Issue by aparada** [voutcn/megahit#145]
Hello,
I am getting the an 'exit code 1' error when trying to assemble some metagenomes, and the log appears to indicates
'assemble: unrecognized option '--bubble_level'
uknown option'

Below is the command I used, and the error. I've also attached the log file. I should also note that I get the same error without the -m parameter. Any suggestions?

megahit -1 4LO_forward_paired_5_subsampled.fastq.gz -2 4LO_reverse_paired_5_subsampled.fastq.gz -o megahit_4LO_5 --presets meta-large -t 50 -m 0.5

1007.0Gb memory in total.
Using: 503.933Gb.
MEGAHIT v1.0.3-29-g707d683
--- [Sun Nov 19 11:48:52 2017] Start assembly. Number of CPU threads 50 ---
--- [Sun Nov 19 11:48:52 2017] Available memory: 1082187350016, used: 541093675008
--- [Sun Nov 19 11:48:52 2017] Converting reads to binaries ---
    [read_lib_functions-inl.h  : 209]     Lib 0 (4LO_forward_paired_5_subsampled.fastq.gz,4LO_reverse_paired_5_subsampled.fastq.gz): pe, 5362132 reads, 150 max length
    [utils.h                   : 124]     Real: 7.5402  user: 5.7990    sys: 0.8520     maxrss: 165156
--- [Sun Nov 19 11:48:59 2017] k list: 27,37,47,57,67,77,87,97,107,117,127 ---
--- [Sun Nov 19 11:48:59 2017] Extracting solid (k+1)-mers and building sdbg for k = 27 ---
--- [Sun Nov 19 11:49:50 2017] Assembling contigs from SdBG for k = 27 ---
Error occurs when assembling contigs for k = 27, please refer to megahit_4LO_5/log for detail
[Exit code 1]

Log:
[megahit.log](https://github.com/voutcn/megahit/files/1485919/megahit.log)

**Comment by voutcn** [comment]
Please use the latest version v1.1.2.
