### ISSUE TITLE
Assertion failed in SdbgReader

### ISSUE THREAD

**Issue by sjaenick** [voutcn/megahit#146]
MegaHIT 1.1.2 (binary release), with options --preset meta-large -m 0.95 -t 94,
last log entries:

--- [Fri Nov 24 09:18:35 2017] Assembling contigs from SdBG for k = 57 ---
cmd: /data/megahit_v1.1.2_LINUX_CPUONLY_x86_64-bin/megahit_asm_core assemble -s megahit_XXX/tmp/k57/57 -o megahit_XXX/intermediate_contigs/k57 -t 94 --min_standalone 300.0 --prune_level 2 --merge_len 20 --merge_similar 0.95 --low_local_ratio 0.2 --min_depth 2 --bubble_level 2 --max_tip_len -1 --careful_bubble
b'    [assembler.cpp             : 148]     Loading succinct de Bruijn graph: megahit_XXX/tmp/k57/57 megahit_asm_core: sdbg_multi_io.h:243: void SdbgReader::read_info(): Assertion `fscanf(sdbg_info, "k %d\\n", &kmer_size_) == 1\' failed.'
Error occurs when assembling contigs for k = 57, please refer to megahit_XXX/log for detail
[Exit code -6]

$ ls -l tmp/k??/*info
-rw-rw-r-- 1 ubuntu ubuntu 2312959 Nov 22 18:28 tmp/k27/27.sdbg_info
-rw-rw-r-- 1 ubuntu ubuntu    1292 Nov 23 09:45 tmp/k37/37.edges.info
-rw-rw-r-- 1 ubuntu ubuntu 2330010 Nov 23 11:46 tmp/k37/37.sdbg_info
-rw-rw-r-- 1 ubuntu ubuntu    1197 Nov 23 21:59 tmp/k47/47.edges.info
-rw-rw-r-- 1 ubuntu ubuntu 2312231 Nov 24 00:01 tmp/k47/47.sdbg_info
-rw-rw-r-- 1 ubuntu ubuntu    1197 Nov 24 07:40 tmp/k57/57.edges.info
-rw-rw-r-- 1 ubuntu ubuntu       0 Nov 24 09:18 tmp/k57/57.sdbg_info

Any additional info needed? Can this assembly be restarted?

**Comment by voutcn** [comment]
I am afraid that your server is running out of space. Could you check the disk usage?

**Comment by sjaenick** [comment]
Possible. 1TB data volume with 2 fastq files (~250GB total) before starting the assembly, and >200GB free after it aborted (but open fd's might have occupied disk space in between).

I'd guess the empty 57.sdbg_info file is causing the abort.

Maybe the code writing the .sdbg_info files doesn't check whether data was successfully written to disk?

**Comment by voutcn** [comment]
A bit strange that the disk still has >200GB free space. The file `57.sdbg_info` should be smaller than 2Kb.
Could you try restarting the assembly ( from scratch, `--continue` flag will not work). If you are afraid that 1T space is not enough, I suggest using BBNorm or Khmer to normalize the reads, to a target depth of about 70x.
I will review the source code when I have time.

**Comment by sjaenick** [comment]
Cannot reproduce for recent releases, closing..
