### ISSUE TITLE
trying megahit to re-assemble contigs from different samples

### ISSUE THREAD

**Issue by mlozada** [voutcn/megahit#147]
Hello,
I have a sequence dataset corresponding to the already assembled fraction of three independent samples from the same site (biological replicates). My aim is to use these samples altogether to re-assembly with megahit, as the samples are similar I know that some contigs can be further merged. We want to do this due to the poor assembly efficiency we obtained in the first step (each sample alone). My dataset is like this: single end (they are already contigs), minlength 500 bp , maxlength 147773 bp , N50 1306. 

I have successfully compiled and run megahit on this dataset with options:
 megahit -r assembled.OR.500.fa --preset meta-large -o OR500_metalarge 

everything seems to work well, but got strange results for the output:
result of running two well known python scripts for description of the dataset:
name             alignment    min_len   max_len   avg_len  num_seqs
final.contigs.fa FALSE            200     67728   1100.45    123841

Load file `final.contigs.fa`
File, #_seqs, #_reals, #_Ns, Total, Min, Max, N50
final.contigs.fa, 123841, 136280315, 0, 136280315, 200, 67728, 1341

This is the statistic for the input:
Load file `assembled.OR.500.fa`
File, #_seqs, #_reals, #_Ns, Total, Min, Max, N50
assembled.OR.500.fa, 178054, 205195799, 63460, 205259259, 500, 147773, 1306

As you can see, I get many sequences which are 200 bp, which is less than the shorter sequence in the input file. Is that correct? I can see that there are no Ns in the output, can it be the case that megahit trims these regions and therefore the shorter reads? In addition, the larger sequence in the new assembly is also shorter (however I understand that this could be due to the fact that some of the originally long contigs are not joined with any other sequence and so they are not kept in the output file)

how is it possible to have shorter sequences in output than in the input?
maybe it is not correct to use megahit  for this purpose? should I change any other option to better match my dataset characteristics? 
thank you

**Comment by voutcn** [comment]
It is not a good idea to use an NGS short read assembler to merge assembled contigs.
Some reasons:
- Assemblers may presume a sufficient sequencing depth of a dataset, but roughly speaking, the depth assembled config is 1
- Most NGS assemblers are de Bruijn graph based, it will break long sequences into k-mers, that's why you got shorter contigs

I suggest to co-assemble the three samples, using unassembled reads instead of contigs.
