### ISSUE TITLE
Settings from MEGAHIT paper

### ISSUE THREAD

**Issue by bkj** [voutcn/megahit#148]
Do you have the parameters for the experiment in [the MEGAHIT paper](https://arxiv.org/pdf/1409.7208.pdf)?

available somewhere?  Are they the parameters given on this [page](https://hku-bal.github.io/megabox/greprachallenge/IowNatreferecore-v1.0.1.html)?

Also, are the datasets used eg `mgm4539514.3.1.1371.qc.fastq.gz.fq.all.fna` from [here](http://metagenomics.anl.gov/mgmain.html?mgpage=download&metagenome=mgm4539514.3)?

**Comment by voutcn** [comment]
Raw reads: http://metagenomics.anl.gov/linkin.cgi?project=6377
Parameters: `--k-min 27 --k-max 87 --k-step 10 -m 370 000 000 000`.

**Comment by bkj** [comment]
Thanks!

Only some of the reads in those files appear to be paired --  the IDs look something like
```
@1461:1:1:1224:2031/1
@1461:1:1:1232:2067/1
@1461:1:1:1232:2090/1
@1461:1:1:1232:2090/2
@1461:1:1:1232:3000/1
@1461:1:1:1232:3000/2
@1461:1:1:1232:3050/2
@1461:1:1:1232:3061/2
```

How do you deal with this in MEGAHIT?  If I pass using the `--12` flag, I think it complains about there being an uneven number of 1s and 2s.  If I pass using the `--read` flag, I think it ignores all pairing information, which is presumably not what we want to do.

Any clarification would be super helpful.
