### ISSUE TITLE
Exit Code 1

### ISSUE THREAD

**Issue by bioInfo25** [voutcn/megahit#149]
Hello

I am currently trying to run Megahit for a metagenome assembly and I keep getting an error saying 
"_Error occurs when running "sdbg_builder count/read2sdbg", please refer to All_assembled_sequences_metagenomic/log for detail
[Exit code 1]_"

I have -m set to 2 and specified 256Gb on memory. Is this error occuring due to program running out of memory?

**Comment by voutcn** [comment]
Do you mean you used `-mem-flag 2 -m 256e9`?

**Comment by bioInfo25** [comment]
Hello

Yes sorry. Used those parameters. -m 256e9.

**Comment by voutcn** [comment]
Which version of Megahit were you using? How about using `-mem-flag 1 -m 256e9`.
