### ISSUE TITLE
Distribution of indegree and outdegree for contigs

### ISSUE THREAD

**Issue by sebhtml** [voutcn/megahit#15]
Operating system
==============
2.6.32-431.29.2.el6.x86_64

Compiler
=======
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-4)

Version
======
megahit/0.1.4-1

Dataset
======
Cow Rumen (SRS150404)

Command
========
```bash
./megahit -m 500000000000 --cpu-only -l 300 -o megahit-test-2015-01-23-2 \
    --input-cmd "zcat SRS150404/*.fastq.gz" \
    --k-min 21 --k-max 99 --k-step 10 \
    --min-count 2 \
    --num-cpu-threads 32 \
    | tee Log
```

Output
=======

[boisvert@bigmem foo]$ grep '>' megahit-test-2015-01-23-2/tmp/k21.final.contigs.fa|grep -v "_in_0_out_0"|grep -v loop |wc -l
0
[boisvert@bigmem foo]$ grep '>' megahit-test-2015-01-23-2/tmp/k31.final.contigs.fa|grep -v "_in_0_out_0"|grep -v loop |wc -l                                                                                                            
0
[boisvert@bigmem foo]$ grep '>' megahit-test-2015-01-23-2/tmp/k41.final.contigs.fa|grep -v "_in_0_out_0"|grep -v loop |wc -l                                                                                                            
1
[boisvert@bigmem foo]$ grep '>' megahit-test-2015-01-23-2/tmp/k41.final.contigs.fa|grep -v "_in_0_out_0"|grep -v loop
>contig_41_185619613_length_5

Question
=======

According to their names, all my (intermediate) contigs have a ingoing degree of 0 and an outdegree of 0 or they are loops:

I would expected some DNA repeats to produce an ingoing degree of 2 and/or an outgoing degree of 2.

Also, palindrome vertices are loops with 1 vertex, right ?

**Comment by voutcn** [comment]
1. Those intermediate files with suffix "final.contigs.fa" only contain contigs whose are indegree zero and outdegree or loops. These contigs have already been linear or loop paths isolated from the graph, therefore we don't need to pass them to the next iteration. We keep them in an intermediate file and merge them after all iterations are done. You will possibly see some contigs with in/out degree > 0 in the file *K_MAX.final.contigs.fa*.

2. Palindrome contigs is not a loop with 1 vertex. As we have an odd number requirement for *k*, there won't be any palindrome k-mers. However, the SdBG does not pack the a k-mer and its reverse-complement into one node, so there can be some paths like `D->C->B->A->A'->B'->C'->D'`, which represents a palindrome contig. MEGAHIT will “fold” the palindrome before output it.

**Comment by sebhtml** [comment]
Thank you.
