### ISSUE TITLE
parameters to get less processed assembly graph?

### ISSUE THREAD

**Issue by ctb** [voutcn/megahit#150]
hello, I have been looking into the contigs output by megahit and the resulting FASTG file (#20), and I noticed that in metagenomes with lots of strain variation, the FASTG file is for small k=27 is already missing many k-mers.  To me this suggests that the contig graph is already pretty heavily processed with error trimming and the like. Are there parameters you could suggest adjusting so that I can get a less processed output? Perhaps some of the ones in Advanced Assembly Parameters? Guidance welcome.

**Comment by voutcn** [comment]
You can try `--merge-level 0,1`.
If it doesn't work, please try the older version v1.0.6.1.
In version >= 1.1, I hardcode a parameter for more aggressive pruning. If you find that v1.0.6.1 can cover much more strain variation, I will release a new version to expose the parameter.
