### ISSUE TITLE
v1.1.2 does not link

### ISSUE THREAD

**Issue by cmeesters** [voutcn/megahit#151]
Hi

The release download of the current version does not link (GCC):

<snip>
g++ -g -O2 -Wall -Wno-unused-function -Wno-array-bounds -D__STDC_FORMAT_MACROS -funroll-loops -fprefetch-loop-arrays -fopenmp -I. -std=c++0x -static-libgcc -m64 -static-libstdc++ -mpopcnt asm_core.o assembler.o local_assemble.o iterate_edges.o build_read_lib.o lib_idba/contig_graph.o lib_idba/contig_graph_branch_group.o lib_idba/contig_info.o lib_idba/hash_graph.o lib_idba/sequence.o succinct_dbg.o assembly_algorithms.o options_description.o unitig_graph.o sequence_manager.o local_assembler.o city.o -lm -lz -lpthread -o megahit_asm_core
local_assembler.cpp:604: error: undefined reference to 'WriteFasta(std::ostream&, Sequence const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'

A fix would be nice.

Best regards,
Christian Meesters

**Comment by voutcn** [comment]
Which version of GCC were u using? The compilation should be okay with GCC >= 4.4.7.
