### ISSUE TITLE
problem running with gpu

### ISSUE THREAD

**Issue by eranbio** [voutcn/megahit#152]
I am trying to run megahit with gpu on a machine with large RAM (~500GB) with read files which are quite small (about 2x3M plus 1M unpaired reads).

**This what I get:**

./megahit -1 /home/users/bioinf/erane/assembly_run_tests/L1_1.fq.gz -2 /home/users/bioinf/erane/assembly_run_tests/L1_2.fq.gz -r /home/users/bioinf/erane/assembly_run_tests/L1_unpaired.fq.gz -o megahit0.3 --merge-level 20,0.92 --kmin-1pass --min-contig-len 100 --min-count 2 --k-min 31 --k-step 20 --k-max 155 --use-gpu  -t 2
503.0Gb memory in total.
Using: 453.145Gb.
MEGAHIT v1.1.2
--- [Sun Jan  7 18:06:20 2018] Start assembly. Number of CPU threads 2 ---
--- [Sun Jan  7 18:06:20 2018] Available memory: 540622774272, used: 486560496844
--- [Sun Jan  7 18:06:20 2018] Converting reads to binaries ---
    [read_lib_functions-inl.h  : 209]     Lib 0 (/home/users/bioinf/erane/assembly_run_tests/L1_1.fq.gz,/home/users/bioinf/erane/assembly_run_tests/L1_2.fq.gz): pe, 5603494 reads, 151 max length
    [read_lib_functions-inl.h  : 209]     Lib 1 (/home/users/bioinf/erane/assembly_run_tests/L1_unpaired.fq.gz): se, 262575 reads, 151 max length
    [utils.h                   : 126]     Real: 35.3418 user: 10.3383   sys: 0.8048     maxrss: 166296
--- [Sun Jan  7 18:06:56 2018] k list: 31,51,71,91,111,131,151,155 ---
--- [Sun Jan  7 18:06:56 2018] Extracting solid (k+1)-mers and building sdbg for k = 31 ---
Error occurs when running "sdbg_builder count/read2sdbg", please refer to megahit0.3/log for detail
[Exit code -6]

**In the log file I see the following:**

MEGAHIT v1.1.2
--- [Sun Jan  7 18:06:20 2018] Start assembly. Number of CPU threads 2 ---
--- [Sun Jan  7 18:06:20 2018] Available memory: 540622774272, used: 486560496844
--- [Sun Jan  7 18:06:20 2018] Converting reads to binaries ---
/home/users/bioinf/erane/software/megahit/megahit_asm_core buildlib megahit0.3/tmp/reads.lib megahit0.3/tmp/reads.lib
    [read_lib_functions-inl.h  : 209]     Lib 0 (/home/users/bioinf/erane/assembly_run_tests/L1_1.fq.gz,/home/users/bioinf/erane/assembly_run_tests/L1_2.fq
.gz): pe, 5603494 reads, 151 max length
    [read_lib_functions-inl.h  : 209]     Lib 1 (/home/users/bioinf/erane/assembly_run_tests/L1_unpaired.fq.gz): se, 262575 reads, 151 max length
    [utils.h                   : 126]     Real: 35.3418 user: 10.3383   sys: 0.8048     maxrss: 166296
--- [Sun Jan  7 18:06:56 2018] k list: 31,51,71,91,111,131,151,155 ---
--- [Sun Jan  7 18:06:56 2018] Extracting solid (k+1)-mers and building sdbg for k = 31 ---
cmd: /home/users/bioinf/erane/software/megahit/megahit_sdbg_build_gpu read2sdbg -k 31 -m 2 --host_mem 486560496844 --mem_flag 1 --gpu_mem 0 --output_prefix
 megahit0.3/tmp/k31/31 --num_cpu_threads 2 --num_output_threads 1 --read_lib_file megahit0.3/tmp/reads.lib --need_mercy
megahit_sdbg_build_gpu: lv2_gpu_functions.cu:38: void get_cuda_memory(size_t&, size_t&): Assertion `cudaMemGetInfo(&free_mem, &total_mem) == cudaSuccess' f
ailed.
Error occurs when running "sdbg_builder count/read2sdbg", please refer to megahit0.3/log for detail
[Exit code -6]

Without gpu I can run successfully.  I have played quite a bit with the --gpu-mem, -m and --mem-flag flags but with no success. I will appreciate any ideas. I am using CentOS and  Cuda-8.0.

**Comment by voutcn** [comment]
Megahit has not been tested on Cuda 8.
We do not plan to upgrade the GPU version of Megahit, because the CPU-only version is very fast already.

**Comment by ejgarza31** [comment]
I'm having the same issue but I'm running Cuda 7.0. Has megahit been tested with Cuda 7.0?
