### ISSUE TITLE
Binary release of the latest version

### ISSUE THREAD

**Issue by little-hunter** [voutcn/megahit#153]
Dear Author
        I would like to install Megahit and I have followed your instraction of installation (). However, I have always have the following problem:
g++ -g -O2 -Wall -Wno-unused-function -Wno-array-bounds -D__STDC_FORMAT_MACROS -funroll-loops -fprefetch-loop-arrays -fopenmp -I. -std=c++0x -static-libgcc -m64 -static-libstdc++ -mpopcnt -DPACKAGE_VERSION="\"v1.1.2\"" asm_core.o assembler.o local_assemble.o iterate_edges.o build_read_lib.o lib_idba/contig_graph.o lib_idba/contig_graph_branch_group.o lib_idba/contig_info.o lib_idba/hash_graph.o lib_idba/sequence.o succinct_dbg.o assembly_algorithms.o options_description.o unitig_graph.o sequence_manager.o local_assembler.o city.o -lm -lz -lpthread -o megahit_asm_core
g++ -g -O2 -Wall -Wno-unused-function -Wno-array-bounds -D__STDC_FORMAT_MACROS -funroll-loops -fprefetch-loop-arrays -fopenmp -I. -std=c++0x -static-libgcc -m64 -static-libstdc++ -mpopcnt -DPACKAGE_VERSION="\"v1.1.2\"" kthread.cpp sdbg_builder.cpp cx1_kmer_count.o options_description.o cx1_read2sdbg_s1.o cx1_read2sdbg_s2.o cx1_seq2sdbg.o sequence_manager.o -lm -lz -lpthread -o megahit_sdbg_build
g++ -g -O2 -Wall -Wno-unused-function -Wno-array-bounds -D__STDC_FORMAT_MACROS -funroll-loops -fprefetch-loop-arrays -fopenmp -I. -std=c++0x -static-libgcc -m64 -static-libstdc++ -mpopcnt -DPACKAGE_VERSION="\"v1.1.2\"" tools/toolkit.cpp tools/contigs_to_fastg.cpp tools/read_stat.cpp tools/trim_low_qual_tail.cpp tools/filter_by_len.cpp tools/extract_pe_reads.cpp -lm -lz -lpthread -o megahit_toolkit
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
make: *** [megahit_asm_core] Error 1
make: *** Waiting for unfinished jobs....
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
make: *** [megahit_toolkit] Error 1
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
make: *** [megahit_sdbg_build] Error 1.

I have also tried make -j8, make -j, git checkout debug. But the problem still exist. 
I have also checked my gcc version, it is 4.8.5(g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)). Does that cause problems in "make" predure? Since I'm afraid that I have no permission to change GCC version, would it possible to have alternative solutions? Would it possible to have a binary release of the latest version? 

Thank you very much for your reponse.

**Comment by little-hunter** [comment]
Dear  Author
         I have also tried in centos 6.5, so that gcc and g++ version is 4.4.7. However, I have encountered problems as following, could you please let me how can I fix them?
         Thank you very much. 
[root@localhost megahit]# make
g++ -g -O2 -Wall -Wno-unused-function -Wno-array-bounds -D__STDC_FORMAT_MACROS -funroll-loops -fprefetch-loop-arrays -fopenmp -I. -std=c++0x -static-libgcc -m64 -mpopcnt -DPACKAGE_VERSION="\"v1.1.2\"" -c succinct_dbg.cpp -o succinct_dbg.o
g++ -g -O2 -Wall -Wno-unused-function -Wno-array-bounds -D__STDC_FORMAT_MACROS -funroll-loops -fprefetch-loop-arrays -fopenmp -I. -std=c++0x -static-libgcc -m64 -mpopcnt -DPACKAGE_VERSION="\"v1.1.2\"" -c assembly_algorithms.cpp -o assembly_algorithms.o
g++ -g -O2 -Wall -Wno-unused-function -Wno-array-bounds -D__STDC_FORMAT_MACROS -funroll-loops -fprefetch-loop-arrays -fopenmp -I. -std=c++0x -static-libgcc -m64 -mpopcnt -DPACKAGE_VERSION="\"v1.1.2\"" -c options_description.cpp -o options_description.o
g++ -g -O2 -Wall -Wno-unused-function -Wno-array-bounds -D__STDC_FORMAT_MACROS -funroll-loops -fprefetch-loop-arrays -fopenmp -I. -std=c++0x -static-libgcc -m64 -mpopcnt -DPACKAGE_VERSION="\"v1.1.2\"" -c unitig_graph.cpp -o unitig_graph.o
unitig_graph.cpp: In member function ‘int UnitigGraph::SearchAndMergeSuperBubble_(int64_t, int, bool, FILE*, Histgram<long int>&)’:
unitig_graph.cpp:581: warning: comparison between signed and unsigned integer expressions
unitig_graph.cpp:528: warning: unused variable ‘num_tips’
In file included from hash_map.h:17,
                 from unitig_graph.h:29,
                 from unitig_graph.cpp:21:
hash_table.h: At global scope:
hash_table.h: In instantiation of ‘HashTableNode<std::pair<long int, unsigned int> >’:
hash_table.h:102:   instantiated from ‘Value* HashTableIterator<Value, Key, HashFunc, ExtractKey, EqualKey>::operator->() const [with Value = std::pair<long int, unsigned int>, Key = long int, HashFunc = Hash<long int>, ExtractKey = Select1st<std::pair<long int, unsigned int> >, EqualKey = std::equal_to<long int>]’
unitig_graph.cpp:430:   instantiated from here
hash_table.h:50: warning: ignoring packed attribute because of unpacked non-POD field ‘std::pair<long int, unsigned int> HashTableNode<std::pair<long int, unsigned int> >::value’
g++ -g -O2 -Wall -Wno-unused-function -Wno-array-bounds -D__STDC_FORMAT_MACROS -funroll-loops -fprefetch-loop-arrays -fopenmp -I. -std=c++0x -static-libgcc -m64 -mpopcnt -DPACKAGE_VERSION="\"v1.1.2\"" -c sequence_manager.cpp -o sequence_manager.o
In file included from sequence_manager.cpp:21:
sequence_manager.h:27:18: error: zlib.h: No such file or directory
In file included from sequence_manager.cpp:21:
sequence_manager.h:36: error: ‘gzFile’ does not name a type
sequence_manager.h:36: error: ‘ks_init’ declared as an ‘inline’ variable
sequence_manager.h:36: error: ‘gzFile’ was not declared in this scope
sequence_manager.h:36: error: expected ‘,’ or ‘;’ before ‘{’ token
sequence_manager.h: In function ‘int ks_getc(kstream_t*)’:
sequence_manager.h:36: error: ‘struct __kstream_t’ has no member named ‘f’
sequence_manager.h:36: error: ‘gzread’ was not declared in this scope
sequence_manager.h: In function ‘int ks_getuntil2(kstream_t*, int, kstring_t*, int*, int)’:
sequence_manager.h:36: error: ‘struct __kstream_t’ has no member named ‘f’
sequence_manager.h:36: error: ‘gzread’ was not declared in this scope
sequence_manager.h: At global scope:
sequence_manager.h:36: error: ‘gzFile’ was not declared in this scope
sequence_manager.h:36: error: expected ‘,’ or ‘;’ before ‘{’ token
sequence_manager.h:63: error: ‘gzFile’ was not declared in this scope
sequence_manager.h:63: error: template argument 1 is invalid
sequence_manager.h:63: error: template argument 2 is invalid
sequence_manager.h: In constructor ‘SequenceManager::SequenceManager(SequencePackage*)’:
sequence_manager.h:75: error: request for member ‘clear’ in ‘((SequenceManager*)this)->SequenceManager::files_’, which is of non-class type ‘int’
sequence_manager.h: In member function ‘void SequenceManager::clear()’:
sequence_manager.h:93: error: request for member ‘begin’ in ‘((SequenceManager*)this)->SequenceManager::files_’, which is of non-class type ‘int’
sequence_manager.h:93: error: unable to deduce ‘auto’ from ‘<expression error>’
sequence_manager.h:93: error: request for member ‘end’ in ‘((SequenceManager*)this)->SequenceManager::files_’, which is of non-class type ‘int’
sequence_manager.h:94: error: ‘gzclose’ was not declared in this scope
sequence_manager.h:97: error: request for member ‘clear’ in ‘((SequenceManager*)this)->SequenceManager::files_’, which is of non-class type ‘int’
sequence_manager.cpp: In member function ‘void SequenceManager::set_file(const std::string&)’:
sequence_manager.cpp:32: error: request for member ‘size’ in ‘((SequenceManager*)this)->SequenceManager::files_’, which is of non-class type ‘int’
sequence_manager.cpp:35: error: request for member ‘resize’ in ‘((SequenceManager*)this)->SequenceManager::files_’, which is of non-class type ‘int’
sequence_manager.cpp:38: error: invalid types ‘int[int]’ for array subscript
sequence_manager.cpp:38: error: ‘gzdopen’ was not declared in this scope
sequence_manager.cpp:38: error: ‘gzopen’ was not declared in this scope
sequence_manager.cpp:39: error: invalid types ‘int[int]’ for array subscript
sequence_manager.cpp:42: error: invalid types ‘int[int]’ for array subscript
sequence_manager.cpp:42: error: ‘kseq_init’ cannot be used as a function
sequence_manager.cpp: In member function ‘void SequenceManager::set_pe_files(const std::string&, const std::string&)’:
sequence_manager.cpp:49: error: request for member ‘size’ in ‘((SequenceManager*)this)->SequenceManager::files_’, which is of non-class type ‘int’
sequence_manager.cpp:52: error: request for member ‘resize’ in ‘((SequenceManager*)this)->SequenceManager::files_’, which is of non-class type ‘int’
sequence_manager.cpp:55: error: invalid types ‘int[int]’ for array subscript
sequence_manager.cpp:55: error: ‘gzdopen’ was not declared in this scope
sequence_manager.cpp:55: error: ‘gzopen’ was not declared in this scope
sequence_manager.cpp:56: error: invalid types ‘int[int]’ for array subscript
sequence_manager.cpp:58: error: invalid types ‘int[int]’ for array subscript
sequence_manager.cpp:62: error: invalid types ‘int[int]’ for array subscript
sequence_manager.cpp:62: error: ‘kseq_init’ cannot be used as a function
sequence_manager.cpp: In member function ‘void SequenceManager::set_edge_files(const std::string&)’:
sequence_manager.cpp:70: error: request for member ‘size’ in ‘((SequenceManager*)this)->SequenceManager::files_’, which is of non-class type ‘int’
sequence_manager.cpp: In member function ‘int64_t SequenceManager::ReadShortReads(int64_t, int64_t, bool, bool, bool, std::string)’:
sequence_manager.cpp:191: error: invalid types ‘int[int]’ for array subscript
sequence_manager.cpp:191: error: ‘gzread’ was not declared in this scope
sequence_manager.cpp:201: error: invalid types ‘int[int]’ for array subscript
sequence_manager.cpp:201: error: ‘gzread’ was not declared in this scope
sequence_manager.h: At global scope:
sequence_manager.h:36: warning: ‘ks_init’ defined but not used
make: *** [sequence_manager.o] Error 1

**Comment by voutcn** [comment]
zlib is missing. You can install it by `yum install zlib-devel`.
