### ISSUE TITLE
Better documentation of paired-end read information usage in algorithm

### ISSUE THREAD

**Issue by nwespe** [voutcn/megahit#154]
Hi,
First of all, thank you for creating an excellent de novo assembly program. I recently benchmarked it against several other programs and chose to use it for my pipeline.
I would like to request better documentation on how Megahit is using information from paired-end reads. I spent some time trying to improve assembly metrics by first merging overlapping reads with FLASH, and since this made no difference in the assembly quality, I assume similar information is being used by Megahit. It would save future users time and effort if this usage were better described on your website.
Thank you!
Nichole

**Comment by voutcn** [comment]
Thank you for the suggestion. I will polish the README file recently.
The algorithm details are described in our publication https://www.sciencedirect.com/science/article/pii/S1046202315301183?via%3Dihub.
