### ISSUE TITLE
Last K value used larger than the read length

### ISSUE THREAD

**Issue by snurk** [voutcn/megahit#155]
Hello!
I stumbled upon a weird log where apparently MEGAHIT iterates to K119 while read length is 100bp.
Is it the intended behavior?
[log.txt](https://github.com/voutcn/megahit/files/1684846/log.txt)

Best,
Sergey

**Comment by voutcn** [comment]
Yes, it is an intended behavior. This makes sense because the local assembly module is able to join"paired-end reads to create "new" k-mers.
