### ISSUE TITLE
Error occurs when running "sdbg_builder count/read2sdbg"

### ISSUE THREAD

**Issue by cox89** [voutcn/megahit#156]
Hi guys I'm trying to use megahit for the first time but I'm struck with this error

Error occurs when running "sdbg_builder count/read2sdbg", please refer to bustina_assembled/log for detail

I really don't know how to solve it. Reading online I haven't find any solution. Anybody can help me? Thank you so much

This is the log file:

MEGAHIT v1.1.2 --- [Wed Feb 7 11:59:28 2018] Start assembly. Number of CPU threads 20 --- --- [Wed Feb 7 11:59:28 2018] Available memory: 135258927104, used: 108207141683 --- [Wed Feb 7 11:59:29 2018] Converting reads to binaries --- /pico/home/userexternal/dmora000/megahit-master/megahit_asm_core buildlib assembl_bustina/tmp/reads.lib assembl_bustina/tmp/reads.lib [read_lib_functions-inl.h : 209] Lib 0 (706010_30535_ATGCGCAGCTAAGCCT_L001_R1_001_AH77FYBCX2.filt.fastq.gz,706010_30535_ATGCGCAGCTAAGCCT_L001_R2_001_AH77FYBCX2.filt.fastq.gz): pe, 97512934 reads, 126 max length [utils.h : 126] Real: 498.1912 user: 98.3321 sys: 7.7718 maxrss: 153492 --- [Wed Feb 7 12:07:47 2018] k list: 21,29,39,59,79,99,119,141 --- --- [Wed Feb 7 12:07:47 2018] Extracting solid (k+1)-mers for k = 21 --- cmd: /pico/home/userexternal/dmora000/megahit-master/megahit_sdbg_build count -k 21 -m 2 --host_mem 108207141683 --mem_flag 5 --gpu_mem 0 --output_prefix assembl_bustina/tmp/k21/21 --num_cpu_threads 20 --num_output_threads 6 --read_lib_file assembl_bustina/tmp/reads.lib [sdbg_builder.cpp : 112] Host memory to be used: 108207141683 [sdbg_builder.cpp : 113] Number CPU threads: 20 [cx1.h : 450] Preparing data... [read_lib_functions-inl.h : 256] Before reading, sizeof seq_package: 3613627640 [read_lib_functions-inl.h : 260] After reading, sizeof seq_package: 3613627640 [cx1_kmer_count.cpp : 136] 97512934 reads, 126 max read length [cx1.h : 457] Preparing data... Done. Time elapsed: 36.4944 [cx1.h : 464] Preparing partitions and initialing global data... [cx1_kmer_count.cpp : 227] 2 words per substring, 2 words per edge [cx1.h : 171] Adjusting memory layout: max_lv1_items=140735296881296, num_sorting_items=8504140, mem_sorting_items=204099360, mem_avail=104256463143 [cx1_kmer_count.cpp : 356] 26013090945, 8504140 104256463140 104256463143 [cx1_kmer_count.cpp : 363] Memory for reads: 3702175296 [cx1_kmer_count.cpp : 364] max # lv.1 items = 26013090945 [cx1.h : 480] Preparing partitions and initialing global data... Done. Time elapsed: 9.9664 [cx1.h : 486] Start main loop... [cx1.h : 515] Lv1 scanning from bucket 0 to 65536 Error occurs when running "sdbg_builder count/read2sdbg", please refer to assembl_bustina/log for detail [Exit code -9] ~

**Comment by voutcn** [comment]
-9 means the program was killed by someone with signal 9. It is likely that someone killed it by mistake. Or if you ran Megahit on a platform that has time/memory limited, it may also be killed when the running time/ memory reach the limitation.
