### ISSUE TITLE
Megahit v1.1.2 abnormal exit in Ubuntu 16.04(docker run in win10 pro)

### ISSUE THREAD

**Issue by yangkl0909** [voutcn/megahit#157]
I'm trying to install and run the sample from this website https://github.com/voutcn/megahit/wiki/An-example-of-real-assembly. A message confirming successful installation by "make test". But when I run the sample dataset (SRR341725) , I got these two lines and some empty files in output dir.

MEGAHIT v1.1.2
--- [Thu Feb 22 09:19:05 2018] Start assembly. Number of CPU threads 7 ---
--- [Thu Feb 22 09:19:05 2018] Available memory: 23365783552, used: 21029205196

**Comment by voutcn** [comment]
Please try using less memory, like `-m 0.5`.

**Comment by ltipton** [comment]
I am having the same problem with v1.1.3 and using less memory via the -m option does not make a difference, other than reducing the number after used. Any other suggestions?
