### ISSUE TITLE
Using both paired and single end reads in the same assembly run

### ISSUE THREAD

**Issue by Stefano04** [voutcn/megahit#158]
Hi everyone, 

I have this doubt - can I use both paired and single end reads in the same run? I launched this command: 

`qsub megahit --preset meta -1 1_trim4p_R1.fastq.gz,2_trim4p_R1.fastq.gz,3_trim4p_R1.fastq.gz,4_trim4p_R1.fastq.gz,5_trim4p_R1.fastq.gz,6_trim4p_R1.fastq.gz -2 1_trim4p_R2.fastq.gz,2_trim4p_R2.fastq.gz,3_trim4p_R2.fastq.gz,4_trim4p_R2.fastq.gz,5_trim4p_R2.fastq.gz,6_trim4p_R2.fastq.gz –r 1_trim4s_R1.fastq.gz,2_trim4s_R1.fastq.gz,3_trim4s_R1.fastq.gz,4_trim4s_R1.fastq.gz,5_trim4s_R1.fastq.gz,6_trim4s_R1.fastq.gz,1_trim4s_R2.fastq.gz,2_trim4s_R2.fastq.gz,3_trim4s_R2.fastq.gz,4_trim4s_R2.fastq.gz,5_trim4s_R2.fastq.gz,6_trim4s_R2.fastq.gz -m 0.25 -t 15 -o outputPS/`

Where in -1 and in -2 are the trimmed (Trimmomatic) paired end reads, whereas in -r all the unpaired/single end reads (as well from Trimmomatic). 

The assembler ran, but then checking the log it seems it didn't include the single reads in the run. Log:

```
MEGAHIT v1.0.3
--- [Mon Feb 26 19:12:05 2018] Start assembly. Number of CPU threads 40 ---
--- [Mon Feb 26 19:12:05 2018] k list: 21,41,61,81,99 ---
--- [Mon Feb 26 19:12:05 2018] Converting reads to binaries ---
/opt/bio/megahit-1.0.3/megahit_asm_core buildlib ./megahit_out/tmp/reads.lib ./megahit_out/tmp/reads.lib
    [read_lib_functions-inl.h  : 209]     Lib 0 (1_trim4p_R1.fastq.gz,1_trim4p_R2.fastq.gz): pe, 5262952 reads, 285 max length
    [read_lib_functions-inl.h  : 209]     Lib 1 (2_trim4p_R1.fastq.gz,2_trim4p_R2.fastq.gz): pe, 4700864 reads, 285 max length
    [read_lib_functions-inl.h  : 209]     Lib 2 (3_trim4p_R1.fastq.gz,3_trim4p_R2.fastq.gz): pe, 5187702 reads, 285 max length
    [read_lib_functions-inl.h  : 209]     Lib 3 (4_trim4p_R1.fastq.gz,4_trim4p_R2.fastq.gz): pe, 4999452 reads, 285 max length
    [read_lib_functions-inl.h  : 209]     Lib 4 (5_trim4p_R1.fastq.gz,5_trim4p_R2.fastq.gz): pe, 6113712 reads, 285 max length
    [read_lib_functions-inl.h  : 209]     Lib 5 (6_trim4p_R1.fastq.gz,6_trim4p_R2.fastq.gz): pe, 4047104 reads, 285 max length
    [utils.h                   : 124]     Real: 64.6702	user: 45.7480	sys: 4.2520	maxrss: 162880
```

Whereas the opts.txt file, which reports the command launched, included (of course) the single reads after -r:

```
--preset
meta
-1
1_trim4p_R1.fastq.gz,2_trim4p_R1.fastq.gz,3_trim4p_R1.fastq.gz,4_trim4p_R1.fastq.gz,5_trim4p_R1.fastq.gz,6_trim4p_R1.fastq.gz
-2
1_trim4p_R2.fastq.gz,2_trim4p_R2.fastq.gz,3_trim4p_R2.fastq.gz,4_trim4p_R2.fastq.gz,5_trim4p_R2.fastq.gz,6_trim4p_R2.fastq.gz
–r
1_trim4s_R1.fastq.gz,2_trim4s_R1.fastq.gz,3_trim4s_R1.fastq.gz,4_trim4s_R1.fastq.gz,5_trim4s_R1.fastq.gz,6_trim4s_R1.fastq.gz,1_trim4s_R2.fastq.gz,2_trim4s_R2.fastq.gz,3_trim4s_R2.fastq.gz,4_trim4s_R2.fastq.gz,5_trim4s_R2.fastq.gz,6_trim4s_R2.fastq.gz
-m
0.25
-t
15
-o
outputPS/
```
Am I doing something wrong? Is there any sort of conflict using both paired and single ends in the same run? 

Thanks everyone.

**Comment by voutcn** [comment]
You command is correct. I found that you are using a relatively old version (v1.0.3) and I cannot reproduce this problem with v1.1.2. Could you try Megahit v1.1.2 with the same command? (removing `--preset meta` because this preset has been obsoleted).

**Comment by Stefano04** [comment]
Hi, 

Thanks for your answer. I run another time with Megahit 1.1.2 removing the -preset meta as per your indications. The result is the same - the command in the opts.txt does include the single reads: 

```
-1
1_trim4p_R1.fastq.gz,2_trim4p_R1.fastq.gz,3_trim4p_R1.fastq.gz,4_trim4p_R1.fastq.gz,5_trim4p_R1.fastq.gz,6_trim4p_R1.fastq.gz
-2
1_trim4p_R2.fastq.gz,2_trim4p_R2.fastq.gz,3_trim4p_R2.fastq.gz,4_trim4p_R2.fastq.gz,5_trim4p_R2.fastq.gz,6_trim4p_R2.fastq.gz
–r
1_trim4s_R1.fastq.gz,2_trim4s_R1.fastq.gz,3_trim4s_R1.fastq.gz,4_trim4s_R1.fastq.gz,5_trim4s_R1.fastq.gz,6_trim4s_R1.fastq.gz,1_trim4s_R2.fastq.gz,2_trim4s_R2.fastq.gz,3_trim4s_R2.fastq.gz,4_trim4s_R2.fastq.gz,5_trim4s_R2.fastq.gz,6_trim4s_R2.fastq.gz
-m
0.50
-t
20
-o
outputPS_2/
MEGAHIT_TEMP_DIR: ./megahit_out/tmp/

```
But then in the log file, single reads are not included: 

```
MEGAHIT v1.1.2
--- [Thu Mar  1 10:19:18 2018] Start assembly. Number of CPU threads 40 ---
--- [Thu Mar  1 10:19:18 2018] Available memory: 540958822400, used: 486862940160
--- [Thu Mar  1 10:19:18 2018] Converting reads to binaries ---
/opt/bio/dset/megahit/megahit_asm_core buildlib ./megahit_out/tmp/reads.lib ./megahit_out/tmp/reads.lib
    [read_lib_functions-inl.h  : 209]     Lib 0 (1_trim4p_R1.fastq.gz,1_trim4p_R2.fastq.gz): pe, 5262952 reads, 285 max length
    [read_lib_functions-inl.h  : 209]     Lib 1 (2_trim4p_R1.fastq.gz,2_trim4p_R2.fastq.gz): pe, 4700864 reads, 285 max length
    [read_lib_functions-inl.h  : 209]     Lib 2 (3_trim4p_R1.fastq.gz,3_trim4p_R2.fastq.gz): pe, 5187702 reads, 285 max length
    [read_lib_functions-inl.h  : 209]     Lib 3 (4_trim4p_R1.fastq.gz,4_trim4p_R2.fastq.gz): pe, 4999452 reads, 285 max length
    [read_lib_functions-inl.h  : 209]     Lib 4 (5_trim4p_R1.fastq.gz,5_trim4p_R2.fastq.gz): pe, 6113712 reads, 285 max length
    [read_lib_functions-inl.h  : 209]     Lib 5 (6_trim4p_R1.fastq.gz,6_trim4p_R2.fastq.gz): pe, 4047104 reads, 285 max length
    [utils.h                   : 126]     Real: 59.8796	user: 41.6680	sys: 3.6160	maxrss: 162044
--- [Thu Mar  1 10:20:18 2018] k list: 21,29,39,59,79,99,119,141 ---
```

No idea why. Maybe I have to use --read instead of -r? Or maybe is there a limit to the number of file you can use as input? 

Thanks for your help again. 

Stefano

**Comment by voutcn** [comment]
I figured it out. The character `–` in `–r` is incorrect. It should be `-`. You can see the tiny difference between the two character. The one you used is not an ASCII code.
```
-
–
```

**Comment by Stefano04** [comment]
Wow, that was subtle. I couldn't figure that out. On to the assemblies!

THANKS A LOT <3
