### ISSUE TITLE
Unable to compile MEGAHIT to use locally 

### ISSUE THREAD

**Issue by nixon444** [voutcn/megahit#159]
I am pretty new to the world of bioinformatics and I could use some help with the following...

I downloaded MEGAHIT to my Mac and am trying to run it. First I need to recompile it and when I type 'make' in my megahit folder I keep getting the following error:

c++ -g -O2 -Wall -Wno-unused-function -Wno-array-bounds -D__STDC_FORMAT_MACROS -funroll-loops -fprefetch-loop-arrays -fopenmp -I. -std=c++0x -static-libgcc -m64 -mpopcnt -DPACKAGE_VERSION="\"v1.1.3\"" -c succinct_dbg.cpp -o succinct_dbg.o
clang: warning: optimization flag '-fprefetch-loop-arrays' is not supported [-Wignored-optimization-argument]
clang: error: unsupported option '-fopenmp'
make: *** [succinct_dbg.o] Error 1

Any ideas? Am I missing dependencies? 

Any help will be gratefully received!!

**Comment by biomendi** [comment]
You could try downloading MEGAHIT through bioconda:

`conda install -c bioconda megahit`

**Comment by nixon444** [comment]
Thank you this worked! Much appreciated :)

**Comment by yo54233154** [comment]
Tried installing megahit with conda, seems they put executables in the environment root path instead of its */bin subdirectory... Wasn't hard to fix though.
