### ISSUE TITLE
setting memory

### ISSUE THREAD

**Issue by bfoster-lbl** [voutcn/megahit#16]
I noticed that megahit has an auto detect feature for specifying gpu ram.  I was wondering if it would be feasible to add the same for the -m option.  For example I added the following to my local copy of megahit:

        elif option in ("-m", "--memory"):
            if value == "auto":
                opt.host_mem = available_mem() * 0.90
            else:
                opt.host_mem = long(float(value))

        def available_mem():
            mem = long()
            if sys.platform.find("linux") != -1:
                mem = long(float(os.popen("free").readlines()[1].split()[1]) * 1024 )
            elif sys.platform.find("darwin") != -1:
                mem = long(float(os.popen("vm_stat").readlines()[1].split()[2]) * 4096 )
            else:
                raise Usage(megahit_version_str + '\nos not determined for "-m auto" memory calculation.' )
            return mem

I am not sure if that is the best way get available memory, but an auto feature helps usability when I am sending megahit jobs to different hardware.

**Comment by voutcn** [comment]
Thanks! That should be useful, and we will test it and consider adding this feature in the next release.
You also are welcomed to create pull requests to MEGAHIT repo (once we've tested and accepted the request, you will appear to be [a contributor](https://github.com/voutcn/megahit/graphs/contributors) :).

**Comment by bfoster-lbl** [comment]
Ok ... I will try the pull request. I was thinking it would be useful to be able to specify and -m value between 0-1.  This would then use the fraction of available memory specified.  Any value  >1 work as usual.  I will create a version with that feature.
