### ISSUE TITLE
Larger kmer size for 250bp reads

### ISSUE THREAD

**Issue by adityabandla** [voutcn/megahit#161]
Hi 

I am trying to assemble a sediment shotgun metagenome dataset. Illumina HiSeq 250bp PE reads. Since these are 250bp reads, is it advisable to try kmer sizes ranging from 27 to 187 in steps of 10? Or is 187 too large for such read lengths.

Regards,
Aditya

**Comment by voutcn** [comment]
Usually larger kmer sizes lead to more misassemblies but longer contigs. I seldom used k >= 150, but some assemblers like A5-Miseq uses kmer size up to 500. So just have a try, I don't have a perfect suggestion here.
