### ISSUE TITLE
%CPU up to 4000

### ISSUE THREAD

**Issue by superhu0** [voutcn/megahit#163]
Hi
When I start megahit, it run COMMAND: megahit_sdbg_bu.             top: %CPU up to 4000
This is cmd in log:
cmd: /home/jinsong/megahit/megahit_sdbg_build count -k 21 -m 2 --host_mem 428408214323 --mem_flag 1 --gpu_mem 0 --output_prefix ../megahit_assembly/megahit7-12/tmp/k21/21 --num_cpu_threads 43 --num_output_threads 14 --read_lib_file ../megahit_assembly/megahit7-12/tmp/reads.lib
My linux version:  Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04)
lscpu:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                48
On-line CPU(s) list:   0-47
Thread(s) per core:    2
Core(s) per socket:    6
Socket(s):             4
NUMA node(s):          8
Vendor ID:             AuthenticAMD
CPU family:            21
Model:                 1
Model name:            AMD Opteron(TM) Processor 6234
Stepping:              2
CPU MHz:               1400.000
CPU max MHz:           2400.0000
CPU min MHz:           1400.0000
BogoMIPS:              4799.98
Virtualization:        AMD-V
L1d cache:             16K
L1i cache:             64K
L2 cache:              2048K
L3 cache:              6144K
NUMA node0 CPU(s):     0-5
NUMA node1 CPU(s):     6-11
NUMA node2 CPU(s):     12-17
NUMA node3 CPU(s):     18-23
NUMA node4 CPU(s):     24-29
NUMA node5 CPU(s):     30-35
NUMA node6 CPU(s):     36-41
NUMA node7 CPU(s):     42-47

How to deal with this problem? THANKS

**Comment by voutcn** [comment]
use `-t` to control the number of threads.

**Comment by superhu0** [comment]
ok, I got it, THANKS
