### ISSUE TITLE
[Exit code -6]std::bad_alloc

### ISSUE THREAD

**Issue by HUANGjz** [voutcn/megahit#164]
I am running megahit on a dataset about 40GB, the memory of my computer is 128G.
The last lines of the log file:

    [cx1_seq2sdbg.cpp          : 440]     Before reading, sizeof seq_package: 15216953608, multiplicity vector: 2766718836
    [cx1_seq2sdbg.cpp          : 455]     Adding mercy edges...
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Error occurs when running "builder build" for k = 21; please refer to megahit_skin/log for detail

Although the option --kmin-1pass seems to work, but it is too slow when adding this option.
Are there any solution to the problem? 

Complete log file also attached.

**Comment by HUANGjz** [comment]
[log.txt](https://github.com/voutcn/megahit/files/1931147/log.txt)

**Comment by voutcn** [comment]
Try to use `--kmin-1pass` option.
