### ISSUE TITLE
Co-assemble PE files

### ISSUE THREAD

**Issue by ValerieLanglois** [voutcn/megahit#169]
Hi, 

I would like to assemble in one big co-assembly multiples PE files from viral metagenomes
I have a total of 18 libraries (36 files total since it's PE) in fastq format (162Gb  total)

That said, I have three questions : 
1- how much memory should I plan for this job? Would 1T be enough? 
2- Is there a way to co-assemble these files without having to concatenate them all together?
3- two files come from Mi-Seq sequencing (about 300bp reads) and the rest come from HiSeq sequencing (125bp), is there any option that would facilitate the assembly of reads with a big length difference

**Comment by voutcn** [comment]
1. Memory usage really depends on the number of unique kmers in your dataset. usually, 1T should be enough. The `--kmin-1pass` option is recommended.
2. Yes, you can specify `-1`, `-2`, `--12` and `-r` for multiple times to use multiple files without concatenating them.
3. There is no problem co-assembling 125bp and 300bp reads. You can just feed them to Megahit.
