### ISSUE TITLE
Different results with same configuration

### ISSUE THREAD

**Issue by claczny** [voutcn/megahit#170]
Hi,

thanks a lot for developing MEGAHIT!!!

I was wondering whether one should expect MEGAHIT to be deterministic, i.e., reveal the **same** results on the **same** input, **same** platform, and **same** number of threads?

Based on some preliminary tests we have performed, this seems **not** to be the case, i.e., we get *different* results.

TIA for clarifying this.

Best,

Cedric

**Comment by voutcn** [comment]
It is non-deterministic because of multithreading. But you will get almost identical results, except for contigs originated from loops in the DBG (really rare cases).

**Comment by claczny** [comment]
Thanks a lot for the clarification!
Does that mean that it would be deterministic if one would use a single thread in the options, assuming that there would be *no* loops?

Along this, would there be a possibility to ensure determinism, e.g., by specifying a `seed` option on the command line?

**Comment by claczny** [comment]
Thanks!
