### ISSUE TITLE
'make test' returns error 245

### ISSUE THREAD

**Issue by c94rivera** [voutcn/megahit#171]
Hi,
I am trying to use megahit and when I run `make test` it returns error 245. Below is the log file that is tells me to check

`MEGAHIT v1.1.3
--- [Wed Jun  6 17:16:16 2018] Start assembly. Number of CPU threads 2 ---
--- [Wed Jun  6 17:16:16 2018] Available memory: 33661382656, used: 30295244390
--- [Wed Jun  6 17:16:16 2018] Converting reads to binaries ---
/home/phyllobates/Assemblers/megahit-master/megahit_asm_core buildlib example/megahit_out/tmp/reads.lib example/megahit_out/tmp/reads.lib
    [read_lib_functions-inl.h  : 209]     Lib 0 (example/readsInterleaved1.fa.gz): interleaved, 200 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 1 (example/readsInterleaved2.fa.bz2): interleaved, 200 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 2 (example/readsInterleaved3.fa): interleaved, 200 reads, 100 max length
    [utils.h                   : 126]     Real: 0.0023	user: 0.0013	sys: 0.0000	maxrss: 7720
--- [Wed Jun  6 17:16:16 2018] k-max reset to: 119 ---
--- [Wed Jun  6 17:16:16 2018] k list: 21,29,39,59,79,99,119 ---
--- [Wed Jun  6 17:16:16 2018] Extracting solid (k+1)-mers and building sdbg for k = 21 ---
cmd: /home/phyllobates/Assemblers/megahit-master/megahit_sdbg_build read2sdbg -k 21 -m 2 --host_mem 30295244390 --mem_flag 1 --gpu_mem 0 --output_prefix example/megahit_out/tmp/k21/21 --num_cpu_threads 2 --num_output_threads 1 --read_lib_file example/megahit_out/tmp/reads.lib --need_mercy
    [cx1.h                     : 450]     Preparing data...
    [read_lib_functions-inl.h  : 256]     Before reading, sizeof seq_package: 19812
    [read_lib_functions-inl.h  : 260]     After reading, sizeof seq_package: 19812
    [cx1_read2sdbg_s1.cpp      : 140]     600 reads, 100 max read length, 60000 total bases
    [cx1.h                     : 457]     Preparing data... Done. Time elapsed: 0.0001
    [cx1.h                     : 464]     Preparing partitions and initialing global data...
    [cx1_read2sdbg_s1.cpp      : 250]     2 words per substring
    [cx1_read2sdbg_s1.cpp      : 382]     Memory for reads: 27808
    [cx1_read2sdbg_s1.cpp      : 383]     max # lv.1 items = 6640
    [cx1_read2sdbg_s1.cpp      : 397]     Number of files for mercy candidate reads: 1
    [cx1.h                     : 480]     Preparing partitions and initialing global data... Done. Time elapsed: 0.0095
    [cx1.h                     : 486]     Start main loop...
    [cx1.h                     : 515]     Lv1 scanning from bucket 0 to 84
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 0.0003
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 0.0005
    [cx1.h                     : 515]     Lv1 scanning from bucket 84 to 196
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 0.0003
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 0.0004
    [cx1.h                     : 515]     Lv1 scanning from bucket 196 to 336
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 0.0003
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 0.0004
    [cx1.h                     : 515]     Lv1 scanning from bucket 336 to 516
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 0.0003
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 0.0004
    [cx1.h                     : 515]     Lv1 scanning from bucket 516 to 733
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 0.0003
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 0.0004
    [cx1.h                     : 515]     Lv1 scanning from bucket 733 to 1009
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 0.0003
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 0.0004
    [cx1.h                     : 515]     Lv1 scanning from bucket 1009 to 4575
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 0.0003
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 0.0006
    [cx1.h                     : 515]     Lv1 scanning from bucket 4575 to 65536
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 0.0007
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 0.0019
    [cx1.h                     : 607]     Main loop done. Time elapsed: 0.0077
    [cx1.h                     : 613]     Postprocessing...
    [cx1_read2sdbg_s1.cpp      : 921]     Total number of solid edges: 3041
    [cx1.h                     : 621]     Postprocess done. Time elapsed: 0.0059
    [cx1.h                     : 450]     Preparing data...
    [cx1_read2sdbg_s2.cpp      : 115]     Adding mercy edges...
Error occurs when running "sdbg_builder count/read2sdbg", please refer to example/megahit_out/log for detail
[Exit code -11] ` 

> 

and in terminal the following message is after the log file 
`Makefile:287: recipe for target 'test' failed
make: *** [test] Error 245`

**Comment by AntoineHo** [comment]
Hello, I have the same issue. Have you found a solution ?
Thanks
