### ISSUE TITLE
multiple questions

### ISSUE THREAD

**Issue by ValerieLanglois** [voutcn/megahit#172]
Hi, 
I have two questions : 
1- Does megahit take advantage of the base quality in fastq file? (and if not does it still slow down / take more memory to comlpete the assembly) 
2- Can megahit use multiple GPUs and if so does it help reducing the human time of the run?

thanks

**Comment by ValerieLanglois** [comment]
Another question, 
I've been doing some tests, and I notice the CPU usage vary a lot between runs, is it something to be expected?

**Comment by voutcn** [comment]
1. No, it does not take advantage of the base quality.
2. No, it doesn't. In fact, the CPU version is way faster than the GPU version. We had stopped optimizing the GPU counter-part for a long time.
3. It is not expected. The running time should be stable. But if your memory size is big enough, it is possible that the input fastq will be cached by the OS and the total running time may decrease.
