### ISSUE TITLE
Running megahit inside Docker and output to volume

### ISSUE THREAD

**Issue by deepBiomeDiego** [voutcn/megahit#174]
Hello,
I'm attempting to assemble metagenomes inside of a Docker container, it works if I assemble all the data inside of it, but if i attempt to use a temporary directory that's mounted as a volume megahit exists out with no error (immediately after starting).

Because there are no errors i'm at a bit of a loss, and this probably is some weird Docker specific issue. Any suggestions on what i could try to figure this out?

--Thanks

**Comment by voutcn** [comment]
The case is similar to https://github.com/voutcn/megahit/issues/176 and https://github.com/voutcn/megahit/issues/117. What kind of file system you mounted into the docker container?
