### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by UriaMorP** [voutcn/megahit#175]
Hey there, 
Is there a way to specify the absolute amount of GB I want megahit to use?

**Comment by voutcn** [comment]
use `-m`. e.g. `-m 10e9` to use 10Gb memory.
But please note that such setting only constrain the memory used in the graph building stage. Other stage (assembly, local assembly etc.) are not bounded.

**Comment by SilentGene** [comment]
Hi voutcn, I was just wondering why we can't constrain the memory usage in assembly stage? In some cases, like using megahit in an HPC, we can't use all the memory in a node (limited by slurm system). However, I found megahit would try to use all the memory in a node, which should lead to 'segmentation fault' (code -11) since there is some memory we can't use.

**Comment by Lzinke** [comment]
Hi voutcn, I am having the same problem as SilentGene on a slurm system. I've tried playing with the memory settings (setting --mem-flag to zero or lowering -m), but none of them have prevented megahit from trying to take over the whole node. Do you have any suggestions?

**Comment by rjsorr** [comment]
Hi can you simply provide a command that will give the lowest memory usage? I just want a simple/basic "no thrills" assembly (it will be used as input for another program)! it is not clear the impact of all the parameters on memory consumption, nor do I have time to test. So how would you modify the following parameters for low memory consumption, lets say for a an average 150PE dataset: 

megahit -1 MERGED_R1_val_1.fq.gz -2 MERGED_R2_val_2.fq.gz --k-list 59,79,99,119,141 --no-mercy --bubble-level 0 --prune-level 3 --prune-depth 5 --cleaning-rounds 3 --no-local --kmin-1pass --no-hw-accel --continue -t 1 -m 120e9 --mem-flag 0 -o Megahit_OUT --min-contig-len 500

regards

**Comment by rjsorr** [comment]
> Hi can you simply provide a command that will give the lowest memory usage? I just want a simple/basic "no thrills" assembly (it will be used as input for another program)! it is not clear the impact of all the parameters on memory consumption, nor do I have time to test. So how would you modify the following parameters for low memory consumption, lets say for a an average 150PE dataset:
> 
> megahit -1 MERGED_R1_val_1.fq.gz -2 MERGED_R2_val_2.fq.gz --k-list 59,79,99,119,141 --no-mercy --bubble-level 0 --prune-level 3 --prune-depth 5 --cleaning-rounds 3 --no-local --kmin-1pass --no-hw-accel --continue -t 1 -m 120e9 --mem-flag 0 -o Megahit_OUT --min-contig-len 500
> 
> regards

and please ignore the fact I have -m set to 120gb, that is just for testing. All I want to know is what parameters would give the lowest memory consumption for an assembly?
