### ISSUE TITLE
Megahit incomplete assembly

### ISSUE THREAD

**Issue by cssulliv** [voutcn/megahit#176]
Hi,

I've been trying to run megahit (v1.1.2) on mac using default assembly settings to assemble my paired end reads. I've been running my commands in/through my  external hard drive, which I have reformatted to exFAT from NTFS. But similar to the issue presented before (issue #117) I too get the following output message 

<img width="562" alt="screen shot 2018-07-17 at 9 39 56 am" src="https://user-images.githubusercontent.com/41393799/42904794-cdb9f826-8a71-11e8-8a09-284ead5969fc.png">
as well as an empty 'intermediate_contigs' folder. 

My question is would using an HFS+ external hard drive (without reformatting) allow megahit to completely execute the assembly?

**Comment by cssulliv** [comment]
Hi,

I figured this one out. Megahit doesn't like hard drives with NTFS files systems but works fine with HFS+ ones. I got it to work on a new hard drive!

**Comment by voutcn** [comment]
Good finding! Thank you @cssulliv
