### ISSUE TITLE
builder build error - is it memory?

### ISSUE THREAD

**Issue by uribe-convers** [voutcn/megahit#177]
Dear Dr. Li,

I'm trying to assemble 163 metagenomic dust samples (8 lanes of HiSeq data) using Megahit on an AWS machine with 64 cores, 256Gb RAM, and 1.5 Tb of storage, running Ubuntu Server 16.04 (64-bit).  

Running with the default parameters, Megahit starts well and  finishes the `Converting reads to binaries ` and `Extracting solid (k+1)-mers for k = 21` steps but crashes during the `Building graph for k = 21` step with the following error:

```
--- [Thu Jul 19 10:18:51 2018] Building graph for k = 21 ---
/home/ubuntu/bin/megahit/megahit_sdbg_build seq2sdbg --host_mem 243432194457 --mem_flag 1 --gpu_mem 0 --output_prefix output_megahit_all/tmp/k21/21 --num_cpu_threads 64 -k 21 --kmer_from 0 --num_edge_files 21 --input_prefix output_megahit_all/tmp/k21/21 --need_mercy
    [sdbg_builder.cpp          : 339]     Host memory to be used: 243432194457
    [sdbg_builder.cpp          : 340]     Number CPU threads: 64
    [cx1.h                     : 450]     Preparing data...
    [cx1_seq2sdbg.cpp          : 394]     Number edges: 39073485552
    [cx1_seq2sdbg.cpp          : 434]     Bases to reserve: 1074520852680, number contigs: 0, number multiplicity: 48841856940
    [cx1_seq2sdbg.cpp          : 440]     Before reading, sizeof seq_package: 268630213180, multiplicity vector: 48841856940
Error occurs when running "builder build" for k = 21; please refer to output_megahit_all/log for detail
[Exit code -9]
```
I found older issues on GitHub with similar errors and, following your recommendations, I'm now also using the `--kmin-1pass`, `-m 0.98`, and  `--continue` options. However, the program keeps crashing. 

Do you have any recommendations to overcome this problem? 

I'm attaching the `log` and `opts.txt` files here too, although the `opts.txt` has not updated since the first time I ran the program and does not reflect the additional options.

Thank you,
Simon

[opts.txt](https://github.com/voutcn/megahit/files/2210967/opts.txt)

[log.txt](https://github.com/voutcn/megahit/files/2210969/log.txt)

**Comment by uribe-convers** [comment]
My "meta-assembly" of 8 assemblies finished and I got many contigs. However, I have a few quick question for you @voutcn:

1) I noticed that my meta-assembly contigs have a shorter `max length` and `N50`—something you explained really well [here](https://github.com/voutcn/megahit/issues/147). My question is, is the approach of creating contigs from _contigs_ fundamentally wrong?

2) I set `--min_count 1` thinking this would set `--min_depth` to 1 but looking at the log file I noticed it didn't (it still says `--min_depth 2`). I wanted to set the minimum depth to 1 because some contigs might only be found in one assembly and I would like to keep all of them. The idea is that those contigs have already been assembled by reads providing appropriate sequencing depth. Is there a way to do this? I tried setting `--min_depth 2 ` but the program crashed saying that option didn't exist. 

3) Would an approach involving merging all contigs and keeping the ones that are not too similar (not redundant) with `cd-hit-est` be a better way to do what I want to do?

Thank you so much for your help!

Simon

**Comment by voutcn** [comment]
First, there is a typo, `--min_count 1` should be `--min-count 1`.

I think creating contigs from contigs is a wrong idea. Use cd-hit may help to merge duplicated contigs, but I don't think it will increase the lengths of the resulting contigs.

I believe that co-assembly will result in better assemblies because organisms may be sequenced in low depths in individual lanes, and a combination of all the sequencing data can boost the sequencing depths.

You can try to use normalization methods (BBNorm, khmer) to reduce the volume of your data if you think co-assembly is computationally too heavy.

**Comment by uribe-convers** [comment]
Thank you for your response, I'll see if I can give the normalization methods a chance. 

I agree with your comment on `cd-hit`, I'm only using it to merge multiple contig in a non-redundant way and _not_ to create new contigs.

Is there an option to adjust the minimum depth (see my second question above)?

Thanks.

**Comment by voutcn** [comment]
Yes, `--min-count` (not `--min_count`).
