### ISSUE TITLE
Add install target with DESTDIR support, patch for FreeBSD bswap

### ISSUE THREAD

**Issue by outpaddling** [voutcn/megahit#178]
Just created a FreeBSD port for megahit, which I'll commit following some testing.

[patch-Makefile.txt](https://github.com/voutcn/megahit/files/2235953/patch-Makefile.txt)
[patch-city.cpp.txt](https://github.com/voutcn/megahit/files/2235954/patch-city.cpp.txt)

I plan to add a pkgsrc package shortly (which we use mainly on CentOS).

The Makefile patch will help other package managers as well (Homebrew, Debian, MacPorts, etc).

If you prefer a pull request, I can do that, but I think this is simpler for trivial patches.

**Comment by voutcn** [comment]
@outpaddling thanks. A pull request is most welcomed!
