### ISSUE TITLE
"tmp" folder is not deleted at completion

### ISSUE THREAD

**Issue by tseemann** [voutcn/megahit#18]
Even though I don't use ```--keep-tmp-files``` it still leaves a ```tmp/``` folder behind.

Is this expected?

**Comment by voutcn** [comment]
Yes, that's expected.

**Comment by tseemann** [comment]
Confusing however.

**Comment by voutcn** [comment]
Long ago I keep all intermediate contigs in the temporary directory they may be useful in some cases. But in version 0.2.1 only *.final.contigs.fa are kept, the temporary directory is really useless after they are merged to final.contigs.fa.

A new version will be release later this week. It will delete the `tmp/` folder when assembly is done. All intermediate contigs will be move to another folder.

**Comment by tseemann** [comment]
Ok, i noticed the new `intermediate_contigs` folder. I've modified my pipeline again :)
