### ISSUE TITLE
How to assemble with multiple samples (i.e. multiple fastq files) in one command

### ISSUE THREAD

**Issue by cssulliv** [voutcn/megahit#180]
Hi,

I currently have 2 samples each with an R1 and R2 fastq files. And so is it possible to get one contigs.fa file from multiple samples? If so how do I essentially do that in one megahit command/run: megahit [options] {-1 <pe_1.fq> -2 <pe_2.fq> | --12 <pe12.fq> | -r <se.fq>}? 

Any feedback would help as I would like to avoid running megahit 5+ times for my metagenomic samples.

**Comment by gelomerase** [comment]
Hi there. To run a co-assembly using multiple samples, you group together the R1 and R2 reads as shown for three libraries (six read files):
megahit [options] {-1 pe1_R1.fq,pe2_R1.fq,pe3_R1.fq -2 pe1_R2.fq,pe2_R2.fq,pe3_R2.fq} -o outdir

It should give you a coassembled fasta contig file.

Cheers

**Comment by cssulliv** [comment]
Thank you!
