### ISSUE TITLE
running megahit remotely

### ISSUE THREAD

**Issue by jblakele** [voutcn/megahit#183]
Hi, 

Thanks for the really efficient code. I'm co-assembling a fairly large mouse metagenome using megahit, 18 samples, 909 total gigabytes of fq.gz files so I am trying to run them on a remote server with sufficient memory > 2tb. My question is how can I run megahit so that it does not get interrupted when the pipe to a remote server is broken? I attempted to use nohup.

example:
nohup megahit -1 file_1.fq.gz -2 file_2.fq.gz -o OutDirectory &

However, it seems like the megahit process triggers different independent processes that are still subject to the hangup signal as my runs tend to get terminated whenever my pipe is broken. Has anyone had a similar experience? Is there a work around? I would rather not use "screen" as its not installed on the remote server, and I do not have sudo apt-get privileges. 

On a separate note I have access to around 500 cores on this node. Is there an upper limit to the number of threads megahit can use efficiently? 

Cheers,
Alfredo

**Comment by voutcn** [comment]
It is strange. I often run megahit on remote server with nohup and never seen "broken pipe" problem. Anyway, you can try using [screen[(https://www.howtoforge.com/linux_screen).

I don't have a comprehensive test on the threading scalability of Megahit. My experience showed that you can still get acceleration (though non-linear) with more than 40 cores.
