### ISSUE TITLE
Assertion Failed in unitig_graph.cpp [Exit code -6]

### ISSUE THREAD

**Issue by Andy-Thmpsn** [voutcn/megahit#188]
Hello, 

I keep getting this error and I'm not sure why. I tried compiling without mpopcnt but that didn't work. I also tried running it with --kmin-1pass but that also failed. I've run it on 4, 12 and 24 threads and with 128GB of memory. Any tips on this would be super helpful.

MEGAHIT v1.1.4-2-gd1998a1
--- [Tue Nov 13 10:20:19 2018] Start assembly. Number of CPU threads 12 ---
--- [Tue Nov 13 10:20:19 2018] Available memory: 135357046784, used: 121821342105
--- [Tue Nov 13 10:20:19 2018] Converting reads to binaries ---
/zhome/orange77/programs/megahit/megahit_asm_core buildlib Mega_GRL12_Test5Asb/tmp/reads.lib Mega_GRL12_Test5Asb/tmp/reads.lib
    [read_lib_functions-inl.h  : 209]     Lib 0 (GR_R1_L12_raw.fastq.gz,GR_R2_L12_raw.fastq.gz): pe, 15001344 reads, 250 max length
    [utils.h                   : 126]     Real: 34.0176	user: 21.5997	sys: 1.9457	maxrss: 157500
--- [Tue Nov 13 10:20:56 2018] k list: 27,37,47,57,67,77,87,97,107,117,127,137,141 ---
--- [Tue Nov 13 10:20:56 2018] Extracting solid (k+1)-mers for k = 27 ---
cmd: /zhome/orange77/programs/megahit/megahit_sdbg_build count -k 27 -m 2 --host_mem 121821342105 --mem_flag 1 --gpu_mem 0 --output_prefix Mega_GRL12_Test5Asb/tmp/k27/27 --num_cpu_threads 12 --num_output_threads 4 --read_lib_file Mega_GRL12_Test5Asb/tmp/reads.lib
    [sdbg_builder.cpp          : 112]     Host memory to be used: 121821342105
    [sdbg_builder.cpp          : 113]     Number CPU threads: 12
    [cx1.h                     : 450]     Preparing data...
    [read_lib_functions-inl.h  : 256]     Before reading, sizeof seq_package: 1039455768
    [read_lib_functions-inl.h  : 260]     After reading, sizeof seq_package: 1039455768
    [cx1_kmer_count.cpp        : 136]     15001344 reads, 250 max read length
    [cx1.h                     : 457]     Preparing data... Done. Time elapsed: 4.8015
    [cx1.h                     : 464]     Preparing partitions and initialing global data...
    [cx1_kmer_count.cpp        : 227]     2 words per substring, 3 words per edge
    [cx1_kmer_count.cpp        : 322]     Set: 1788786168, 120690645105
    [cx1_kmer_count.cpp        : 356]     436408854, 1797948 1788786168 120690645105
    [cx1_kmer_count.cpp        : 363]     Memory for reads: 1068188456
    [cx1_kmer_count.cpp        : 364]     max # lv.1 items = 436408854
    [cx1.h                     : 480]     Preparing partitions and initialing global data... Done. Time elapsed: 6.7964
    [cx1.h                     : 486]     Start main loop...
    [cx1.h                     : 515]     Lv1 scanning from bucket 0 to 554
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 6.6172
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 9.7918
    [cx1.h                     : 515]     Lv1 scanning from bucket 554 to 1751
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 6.9427
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 10.2333
    [cx1.h                     : 515]     Lv1 scanning from bucket 1751 to 3641
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 7.2792
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 10.6811
    [cx1.h                     : 515]     Lv1 scanning from bucket 3641 to 6426
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 7.5416
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 11.0752
    [cx1.h                     : 515]     Lv1 scanning from bucket 6426 to 10575
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 8.5154
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 11.6751
    [cx1.h                     : 515]     Lv1 scanning from bucket 10575 to 17220
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 8.0672
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 12.4263
    [cx1.h                     : 515]     Lv1 scanning from bucket 17220 to 30083
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 8.2766
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 13.2065
    [cx1.h                     : 515]     Lv1 scanning from bucket 30083 to 65536
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 8.6427
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 9.5227
    [cx1.h                     : 607]     Main loop done. Time elapsed: 150.4954
    [cx1.h                     : 613]     Postprocessing...
    [cx1_kmer_count.cpp        : 860]     Total number of candidate reads: 2936357(6695147)
    [cx1_kmer_count.cpp        : 871]     Total number of solid edges: 665323014
    [cx1.h                     : 621]     Postprocess done. Time elapsed: 3.8004
    [utils.h                   : 126]     Real: 165.9575	user: 1857.9346	sys: 8.7577	maxrss: 2939096
--- [Tue Nov 13 10:23:42 2018] Building graph for k = 27 ---
/zhome/orange77/programs/megahit/megahit_sdbg_build seq2sdbg --host_mem 121821342105 --mem_flag 1 --gpu_mem 0 --output_prefix Mega_GRL12_Test5Asb/tmp/k27/27 --num_cpu_threads 12 -k 27 --kmer_from 0 --num_edge_files 4 --input_prefix Mega_GRL12_Test5Asb/tmp/k27/27 --need_mercy
    [sdbg_builder.cpp          : 339]     Host memory to be used: 121821342105
    [sdbg_builder.cpp          : 340]     Number CPU threads: 12
    [cx1.h                     : 450]     Preparing data...
    [cx1_seq2sdbg.cpp          : 394]     Number edges: 665323014
    [cx1_seq2sdbg.cpp          : 434]     Bases to reserve: 23286305476, number contigs: 0, number multiplicity: 831653767
    [cx1_seq2sdbg.cpp          : 440]     Before reading, sizeof seq_package: 5821576380, multiplicity vector: 831653767
    [cx1_seq2sdbg.cpp          : 455]     Adding mercy edges...
    [cx1_seq2sdbg.cpp          : 373]     Number of reads: 2936357, Number of mercy edges: 116041743
    [cx1_seq2sdbg.cpp          : 462]     Done. Time elapsed: 126.3848
    [cx1_seq2sdbg.cpp          : 529]     After reading, sizeof seq_package: 5821576380, multiplicity vector: 831653767
    [cx1.h                     : 457]     Preparing data... Done. Time elapsed: 140.5208
    [cx1.h                     : 464]     Preparing partitions and initialing global data...
    [cx1_seq2sdbg.cpp          : 740]     Memory for sequence: 7555229462
    [cx1_seq2sdbg.cpp          : 741]     max # lv.1 items = 625091805
    [cx1.h                     : 480]     Preparing partitions and initialing global data... Done. Time elapsed: 3.9824
    [cx1.h                     : 486]     Start main loop...
    [cx1.h                     : 515]     Lv1 scanning from bucket 0 to 808
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 3.8205
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 14.9473
    [cx1.h                     : 515]     Lv1 scanning from bucket 808 to 2475
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 4.0191
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 14.4019
    [cx1.h                     : 515]     Lv1 scanning from bucket 2475 to 5078
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 4.2159
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 13.5837
    [cx1.h                     : 515]     Lv1 scanning from bucket 5078 to 8924
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 4.3039
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 13.7262
    [cx1.h                     : 515]     Lv1 scanning from bucket 8924 to 14597
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 4.4533
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 13.7176
    [cx1.h                     : 515]     Lv1 scanning from bucket 14597 to 23613
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 4.5642
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 13.5475
    [cx1.h                     : 515]     Lv1 scanning from bucket 23613 to 40211
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 5.1184
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 13.5048
    [cx1.h                     : 515]     Lv1 scanning from bucket 40211 to 65536
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 4.5818
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 8.0031
    [cx1.h                     : 607]     Main loop done. Time elapsed: 140.5096
    [cx1.h                     : 613]     Postprocessing...
    [cx1_seq2sdbg.cpp          :1139]     Number of $ A C G T A- C- G- T-:
    [cx1_seq2sdbg.cpp          :1142]     6053808 269768722 510052544 509876537 270563489 1079633 3218916 3180489 1040619
    [cx1_seq2sdbg.cpp          :1151]     Total number of edges: 1574834757
    [cx1_seq2sdbg.cpp          :1152]     Total number of ONEs: 1560261292
    [cx1_seq2sdbg.cpp          :1153]     Total number of $v edges: 6053808
    [cx1.h                     : 621]     Postprocess done. Time elapsed: 1.0628
    [utils.h                   : 126]     Real: 286.5594	user: 2948.8197	sys: 25.4701	maxrss: 14703688
--- [Tue Nov 13 10:28:29 2018] Assembling contigs from SdBG for k = 27 ---
cmd: /zhome/orange77/programs/megahit/megahit_asm_core assemble -s Mega_GRL12_Test5Asb/tmp/k27/27 -o Mega_GRL12_Test5Asb/intermediate_contigs/k27 -t 12 --min_standalone 300.0 --prune_level 2 --merge_len 20 --merge_similar 0.95 --low_local_ratio 0.2 --min_depth 2 --bubble_level 2 --max_tip_len -1 --careful_bubble
    [assembler.cpp             : 148]     Loading succinct de Bruijn graph: Mega_GRL12_Test5Asb/tmp/k27/27 Done. Time elapsed: 14.284344
    [assembler.cpp             : 152]     Number of Edges: 1574834757; K value: 27
    [assembler.cpp             : 162]     Number of CPU threads: 12
    [assembly_algorithms.cpp   : 162]     Removing tips with length less than 2; Accumulated tips removed: 155206; time elapsed: 10.4413
    [assembly_algorithms.cpp   : 162]     Removing tips with length less than 4; Accumulated tips removed: 497420; time elapsed: 11.6740
    [assembly_algorithms.cpp   : 162]     Removing tips with length less than 8; Accumulated tips removed: 982534; time elapsed: 14.7894
    [assembly_algorithms.cpp   : 162]     Removing tips with length less than 16; Accumulated tips removed: 1744001; time elapsed: 21.6991
    [assembly_algorithms.cpp   : 162]     Removing tips with length less than 32; Accumulated tips removed: 2828862; time elapsed: 32.9163
    [assembly_algorithms.cpp   : 170]     Removing tips with length less than 54; Accumulated tips removed: 3521165; time elapsed: 44.3143
    [assembler.cpp             : 179]     Tips removal done! Time elapsed(sec): 135.948202
    [assembler.cpp             : 188]     unitig graph size: 12219152, time for building: 223.765483
    [assembler.cpp             : 211]     Number of bubbles removed: 1717678, Time elapsed(sec): 39.321649
    [assembler.cpp             : 225]     Number of complex bubbles removed: 318498, Time elapsed(sec): 16.699480
megahit_asm_core: unitig_graph.cpp:1276: void UnitigGraph::Refresh_(bool): Assertion `!vertices_[i].is_marked' failed.
Error occurs when assembling contigs for k = 27, please refer to Mega_GRL12_Test5Asb/log for detail
[Exit code -6]

**Comment by voutcn** [comment]
@Askarbek-orakov could you rerun Megahit with `--continue` to see whether it still fails at the same place?

**Comment by voutcn** [comment]
I think v1.2.4 should have fixed the problem. Please try.
