### ISSUE TITLE
Error occurs when running "sdbg_builder count/read2sdbg"

### ISSUE THREAD

**Issue by ling-he** [voutcn/megahit#189]
I got an error when I tried to use MEGAHIT v1.1.2.

Here is the log details. Do you have any idea to fix that? Thank you very much for your help in advance!

MEGAHIT v1.1.2
--- [Fri Nov 30 09:42:56 2018] Start assembly. Number of CPU threads 112 ---
--- [Fri Nov 30 09:42:56 2018] Available memory: 2168755318784, used: 1951879786905
--- [Fri Nov 30 09:42:56 2018] Converting reads to binaries ---

megahit_asm_core buildlib /tmp/reads.lib /tmp/reads.lib
    [read_lib_functions-inl.h  : 209]     Lib 0 (unmap.1.fq,unmap.2.fq): pe, 1510019498 reads, 151 max length
    [read_lib_functions-inl.h  : 209]     Lib 1 (unmap.s.fq): se, 43809848 reads, 151 max length
    [utils.h                   : 126]     Real: 18812.3964      user: 1716.0251 sys: 9596.9670  maxrss: 163812
--- [Fri Nov 30 14:56:29 2018] k list: 47,57,67,77,87,97 ---
--- [Fri Nov 30 14:56:29 2018] Extracting solid (k+1)-mers for k = 47 ---
cmd: megahit_sdbg_build count -k 47 -m 2 --host_mem 1951879786905 --mem_flag 1 --gpu_mem 0 --output_prefix /tmp/k47/47 --num_cpu_threads 112 --num_output_threads 37 --read_lib_file /tmp/reads.lib
    [sdbg_builder.cpp          : 112]     Host memory to be used: 1951879786905
    [sdbg_builder.cpp          : 113]     Number CPU threads: 112
    [cx1.h                     : 450]     Preparing data...
    [read_lib_functions-inl.h  : 256]     Before reading, sizeof seq_package: 69771890940
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Error occurs when running "sdbg_builder count/read2sdbg", please refer to /unmap/log for detail
[Exit code -6]

**Comment by voutcn** [comment]
You may lower the memory usage. For example, use `-m 0.8`.
