### ISSUE TITLE
Support --prefix option for output filenames?

### ISSUE THREAD

**Issue by tseemann** [voutcn/megahit#19]
This is a feature request for a ```--prefix``` option to control the naming of all the output files in the output folder.

For example, if ```--prefix Ecoli``` then we get files ```Ecoli.log``` and ```Ecoli.contigs.fa``` and so on.

(Not sure about opts.txt for your checkpointing)

**Comment by voutcn** [comment]
At this stage please use  `-o/--out-dir` option to specify different output directories for different assemblies. We will add your requested feature in the next release.

**Comment by tseemann** [comment]
Thanks, I look forward to it!

**Comment by voutcn** [comment]
@tseemann please check out the head in the master branch. An option `--out-prefix` is supported for the naming of the contig file & log file only. Putting multiple assemblies to one output folder is not allowed, because I found that's error prone to mix two assemblies when using `--continue`.
