### ISSUE TITLE
"free" is not installed on all linux distros

### ISSUE THREAD

**Issue by mw55309** [voutcn/megahit#191]
Hey

When using "-m 0.9" or any other fraction, megahit I think tries to use "free" to find out the available memory

However free is not available on all linux distros - particularly it is not installed by default on the google cloud image

Suggest you check for existence of free; if it doesn't exist, try an alternative, or default to sensible (?) value

Cheers
Mick

**Comment by Finesim97** [comment]
Hey,
A fix would be to replace the implementation in the megahit wrapper script of `detect_available_mem()`:
``` python
def detect_available_mem():
    if sys.platform.find("linux") != -1:
        try:
            mem = long(float(os.popen("free").readlines()[1].split()[1]) * 1024)
        except IndexError:
            mem = 0
    elif sys.platform.find("darwin") != -1:
        try:
            mem = long(float(os.popen("sysctl hw.memsize").readlines()[0].split()[1]))
        except IndexError:
            mem = 0
    else:
        mem = 0
    return mem
```
with
``` python
def detect_available_mem():
    if sys.platform.find("linux") != -1:
        psize = os.sysconf('SC_PAGE_SIZE')
        pcount = long(os.sysconf('SC_PHYS_PAGES'))
        if(psize<0 or pcount<0) # If the flags are unavailable 
            mem = 0
        else
            mem = pcount*psize
    elif sys.platform.find("darwin") != -1:
        try:
            mem = long(float(os.popen("sysctl hw.memsize").readlines()[0].split()[1]))
        except IndexError:
            mem = 0
    else:
        mem = 0
    return mem
```
For current macOS Versions the Darwin block wouldn't be necessary, but the SC_PHYS_PAGES flag is missing in some versions. It should also work for OpenBSD and Solaris.

**Comment by voutcn** [comment]
@Finesim97 thank you! I will borrow you code in the next release.
