### ISSUE TITLE
setting up megahit using make

### ISSUE THREAD

**Issue by mstambou** [voutcn/megahit#193]
when I cloned the megahit repository to my home directory and unpacked it and issued a make command I get the following error:

g++ -g -O2 -Wall -Wno-unused-function -Wno-array-bounds -D__STDC_FORMAT_MACROS -funroll-loops -fprefetch-loop-arrays -fopenmp -I. -std=c++0x -static-libgcc -m64 -static-libstdc++ -mpopcnt -DPACKAGE_VERSION="\"v1.1.4-2-gd1998a1\"" asm_core.o assembler.o local_assemble.o iterate_edges.o build_read_lib.o lib_idba/contig_graph.o lib_idba/contig_graph_branch_group.o lib_idba/contig_info.o lib_idba/hash_graph.o lib_idba/sequence.o succinct_dbg.o assembly_algorithms.o options_description.o unitig_graph.o sequence_manager.o local_assembler.o city.o -lm -lz -lpthread -o megahit_asm_core
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
make: *** [megahit_asm_core] Error 1

I don't know whats wrong. Maybe I need a newer gcc version? something is missing in the ld, 

[mstambou@phi megahit]$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)

**Comment by voutcn** [comment]
The gcc version is okay. If you are still struggling with the environment problem, please use conda to install megahit or use megahit's docker image.
```
docker run -v $(pwd):/workspace -w /workspace --user $(id -u):$(id -g) vout/megahit \
  megahit -1 YOUR_READS_1.fq.gz -2 YOUR_READS_2.fq.gz -o megahit_out
```
