### ISSUE TITLE
The differences between v1.1.4 and v1.1.3?

### ISSUE THREAD

**Issue by xinbaiusc** [voutcn/megahit#194]
I used two different versions on the same dataset but the results are completely different.

It seems v1.1.4 outputs fewer but longer contigs.

Did you change your algorithm or threshold for v1.1.4? I am curious about why getting different results.

**Comment by voutcn** [comment]
v1.1.4 is a bug-fixing release and did not change any parameters.
What the parameters did you use? Could you attach the logs generated by v1.1.3 and v1.1.4?

**Comment by xinbaiusc** [comment]
Thanks Dinghua for you reply.

We did not specify any parameters and the default parameters were used. I attached two log files for v1.1.3 and v1.1.4 dealing with an identical dataset.

I do see v1.1.3 outputs more but shorter contigs. If you can help with this issue that would be great.

Best,

Xin

**Comment by xinbaiusc** [comment]
[log_megahit_1.1.4.log](https://github.com/voutcn/megahit/files/2852326/log_megahit_1.1.4.log)
[log_megahit_1.1.3.log](https://github.com/voutcn/megahit/files/2852328/log_megahit_1.1.3.log)

**Comment by xinbaiusc** [comment]
We have found the reason why we are having fewer contigs using v1.1.4. It is because of a changed parameter. The software itself definitely did not play a role.

Sorry about that and thanks Dinghua for your help.
