### ISSUE TITLE
Inquiry on MEGAHIT capabilities 

### ISSUE THREAD

**Issue by cssulliv** [voutcn/megahit#195]
Hi,

I am trying to gain a better understanding of the different assemblers that are available for analyzing metagenomic data. I wanted to know if MEGAHIT assembles short reads to contigs only or if it assembles short reads to contigs to scaffolds? If it is the former can you recommend a program that does contig to scaffold assemblies or can you recommend programs that assemble short reads to scaffolds :)

Lastly, this is more of a general bioinformatic question but is read recruitment (ex. using bowtie2) of short reads to the assemblies better than using programs like metaQUAST to check for the quality of the assembly? I ultimately want to know if it is necessary to utilize both read recruitment and metaQUAST. 

Thank you in advance for your help ^_^

**Comment by voutcn** [comment]
MEGAHIT assembles short reads to contigs only.
You may try SOAPdenovo2-fusion https://github.com/aquaskyline/SOAPdenovo2 for scaffolding.
If you have the reference genomes, metaQuast is a good tool to benchmark the assembly quality. Read recruitment (I think you mean alignment rate here) is always an indicator of the assembly quality.
