### ISSUE TITLE
k-mer

### ISSUE THREAD

**Issue by zhouyunyan** [voutcn/megahit#196]
Hi,
For the intestinal samples, sequenced on the Illumina Novaseq platform, generating150 bp paired-end reads, an average of 10 Gb per sample. how to set --k-mer and --step values? Do you have recommended parameters?

**Comment by voutcn** [comment]
My suggestion: just use the default one.

**Comment by zhouyunyan** [comment]
I used presets parameters: --k-list 27,37,47,57,67,77,87, is that be ok?
