### ISSUE TITLE
Makefile:230: recipe for target 'sequence_manager.o' failed

### ISSUE THREAD

**Issue by TealFurnholm** [voutcn/megahit#197]
Tried installations from git clone and from latest .tar.gz - both give the following 2 warnings and an errors when you run make. I first did a 'ls' so you could see the files in the directory.

tealfurn@alpena:~/MEGAHIT/megahit-1.1.4$ ls
asm_core.cpp             city.cpp            cx1_read2sdbg_s1.cpp  hash.h             kseq.h               lv2_cpu_sort.h           packed_reads.h            sequence_manager.cpp  utils.h
assembler.cpp            citycrc.h           cx1_read2sdbg_s2.cpp  hash_map.h         kthread.cpp          lv2_gpu_functions.cu     pool.h                    sequence_manager.h
assembly_algorithms.cpp  city.h              cx1_seq2sdbg.cpp      hash_table.h       lib_idba             lv2_gpu_functions.h      query_sdbg.cpp            sequence_package.h
assembly_algorithms.h    cub                 cx1_seq2sdbg.h        histgram.h         lib_info.h           Makefile                 rank_and_select.h         succinct_dbg.cpp
atomic_bit_vector.h      cx1.h               definitions.h         iterate_edges.cpp  LICENSE              megahit                  read_lib_functions-inl.h  succinct_dbg.h
bit_operation.h          cx1_kmer_count.cpp  edge_io.h             khash.h            local_assemble.cpp   mem_file_checker-inl.h   README.md                 tools
build_read_lib.cpp       cx1_kmer_count.h    example               kmer.h             local_assembler.cpp  options_description.cpp  sdbg_builder.cpp          unitig_graph.cpp
ChangeLog.md             cx1_read2sdbg.h     functional.h          kmer_plus.h        local_assembler.h    options_description.h    sdbg_multi_io.h           unitig_graph.h

tealfurn@alpena:~/MEGAHIT/megahit-1.1.4$ make
g++ -g -O2 -Wall -Wno-unused-function -Wno-array-bounds -D__STDC_FORMAT_MACROS -funroll-loops -fprefetch-loop-arrays -fopenmp -I. -std=c++0x -static-libgcc -m64 -static-libstdc++ -mpopcnt -c succinct_dbg.cpp -o succinct_dbg.o
g++ -g -O2 -Wall -Wno-unused-function -Wno-array-bounds -D__STDC_FORMAT_MACROS -funroll-loops -fprefetch-loop-arrays -fopenmp -I. -std=c++0x -static-libgcc -m64 -static-libstdc++ -mpopcnt -c assembly_algorithms.cpp -o assembly_algorithms.o
g++ -g -O2 -Wall -Wno-unused-function -Wno-array-bounds -D__STDC_FORMAT_MACROS -funroll-loops -fprefetch-loop-arrays -fopenmp -I. -std=c++0x -static-libgcc -m64 -static-libstdc++ -mpopcnt -c options_description.cpp -o options_description.o
g++ -g -O2 -Wall -Wno-unused-function -Wno-array-bounds -D__STDC_FORMAT_MACROS -funroll-loops -fprefetch-loop-arrays -fopenmp -I. -std=c++0x -static-libgcc -m64 -static-libstdc++ -mpopcnt -c unitig_graph.cpp -o unitig_graph.o
unitig_graph.cpp: In member function ‘int UnitigGraph::SearchAndMergeSuperBubble_(int64_t, int, bool, FILE*, Histgram<long int>&)’:
unitig_graph.cpp:581:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 if (visited.size() > max_len / 2) {
                                    ^
unitig_graph.cpp:528:9: warning: unused variable ‘num_tips’ [-Wunused-variable]
     int num_tips = 0;
         ^
In file included from hash_map.h:17:0,
                 from unitig_graph.h:29,
                 from unitig_graph.cpp:21:
hash_table.h: In instantiation of ‘struct HashTableNode<std::pair<long int, unsigned int> >’:
hash_table.h:102:16:   required from ‘HashTableIterator<Value, Key, HashFunc, ExtractKey, EqualKey>::value_type* HashTableIterator<Value, Key, HashFunc, ExtractKey, EqualKey>::operator->() const [with Value = std::pair<long int, unsigned int>; Key = long int; HashFunc = Hash<long int>; ExtractKey = Select1st<std::pair<long int, unsigned int> >; EqualKey = std::equal_to<long int>; HashTableIterator<Value, Key, HashFunc, ExtractKey, EqualKey>::pointer = std::pair<long int, unsigned int>*; HashTableIterator<Value, Key, HashFunc, ExtractKey, EqualKey>::value_type = std::pair<long int, unsigned int>]’
unitig_graph.cpp:430:76:   required from here
hash_table.h:50:7: warning: ignoring packed attribute because of unpacked non-POD field ‘std::pair<long int, unsigned int> HashTableNode<std::pair<long int, unsigned int> >::value’
     T value;
       ^
g++ -g -O2 -Wall -Wno-unused-function -Wno-array-bounds -D__STDC_FORMAT_MACROS -funroll-loops -fprefetch-loop-arrays -fopenmp -I. -std=c++0x -static-libgcc -m64 -static-libstdc++ -mpopcnt -c sequence_manager.cpp -o sequence_manager.o
In file included from sequence_manager.cpp:21:0:
sequence_manager.h:27:18: fatal error: zlib.h: No such file or directory
compilation terminated.
Makefile:230: recipe for target 'sequence_manager.o' failed
make: *** [sequence_manager.o] Error 1

**Comment by voutcn** [comment]
zlib is not installed.
If you are using Ubuntu, you can run `sudo apt-get install zlib1g-dev` to install it.
