### ISSUE TITLE
Access to the assembly graph?

### ISSUE THREAD

**Issue by tseemann** [voutcn/megahit#20]
I would like to visualize the megahit assembly graph in [Bandage](https://github.com/rrwick/Bandage).

But to do so the author @rrwick needs to write a parser for a assembly graph dump, or  a FASTG output format.

Does megahit have the ability to save a graph?

**Comment by voutcn** [comment]
MEGAHIT currently does not support saving a graph. 

A FASTG output is a possible solution to save & visualize a graph, but we want more discussions before putting efforts to support the graph output feature. FASTG is not widely used although it has been introduced for three years. And recently, the community has some discussions on [GFA format](http://lh3.github.io/2014/07/19/a-proposal-of-the-grapical-fragment-assembly-format/). Do you have any preference on different formats?

**Comment by rrwick** [comment]
While Bandage can already load FASTG files, it isn't too difficult to add support for a new format.  GFA looks nice, and if MEGAHIT could output graphs in that format, I'd be happy to add GFA support to Bandage.

**Comment by tseemann** [comment]
I think having an output that Bandage could load would help you debug and improve the assembler, as well as allow the community to investigate the true assembly result (the graph).

I think it will be particularly useful for *meta-transcriptomes*.

**Comment by mr-c** [comment]
+1 for GFA; glad to hear that Bandage might add support for it

**Comment by voutcn** [comment]
I found that it was not difficult to convert MEGAHIT's contigs into SPAdes' FASTG format. Will release a new version of MEGAHIT a tool for the conversion later this week so that Bandage can support it without any changes.

I will also keep my eyes on GFA's specification and turn to it in the further if I have time.

**Comment by voutcn** [comment]
The new version has been released along with a mini wiki page [Visualizing-MEGAHIT's-contig-graph](https://github.com/voutcn/megahit/wiki/Visualizing-MEGAHIT's-contig-graph).

**Comment by rrwick** [comment]
The FASTG conversion works well, and I can now load MEGAHIT graphs in Bandage.  Thank you for this feature!
