### ISSUE TITLE
error while running make simple_test

### ISSUE THREAD

**Issue by hafizmtalha** [voutcn/megahit#204]
I am trying installing megahit on my workstation. but I am facing this error. kindly help me resolve this issue. While ruuning **make simple_test**, it gives me following error

Error occurs when running "megahit_core buildlib";please refer to /tmp/megahit_testXuTm_4/out/log for detail
[Exit code -4]
CMakeFiles/simple_test.dir/build.make:60: recipe for target 'CMakeFiles/simple_test' failed
make[3]: *** [CMakeFiles/simple_test] Error 252
make[3]: Leaving directory '/media/alpha_genomics/9ce95615-e5d7-4b70-a54a-89fbb011c595/Metatest/S4/megahit/build'
CMakeFiles/Makefile2:107: recipe for target 'CMakeFiles/simple_test.dir/all' failed
make[2]: *** [CMakeFiles/simple_test.dir/all] Error 2
make[2]: Leaving directory '/media/alpha_genomics/9ce95615-e5d7-4b70-a54a-89fbb011c595/Metatest/S4/megahit/build'
CMakeFiles/Makefile2:114: recipe for target 'CMakeFiles/simple_test.dir/rule' failed
make[1]: *** [CMakeFiles/simple_test.dir/rule] Error 2
make[1]: Leaving directory '/media/alpha_genomics/9ce95615-e5d7-4b70-a54a-89fbb011c595/Metatest/S4/megahit/build'
Makefile:178: recipe for target 'simple_test' failed
make: *** [simple_test] Error 2

while the referred log file says the following

MEGAHIT v1.2.1-beta
--- [Mon Apr  8 12:17:30 2019] Start assembly. Number of CPU threads 2 ---
--- [Mon Apr  8 12:17:30 2019] Available memory: 135158800384, used: 121642920345
--- [Mon Apr  8 12:17:30 2019] Converting reads to binary library ---
/media/alpha_genomics/9ce95615-e5d7-4b70-a54a-89fbb011c595/Metatest/S4/megahit/build/megahit_core buildlib /tmp/megahit_testNdAw_R/out/tmp/reads.lib /tmp/megahit_testNdAw_R/out/tmp/reads.lib
Error occurs when running "megahit_core buildlib";please refer to /tmp/megahit_testNdAw_R/out/log for detail
[Exit code -4]

**Comment by voutcn** [comment]
Please run `./megahit --test --no-hw-accel` to verify. Because your PC does not support some hardware instructions, you should run Megahit (v1.2.1) with `--no-hw-accel` .
