### ISSUE TITLE
Error -6 terminate called after throwing an instance of 'std::bad_alloc' 

### ISSUE THREAD

**Issue by Young331** [voutcn/megahit#205]
I encountered eror code-6 as well. I am using MEGAHIT v1.2.1-beta. hope you can help?  Do you have any idea to fix it?  Thank you very much for your help in advance!  

My command lines is 
./modules/MEGAHIT-1.2.1-beta-Linux-static/bin/megahit -1 DNA-1117_1.clean.fq -2 DNA-1117_2.clean.fq -o assembly_1117 --k-min 79 --k-max 149 --k-step 10 --min-contig-len 1000 -t 72 --no-hw-accel

Here is the log file detail:
MEGAHIT v1.2.1-beta
--- [Tue Apr 9 14:58:18 2019] Start assembly. Number of CPU threads 68 ---
--- [Tue Apr 9 14:58:18 2019] Available memory: 135082373120, used: 121574135808
--- [Tue Apr 9 14:58:18 2019] Converting reads to binary library ---
/scale_wlg_persistent/filesets/project/uoa02698/modules/MEGAHIT-1.2.1-beta-Linux-static/bin/megahit_core_no_hw_accel buildlib assembly_1117/tmp/reads.lib assembly_1117/tmp/reads.lib
[INFO src/main_buildlib.cpp 122] Lib 0 (/scale_wlg_persistent/filesets/project/uoa02698/DNA-1117_1.clean.fq,/scale_wlg_persistent/filesets/project/uoa02698/DNA-1117_2.clean.fq): pe, 531284512 reads, 150 max length
[INFO src/main_buildlib.cpp 119] Real: 636.1904 user: 554.7897 sys: 51.2243 maxrss: 162060
--- [Tue Apr 9 15:08:54 2019] k list: 79,89,99,109,119,129,139,149 ---
--- [Tue Apr 9 15:08:54 2019] Extracting solid (k+1)-mers for k = 79 ---
cmd: /scale_wlg_persistent/filesets/project/uoa02698/modules/MEGAHIT-1.2.1-beta-Linux-static/bin/megahit_core_no_hw_accel count -k 79 -m 2 --host_mem 121574135808 --mem_flag 1 --output_prefix assembly_1117/tmp/k79/79 --num_cpu_threads 68 --num_output_threads 22 --read_lib_file assembly_1117/tmp/reads.lib
[INFO src/main_sdbg_build.cpp 91] Host memory to be used: 121574135808
[INFO src/main_sdbg_build.cpp 92] Number CPU threads: 68
[INFO src/main_sdbg_build.cpp 264] Preparing data...
terminate called after throwing an instance of 'std::bad_alloc'
what(): std::bad_alloc
Error occurs when running "sdbg_builder count/read2sdbg",please refer to assembly_1117/log for detail
[Exit code -6]

**Comment by voutcn** [comment]
Could you attach the whole log file (i.e. `assembly_1117/log`) here?

**Comment by voutcn** [comment]
It seems that it just ran out of memory. According to the log, I think you might need at least 30Gb (free) memory.
