### ISSUE TITLE
Argument list too long

### ISSUE THREAD

**Issue by jpecar** [voutcn/megahit#206]
Hi,

we have a user using this software where he actually needs to pass thousands of files as a comma-separated argument. This is failing with "argument list too long". Looking at man execve, I assume it is because that argument is comma separated without spaces, treated as a single string and single string limit is 32 pages (128kB). 

Q: Can this argument be separated with comma and space so it is not treated as a single string?
Q: If not, can you provide an alternative method for megahit to read thousands of input files? Something like a single file with a list of input files?

**Comment by jpecar** [comment]
Possibly something like this:

```
diff --git a/megahit b/megahit
index abfcf49..6b3b4ae 100755
--- a/megahit
+++ b/megahit
@@ -312,10 +312,20 @@ def parse_opt(argv):
         elif option in ("-r", "--read"):
             opt.se += value.split(",")
         elif option == "-1":
-            opt.pe1 += value.split(",")
+            if value == 'stdin':
+                opt.pe1 = [x.strip() for x in sys.stdin]
+            else:
+                opt.pe1 += value.split(",")
         elif option == "-2":
-            opt.pe2 += value.split(",")
+            if value == 'stdin':
+                opt.pe2 = [x.strip() for x in sys.stdin]
+            else:
+                opt.pe2 += value.split(",")
         elif option == "--12":
+            if value == 'stdin':
+                opt.pe12 = [x.strip() for x in sys.stdin]
+            else:
+                opt.pe12 += value.split(",")
             opt.pe12 += value.split(",")
         elif option == "--input-cmd":
             opt.input_cmd = value
```
And then one can do ```find /where/thousands/of/files/reside -type f | megahit -1 stdin -o outdir```

**Comment by voutcn** [comment]
You can use `-1`, `-2` or `--12` multiple times. Like `-1 A_1.fq -1 B_1.fq -2 A_2.fq -2 B_2.fq`.
