### ISSUE TITLE
Megahit & error correction

### ISSUE THREAD

**Issue by a-kroh** [voutcn/megahit#209]
Thanks for this great tool – it is a very fast and easy to use tool!

Lately I have been seeing a lot of fragmentation in the assemblies (single-species, genomic, coverage 40x) I ran and was wondering if that could be related to erroneous k-mers.

Do you have any experience on the effect of error correction tools on assemblies with megahit – published reviews on k-mer based error correction of reads in general came to very different conclusions, but none specifically addressed the topic in context of the Megahit assembler.

Kind regards,
Andreas

**Comment by voutcn** [comment]
I don't think there are any error-correction tools specifically designed for one particular assembler. You can try any of them (BBNorm, BFC, Lighter etc).
