### ISSUE TITLE
Using long reads in MEGAHIT

### ISSUE THREAD

**Issue by shaman-narayanasamy** [voutcn/megahit#21]
Dear authors,

I would like your opinion about using contigs or long reads (in fasta format) within MEGAHIT. Is the software, at its current state suitable for such input?

I look forward to hear your thoughts.

Best regards,
Shaman

**Comment by voutcn** [comment]
Hi Shaman,
How long is your "long reads" or contigs?

**Comment by shaman-narayanasamy** [comment]
Well, for this particular data set, the longest read is: 11633. Also note that there are varying read lengths.

I actually made and attempts to run MEGAHIT on such data. Below is what I have to report at the moment. Here is the command issued:

```
megahit -o MTpooledAssembledSequences-megahit-ALL_MG-reads_megahit --cpu-only -m 763000000000 --mem-flag 1 -l 11633 -r pooledAssembledSequences_MT-megahit_MT-megahit2_MG_reads.fa -t 24
```

And This is the error received:

```
MEAGHIT v0.2.0-alpha
[Fri Feb 27 15:51:45 2015] Start assembly. Number of CPU threads 24.
[Fri Feb 27 15:51:45 2015] Extracting solid (k+1)-mers for k = 21
[Fri Feb 27 16:06:29 2015] Building graph for k = 21
sdbg_builder_cpu: io-utility.h:202: void ReadPackage::ReadBinaryReads(gzFile): Assertion `num_bytes % (words_per_read * sizeof(edge_word_t)) == 0' failed.
Error occurs when running "builder build" for k = 21
[Exit code -6]
```

As  you can see, it was run on a high memory machine with 24 threads and ~720 GB of memory available.

-Shaman-

**Comment by voutcn** [comment]
Please send the log file in the output directory to me (voutcn <at> gmail <dot> com) directly.

**Comment by voutcn** [comment]
Fixed https://github.com/voutcn/megahit/commit/06f84d5cf317dc3324eeeb949a92935dc75c1ca4
