### ISSUE TITLE
Error when running "megahit_core buildlib" [Exit Code -4]

### ISSUE THREAD

**Issue by hafizmtalha** [voutcn/megahit#212]
While running my single end file I am facing this problem. and there is nothing much in log file as well. can any one help me on this.
Error when running "megahit_core buildlib"; please refer to ./megahit_out/log for details
[Exit Code -4]

**Comment by voutcn** [comment]
Were you using v.1.2.1-beta? Try `--no-hw-accel` option.
You can also upgrade to [v.1.2.2-beta](https://github.com/voutcn/megahit/releases/tag/v1.2.2-beta) which can automatically detect hardware compatibility to avoid "exit code -4".
