### ISSUE TITLE
Exit code -11

### ISSUE THREAD

**Issue by ucassee** [voutcn/megahit#213]
Dear developer,
        I use megahit to assemble my metagenome. It went error in assembling contigs for k = 183. The following is error occur in log

> --- [Thu May  9 01:23:01 2019] Assembling contigs from SdBG for k = 183 
cmd: /home/zhouyl/software/MEGAHIT-1.2.2-beta-Linux-static/bin/megahit_core_no_hw_accel assemble -s B10megahit/tmp/k183/183 -o B10megahit/intermediate_contigs/k183 -t 40 --min_standalone 450 --prune_level 2 --
merge_len 20 --merge_similar 0.95 --low_local_ratio 0.2 --min_depth 2 --bubble_level 2 --max_tip_len 268.0 --careful_bubble
    [INFO  src/main_assemble.cpp     120]   Loading succinct de Bruijn graph: B10megahit/tmp/k183/183 Done. Time elapsed: 224.010985
    [INFO  src/main_assemble.cpp     124]   Number of Edges: 2020685435; K value: 183
    [INFO  src/main_assemble.cpp     131]   Number of CPU threads: 40
Error occurs when assembling contigs for k = 183, please refer to B10megahit/log for detail
[Exit code -11]

Thanks in advance. Hope to your reply~

**Comment by voutcn** [comment]
If you did not remove the files output by Megahit, could you run this and attach the log?

```
catchsegv  /home/zhouyl/software/MEGAHIT-1.2.2-beta-Linux-static/bin/megahit_core_no_hw_accel assemble -s B10megahit/tmp/k183/183 -o B10megahit/intermediate_contigs/k183 -t 40 --min_standalone 450 --prune_level 2 --merge_len 20 --merge_similar 0.95 --low_local_ratio 0.2 --min_depth 2 --bubble_level 2 --max_tip_len 268.0 --careful_bubble
```

**Comment by ucassee** [comment]
@voutcn 
Thanks for your reply. this is the log file 

[log.txt](https://github.com/voutcn/megahit/files/3170042/log.txt)

**Comment by strejcem** [comment]
Hi,
I'd like to join in as I have the same problem. The terminal printed out: Segmentation fault (core dumped). 
[log.txt](https://github.com/voutcn/megahit/files/3170367/log.txt)
I am using a lab PC and the inputs are merged interleaved pair-ends + the unmerged reads. I dd not have any problems with 2x150 separate pair-ends of the same data.

@ucassee Did you run the catchsegv? I think @voutcn was more interested in the log from catchsegv than the megahit again.

I am running the catchsegv  right now but it is super slow. It's been running for almost 6 hours, while the unfinished megahit ran under an hour, which got stuck at 201 of 45,71,97,123,149,175,201,225 k-mers. Will post update later.

Mike

**Comment by voutcn** [comment]
@strejcem @ucassee I found and fixed the bug. Please try https://github.com/voutcn/megahit/releases/tag/v1.2.3-beta

**Comment by ucassee** [comment]
Hi @strejcem, 
I run the catchsegv. I use server with 20 cores. It might only take less than half an hour. I will try to use the v1.2.3 first.

**Comment by strejcem** [comment]
@ucassee It's fixed! Thanks a lot!
