### ISSUE TITLE
Checkpoint Large Metagenome Assembly

### ISSUE THREAD

**Issue by mbcouger** [voutcn/megahit#218]
Hello, 

 I am running a very large assembly on a supercomputer that has a local disk to page off of. Is there any way I can tell megahit to stop after a certain kmer point (or if I told it only to do one kmer can I modify it to work this way) so I can copy the current checkpoint back to a non volatile disk.

Many Thanks!
Brian

**Comment by mbcouger** [comment]
Hello Voutcn, 

 I went back and looked through my logs for previous metageomes assemblies and realized that I can run the core commands individually. If possible, do you have preferred quality trimming protocol to remove erroneous kmers. 

Many Thanks,
Brian

**Comment by voutcn** [comment]
You can use `--continue` to resume a job.

For quality trimming/filtering I don't have personal suggestions. There are some workshop materials you can refer to, for example
https://usda-ars-gbru.github.io/Microbiome-workshop/tutorials/metagenomics/
https://2017-dibsi-metagenomics.readthedocs.io/en/latest/quality.html

**Comment by mbcouger** [comment]
Thanks Voutcn!
