### ISSUE TITLE
Combine read files - interleaving necessary ?

### ISSUE THREAD

**Issue by pieterjanvc** [voutcn/megahit#227]
Hi,

I am in the process of creating artificial metagenomes, and am combining and altering read files and merging them together before I assemble them. I'm wondering if MEGAHIT requires the files to be interleaved if I merge my read files, or can I just merge them without interleaving and obtain the same output (saves time not having to interleave the files). If I don't have to interleave (but so there are still pairs of reads, but not together), do I use argument --12 or -r ?

Thanks

**Comment by voutcn** [comment]
What do you mean by "merging"? Do you just append PE2.fq to PE1.fq? If you put paired reads into a single file, interleaving the reads is the only way that Megahit can handle them as paired.

**Comment by pieterjanvc** [comment]
Thanks for the info, that was what I was looking for!
