### ISSUE TITLE
Support for option like "--k-only"

### ISSUE THREAD

**Issue by tseemann** [voutcn/megahit#23]
There are various applications where you want to use a _single_ k value for a fast, rough assembly.

An option like ```--k-only 51``` would be helpful, instead of ```-k-min 51 --k-max 51```.

Not very important, just an idea.

**Comment by voutcn** [comment]
`--k-list` in the latest version v0.3.0-beta can do this.

**Comment by tseemann** [comment]
That's a great solution - thank you.
