### ISSUE TITLE
Small assembly size

### ISSUE THREAD

**Issue by soungalo** [voutcn/megahit#230]
Hello,
I am trying to assemble a tomato genome (900Mb) using a single PE library with ~x30 coverage.
While MEGAHIT produces fairly nice N50 (11kb), assembly size is a bit small with ~640Mb. What's interesting is that I was able to get an assembly ~770Mb in size using a different tool on the same data.
Could you suggest a way to configure MEGAHIT in order to get a more complete assembly? I've used default params for my run. Maybe you can direct me to some log info or stats that can give me a hint on why certain regions were not assembled?
Thanks!

**Comment by voutcn** [comment]
Hi @soungalo 

If you are using a version >= 1.2.6, you may try `--cleaning-rounds 1 --disconnect-ratio 0`.

**Comment by soungalo** [comment]
Thanks, that increased assembly size by ~10% (700Mb) and also N50 by ~30%.
