### ISSUE TITLE
Cannot detect available memory on OSX

### ISSUE THREAD

**Issue by jenniportman** [voutcn/megahit#232]
The `detect_available_mem` function in the wrapper script uses `SC_PHYS_PAGES` which is not available on OSX:

```
>>> import os
>>> os.sysconf('SC_PAGE_SIZE')
4096
>>> os.sysconf('SC_PHYS_PAGES')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: unrecognized configuration name
```

Problematic line is: 
https://github.com/voutcn/megahit/blob/d97f0378abd6c440d8cd3de17caee6a5cba9b188/src/megahit#L595

**Comment by voutcn** [comment]
It works with newer versions of MacOS. You can still use `-m` to run it.
For example, if you have 16G memory, you may try `-m 15e9`.

**Comment by jenniportman** [comment]
It doesn't work for me on Mojave/2017 Macbook Pro. 

I have been using the `-m` option to run it, but it would be nice to have a fix for this.

**Comment by voutcn** [comment]
Should have been fixed in https://github.com/voutcn/megahit/releases/tag/v1.2.9
