### ISSUE TITLE
about memory setting

### ISSUE THREAD

**Issue by PuziJiang** [voutcn/megahit#236]
Dear sir,
I am using MEGAHIT to co-assemble a large matgenomic data (nearly 144G per paired-end file). 
However, when I set the options as below, the tasks were always killed due to out of memory if I ran two tasks. And, I found that memory usage in one task (nearly 200G) was larger than what I set (0.3*256G):

megahit -1 ${file}_all.1.fq.gz -2 ${file}_all.2.fq.gz --kmin-1pass -m 0.3 --mem-flag 2 -t 40 -o ${dir}/assemble1 --out-prefix ${prefix}

What's wrong in the command?  Thanks in advance.

**Comment by voutcn** [comment]
The `-m` only defines the maximum memory used by the graph-construction stage (the algorithm used can trade speed for memory usage). It won't limit the memory usage in other stages (assembly, local assembly, iterative k-mer extraction).
