### ISSUE TITLE
Pre-built docker image-docker run error: docker: Error response from daemon

### ISSUE THREAD

**Issue by snmrna** [voutcn/megahit#243]
Dear all，
I have installed docker and docker-machine on my Macbook Air, when I run the following command: docker run -v $(pwd):/workspace -w /workspace --user $(id -u):$(id -g) vout/megahit \ megahit -1 clean.R1.fq.gz -2 clean.R1.fq.gz -o output
It reported: **docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \" megahit\": executable file not found in $PATH": unknown.**

Anyone can tell me how to fix the problem? Thanks in advance.

**Comment by sjaenick** [comment]
This seems to be a problem with the Docker image, which has megahit installed under
/root/megahit/build, so it's not accessible to non-root users. Try removing

```
--user $(id -u):$(id -g)
```

from your command line.

**Comment by snmrna** [comment]
> This seems to be a problem with the Docker image, which has megahit installed under
> /root/megahit/build, so it's not accessible to non-root users. Try removing
> 
> ```
> --user $(id -u):$(id -g)
> ```
> 
> from your command line.



> This seems to be a problem with the Docker image, which has megahit installed under
> /root/megahit/build, so it's not accessible to non-root users. Try removing
> 
> ```
> --user $(id -u):$(id -g)
> ```
> 
> from your command line.

Thanks very much for your reply! But I got the same error after I removed "--user $(id -u):$(id -g)" from my command line, do you know any other solutions?

**Comment by voutcn** [comment]
Before I investigate this problem please use the image provided by bio-conda.
```
docker run -v $(pwd):/workspace -w /workspace --user $(id -u):$(id -g) quay.io/biocontainers/megahit:1.2.8--h8b12597_0 megahit 
```

See https://quay.io/repository/biocontainers/megahit?tab=tags for other versions.

**Comment by snmrna** [comment]
> Before I investigate this problem please use the image provided by bio-conda.
> 
> ```
> docker run -v $(pwd):/workspace -w /workspace --user $(id -u):$(id -g) quay.io/biocontainers/megahit:1.2.8--h8b12597_0 megahit 
> ```
> 
> See https://quay.io/repository/biocontainers/megahit?tab=tags for other versions.

Thanks for your quick reply! I successfully pulled down the image provided by bio-conda using your command. But when I input the following command: docker run -v $(pwd):/workspace -w /workspace --user $(id -u):$(id -g) quay.io/biocontainers/megahit:1.2.8--h8b12597_0 megahit -1 clean.R1.fq.gz -2 clean.R1.fq.gz -o output
It reported: 
Traceback (most recent call last):
  File "/usr/local/bin/megahit", line 1024, in <module>
    main()
  File "/usr/local/bin/megahit", line 964, in main
    setup_output_dir()
  File "/usr/local/bin/megahit", line 460, in setup_output_dir
    mkdir_if_not_exists(opt.out_dir)
  File "/usr/local/bin/megahit", line 122, in mkdir_if_not_exists
    os.mkdir(path)
PermissionError: [Errno 13] Permission denied: '/workspace/output'

Do you know how to solve this problem? Thanks

**Comment by voutcn** [comment]
It works on my PC.
Do you have permission to create a new directory in your current working directory?

**Comment by voutcn** [comment]
@snmrna I found [this post](https://github.com/docker/for-linux/issues/561#issuecomment-454694108) and it might be helpful. It is a docker issue. Please try the fix proposed by the post and try the prebuilt docker container (`vout/megahit`)

**Comment by voutcn** [comment]
Closing this issue.
