### ISSUE TITLE
How many reads were used / not used in the assembly?

### ISSUE THREAD

**Issue by tseemann** [voutcn/megahit#247]
We were wondering if `megahit` can output some statistics about how many of the input reads it actually used in the assembly, and how many it didn't use?

This would be useful to know, and to help QC the data provided. We understand we can align the original reads back to the contigs/graph but were wondering if megahit can tell us instead.

CC: @milot-mirdita

**Comment by voutcn** [comment]
I don't think I can provide a meaningful stat since reads had been decomposed into k-mers. Perhaps I can provide the number of reads that do not contribute any solid k-mers the smallest k. But even solid k-mers can be removed by the graph cleaning process.

**Comment by tseemann** [comment]
@voutcn thanks for considering this question, i thought that might be the case! thank you.
