### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by shayandoust** [voutcn/megahit#248]
Hello,

My name is Shayan and I am a contributor for the Debian-Med packaging team[1]. More specifically, this software is being packaged for Debian[2], however I am hitting some slight issues.

Generally, pbuilder[3] is used to build the package within a chroot / clean environment and to test if the package builds successfully. Pbuilder builds within sid. Unfortunately, there is an error during the compilation step which I cannot seem to figure out a patch or fix for[4]. Any suggestions or help would be much appreciated.

Kind regards,
Shayan Doust

[1]: https://salsa.debian.org/med-team
[2]: https://salsa.debian.org/med-team/megahit
[3]: https://wiki.debian.org/Diaspora/Packaging/pbuilder
[4]: https://paste.debian.net/1110382/

**Comment by voutcn** [comment]
I encountered this with gcc8 too. And it has been fixed in v1.2.9 or the latest master branch. Could you try the latest source code?

Thank you for your help to pack Megahit to Debian-Med!

**Comment by voutcn** [comment]
I also reviewed the Debian-Med repo for Megahit. I think [this patch](https://salsa.debian.org/med-team/megahit/commit/dedb3d8f4e00c38f90ba5e582b51c1094ad69ece#16c460cde22536759ae04c25443db3e3073df627_0_9) is incorrect and breaks the correctness of the function. We just need to remove the `__attribute__((packed))` as shown [here](https://github.com/voutcn/megahit/commit/36f5d4543bddc887b26e6bd42d722c9aaefac10b#diff-d746908d2b579a0f2476dec71efbd4b8L217).

**Comment by shayandoust** [comment]
Hello,

>  And it has been fixed in v1.2.9 or the latest master branch. Could you try the latest source code?

Yes it has. Thanks!

> I also reviewed the Debian-Med repo for Megahit. I think this patch is incorrect and breaks the correctness of the function. We just need to remove the __attribute__((packed)) as shown here.

The patch was more of an experimentation to try figure out why it was failing with relation to the compiler's output. As the latest upstream tarball has fixed this issue, I'll remove the patch.

Thanks once again.
