### ISSUE TITLE
sorting/kmer_counter.cpp Read count higher than total read count

### ISSUE THREAD

**Issue by Finesim97** [voutcn/megahit#261]
Hi,
In the log I noticed following lines (truncated) on the input libraries:
```
b'INFO  sequence/io/sequence_lib.cpp  :   77 - Lib 0 [...] pe, 983420 reads, 301 max length'
b'INFO  sequence/io/sequence_lib.cpp  :   77 - Lib 1[...] se, 1716784 reads, 593 max length'
[...]
b'INFO  sorting/kmer_counter.cpp      :   76 - 2700566 reads, 593 max read length'
```
The read count sum would be 2700204. Why does the lib file contain 362 reads more?

Thanks for your great work,
Lukas Jansen

**Comment by voutcn** [comment]
It is possible if some reads are shorter than the k-mer size.
