### ISSUE TITLE
Very different results running megahit v1.2.9 with same parameters on two different clusters

### ISSUE THREAD

**Issue by SonWende** [voutcn/megahit#263]
Hello, 

while attempting to assemble a metagenomic sample with megahit with the option `meta-large`, I noticed that i get two very different results for running megahit with the same parameters on two different clusters. 
The only difference in the running parameters come from the fact, that different number of cpus and memory are available on cluster 1 and 2: megahit used 256 threads and 0.9 of 504 Gb memory on one system, and 80 threads and 0.9 of 95 GB memory on the other system. 

This results in 

- number of contigs: 660003 vs 357694 
- largest contig: 125048 vs 51345
- N50: 1196 vs 969  

(For more stats see the attached Quast report. I will also attach the megahit options.json)

I already saw that megahit is not deterministic, bit this seems to be to vast a difference. I also checked, that it is the same version of megahit; both installations are megahit 1.2.9

Do you have any idea what may have caused this? And i how can i proceed, so that i can have a trustworthy  assembly?

Thank you very much in advance

[Cluster2-options.txt](https://github.com/voutcn/megahit/files/4236319/Cluster2-options.txt)
[HPC-options.txt](https://github.com/voutcn/megahit/files/4236320/HPC-options.txt)
[report.txt](https://github.com/voutcn/megahit/files/4236326/report.txt)

**Comment by voutcn** [comment]
It seems that you used `L_R1.fasta.gz` for both forward and reversed reads.
