### ISSUE TITLE
different assemble runing megahit with same sample and same parameters

### ISSUE THREAD

**Issue by feihongloveworld** [voutcn/megahit#264]
i run many times for a sample with megahit，but got different assmble fasta  .......
What does make the difference ？
cmd as below：

megahit -r R1.fastq -o xxxx --out-prefix  xxxx
or
megahit -1 R1.fastq -2 R2.fastq -o xxxx --out-prefix  xxxx

**Comment by fconstancias** [comment]
`megahit -r R1.fastq -o xxxx --out-prefix xxxx` : you are using only R1 
`megahit -1 R1.fastq -2 R2.fastq -o xxxx --out-prefix xxxx` : you are using both R1 and R2 of your pair-end librairy
