### ISSUE TITLE
Insufficient memory warning

### ISSUE THREAD

**Issue by shaman-narayanasamy** [voutcn/megahit#27]
I receive a flurry of these warnings over and over again in the terminal:

```
[B::ReadInputFile WRANING] No enough memory to hold all the reads. Only the first 37292817 reads are kept.
```

Is this supposed to happen? FYI, I am using the "long read" bug fixed version.

**Comment by voutcn** [comment]
I guess that you set a very large `-l` parameter.
MEGAHIT will load all reads into memory before graph construction. It uses fixed length (max read length specified by `-l`) to store reads, so when `-l` is large, it needs more memory for the reads.

And the waring message is explained on [this wiki page](https://github.com/voutcn/megahit/wiki/MEGAHIT-Memory-setting):
>When the memory specified by -m is not enough to hold all reads, MEGAHIT will raise a warning message and try to keep only a portion of reads and perform a partial assembly.

**Comment by shaman-narayanasamy** [comment]
Understood. The thing is, it repeats warning so many times. Since I am running this in passively (i.e. in the background), my log files are huge. This one came up to 2.9GB. I terminated the process upon seeing that. Is it supposed to do that?

**Comment by voutcn** [comment]
Oh that's a bug. Please check out the latest commit which got it fixed.
