### ISSUE TITLE
megahit exit code -6

### ISSUE THREAD

**Issue by Zhanglin1990** [voutcn/megahit#270]
Dear Megahit Team,

Now I am using megahit v-1.2.9 to assemble metagenomics samples. My CPU is 10 and memory is about 46G. I have read other issues associated with this issue, but they don't work. Could you please give me some advice? These are the last lines of the log, if you need more information, please contact me. Thank you very much.
![image](https://user-images.githubusercontent.com/44035901/79480418-6ad77e80-7fe4-11ea-88ae-6c9fc42027b2.png)

**Comment by voutcn** [comment]
The sample is too big to assemble with 46G memory. Please try cleaning/normalizing your data first. Please refer to https://github.com/voutcn/megahit/issues/239#issuecomment-534373589
