### ISSUE TITLE
Memory Setting Error

### ISSUE THREAD

**Issue by jrherr** [voutcn/megahit#28]
Hi, I've searched all over the issues and online elsewhere and I can't find a reference to this, perhaps you can help.

When I try this command:
```
megahit --cpu-only -m 60e9 -max_read_len 250 -r input.fastq
```
I get this error message:
```
Traceback (most recent call last):
  File "/opt/software/megahit/20141001--GCC-4.4.5/bin/megahit", line 584, in <module>
    sys.exit(main())
  File "/opt/software/megahit/20141001--GCC-4.4.5/bin/megahit", line 513, in main
    host_mem = long(value)
ValueError: invalid literal for long() with base 10: '60e9'
```
Could I have compiled incorrectly or do I need to adjust the memory? Memory should not be an issue as I am on a shared server.  I don't know what the error is with the '60e9' string.

Thanks so much for your time!

**Comment by voutcn** [comment]
Hi Josh,

I guess that you are using a rather old version which does not support parsing float value like 60e9 for the “-m” option. What’s the version you are using? (if you use checked it out from github, use "git describe” in the directory)

Cheers,
Dinghua

**Comment by jrherr** [comment]
Thank you very much for the quick reply Dinghua...

I'm using megahit on a shared high performance cluster, the version is stated as:
```
megahit:
  ---------------------------------------------------------------------------------
     Versions:
        megahit/20141001
```
Looks like this is an older version -- I should ask to have the sysadmin recompile a newer version.  Should that fix the problem?

**Comment by voutcn** [comment]
Yes, it should. Please checkout the head of the master branch.

**Comment by jrherr** [comment]
Thank you -- I will have the module updated.  Cheers!
