### ISSUE TITLE
Recover an assembly i.e. the "final.contigs.fa" file, using the intermediary files

### ISSUE THREAD

**Issue by MaryoHg** [voutcn/megahit#299]
Dear @voutcn 

Is there any way to recover the "final.contigs.fa" file using the intermediary files of a run?

I have all the outputs of an assembly run but not the final.contigs.fa file. 
I want to avoid running the assembly process again on that single sample.

I appreciate any suggestion.
Thanks for your time @voutcn.

MaryoHg.

**Comment by evolphotonics** [comment]
Dear @MaryoHg (and @voutcn)
did you ever find a solution - I have the same problem - my final.contigs.fa is empty, but the log has no errors or warnings. strange. i suspect this may be due to low storage disk space?
Thanks

**Comment by MaryoHg** [comment]
Dear @evolphotonics ,

Sorry for the late reply.
I did not recovered that file. I had to run the assembly again.
I didn't try running the assembly again using the initial `--continue` option to recover it, though.

Have fun!
