### ISSUE TITLE
Command line defaults in megahit - maybe $ENV variables?

### ISSUE THREAD

**Issue by tseemann** [voutcn/megahit#30]
Megahit has a lot of compulsory command line options that are difficult for users to choose.

Ideally --memory and --max-read-len would not be necessary but I understand you would like to leave those, but could they be set via environment variables, eg.

    export MEGAHIT_MEMORY=1E10
    export MEGAHIT_MAXREADLEN=602
    export MEGAHIT_THREADS=8

Or possibly just a single variable:

    export MEGAHIT_OPTIONS="--cpu-only -t 8 -m 1E10 -l 602 --min-count 3"

Is there a way to automatically choose --cpu-only if it wasn't compiled against GPU ?

**Comment by voutcn** [comment]
It seems that CPU version is more commonly used. I plan release a new version soon with `--cpu-only` on by default, and provide another option `--use-gpu` for GPU users.

**Comment by tseemann** [comment]
I think an ```--auto``` setting to select some sensible defaults would help people to use it. I see students struggle with choosing ```-m``` and ```-l```.

**Comment by voutcn** [comment]
I think `-l` is not troublesome, and many other assemblers like SOAPdenovo require such a configuration.
We also merged a [pull request](https://github.com/voutcn/megahit/pull/22) to support semi-auto `-m`, which can auto detect a machine's memory size and users are only required to set a fraction of memory to be used.

**Comment by voutcn** [comment]
In the latest release v0.3.0-beta, `-l` is not need and `-m` is automatically selected.

**Comment by tseemann** [comment]
Thanks!
