### ISSUE TITLE
Overwrite output folder

### ISSUE THREAD

**Issue by shaman-narayanasamy** [voutcn/megahit#32]
Hi,

This is not really a big issue.

I would like to know if there an option to force overwrite of output directory. Perhaps I missed this in the documentation somewhere.

At the moment, there is no specific option and I bypass it by using the `--continue` option (which is actually for checkpointing purposes) to achieve this. This is fine for me, but maybe some users would like to restart their assembly and retain the folder names :)

-Shaman-

**Comment by voutcn** [comment]
No such an option. The nonexistence of the output dir is a strict requirement since v0.2.1, which avoids the danger of mixing two assemblies or overwriting the intermediate files which is essential for `--continue` mode.

**Comment by shaman-narayanasamy** [comment]
Ok, understood! Will stick to the `--continue` mode :)

Closing issue.
