### ISSUE TITLE
Broken backward compatibility with -o option

### ISSUE THREAD

**Issue by tseemann** [voutcn/megahit#33]
Something has changed in 0.2.1 from 0.2.0a ?

I now get this message which has broken my pipelines....

```Output directory xxxxx/ already exists, please change the parameter -o to another value to avoid overwriting.```

Can you add a ```--force``` option to allow writing into an existing folder?

**Comment by voutcn** [comment]
Hi Torsten,
The `--continue` option should be an easy solution for you. Please also refer to https://github.com/voutcn/megahit/issues/33.

**Comment by voutcn** [comment]
Anyway, using the existing directory as an output directory is dangerous and not recommended. Please consider updating your pipeline. I am happy to help if needed :)

**Comment by tseemann** [comment]
It was a Makefile based system. I will amend it to resolve this interface change. Thank you.
