### ISSUE TITLE
200bp lower limit?

### ISSUE THREAD

**Issue by pdmarco** [voutcn/megahit#34]
Hi. We ran two metagenomes (Illumina HiSeq 2500 + trimmed + quality checked) with megahit and the resulting sequence lengths, in both cases, started at exactly 200bp. Is this supposed to happen or did we do something wrong?
I would expect a) lots of sequences not to assemble, so lots of short sequences at the low end of the spectrum and b) smaller assembled sequences to have (random?) different lengths.
Thanks.

**Comment by voutcn** [comment]
Yes, 200bp is supposed, because MEGAHIT by default outputs contigs of length >= 200bp. You can use `--min-contig-len` to lower this bound, at the risk of producing more short and erroneous contigs.

**Comment by pdmarco** [comment]
Thank you Dr. Li for your answer.

I wasn't aware of this, I thought all unassembled sequences would still be there at the bottom of the "length scale" in the output file.

Is there a way to understand how many sequences were left out of assembly? Are they binned into some "reject" file? We would like to have an idea of how much information was left out during assembly.

Thanks again. Regards.


Paolo

________________________________
De: Dinghua Li <notifications@github.com>
Enviado: 5 de maio de 2015 03:01
Para: voutcn/megahit
Cc: Paolo De Marco
Assunto: Re: [megahit] 200bp lower limit? (#34)


Yes, 200bp is supposed, because MEGAHIT by default outputs contigs of length >= 200bp. You can use --min-contig-len to lower this bound, at the risk of producing more short and erroneous contigs.

-

**Comment by voutcn** [comment]
No, those reads are not binned to a file.
In fact it is hard for de bruijn graph assembler to tell how many reads are
used during assembly, because reads are chomp into kmers, and some reads
not fully used because they contain errors.
To estimate how many reads are "assembled", I recommend aligning reads back
to the contigs with short read aligner like Bowtie2. If a read is aligned
back to contigs, it can be considered as "being assembled".

Regards,
Dinghua

On Tue, May 5, 2015 at 7:03 PM, pdmarco <notifications@github.com> wrote:

> Thank you Dr. Li for your answer.
>
> I wasn't aware of this, I thought all unassembled sequences would still be
> there at the bottom of the "length scale" in the output file.
>
> Is there a way to understand how many sequences were left out of assembly?
> Are they binned into some "reject" file? We would like to have an idea of
> how much information was left out during assembly.
>
> Thanks again. Regards.
>
>
> Paolo
>
> ________________________________
> De: Dinghua Li <notifications@github.com>
> Enviado: 5 de maio de 2015 03:01
> Para: voutcn/megahit
> Cc: Paolo De Marco
> Assunto: Re: [megahit] 200bp lower limit? (#34)
>
>
> Yes, 200bp is supposed, because MEGAHIT by default outputs contigs of
> length >= 200bp. You can use --min-contig-len to lower this bound, at the
> risk of producing more short and erroneous contigs.
>
> -
> Reply to this email directly or view it on GitHub<
> https://github.com/voutcn/megahit/issues/34#issuecomment-98904158>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/voutcn/megahit/issues/34#issuecomment-99033244>.
>



-- 
Sincerely,
Dinghua (a.k.a vout)
email: voutcn@gmail.com
