### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ghoshal** [voutcn/megahit#37]
Hi,

I have downloaded the megahit v0.2.1 and after unpacking when I run the make command I get the following error.

g++ -O3 -Wall -funroll-loops -fprefetch-loop-arrays -fopenmp -std=c++0x -static-libgcc -lm -mpopcnt -c succinct_dbg.cpp -o succinct_dbg.o
cc1plus: error: unrecognized command line option "-std=c++0x"
make: *** [succinct_dbg.o] Error 1

Any help in why this is happening would be awesome and greatly appreciated.

Thanks,

Bibaswan

**Comment by voutcn** [comment]
Hi Bibaswan,

What's your g++ version? Megahit requires g++ version at least 4.

On Tue, Jun 9, 2015 at 6:11 AM, ghoshal <notifications@github.com> wrote:

> Hi,
>
> I have downloaded the megahit v0.2.1 and after unpacking when I run the
> make command I get the following error.
>
> g++ -O3 -Wall -funroll-loops -fprefetch-loop-arrays -fopenmp -std=c++0x
> -static-libgcc -lm -mpopcnt -c succinct_dbg.cpp -o succinct_dbg.o
> cc1plus: error: unrecognized command line option "-std=c++0x"
> make: *** [succinct_dbg.o] Error 1
>
> Any help in why this is happening would be awesome and greatly appreciated.
>
> Thanks,
>
> Bibaswan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/voutcn/megahit/issues/37>.
>



-- 
Sincerely,
Dinghua (a.k.a vout)
email: voutcn@gmail.com

**Comment by ghoshal** [comment]
Hi,

I checked the gcc version. It is gcc version 4.1.2. So technically gcc should not be a problem.

Thanks,

Bibaswan

**Comment by voutcn** [comment]
Sorry, I make a mistake. g++ 4.4 or higher is required.

On Tue, Jun 9, 2015 at 11:42 PM, ghoshal <notifications@github.com> wrote:

> Hi,
>
> I checked the gcc version. It is gcc version 4.1.2. So technically gcc
> should not be a problem.
>
> Thanks,
>
> Bibaswan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/voutcn/megahit/issues/37#issuecomment-110407548>.
>



-- 
Sincerely,
Dinghua (a.k.a vout)
email: voutcn@gmail.com

**Comment by ghoshal** [comment]
Hi,

I updated my gcc to 4.4.7 but still it is giving the same problem. I don't know what is wrong. 

Thanks for your help.

Bibaswan

**Comment by voutcn** [comment]
Hi Bibaswan,

Please run `g++ --version` to make sure that the g++ used to compile is
really the version of 4.4.7. Then run `make clean` before `make`.

If you encounter the problem, please download the binary release directly
https://github.com/voutcn/megahit/releases/tag/v0.2.1-a


On Fri, Jun 12, 2015 at 12:57 AM, ghoshal <notifications@github.com> wrote:

> Hi,
>
> I updated my gcc to 4.4.7 but still it is giving the same problem. I don't
> know what is wrong.
>
> Thanks for your help.
>
> Bibaswan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/voutcn/megahit/issues/37#issuecomment-111206306>.
>



-- 
Sincerely,
Dinghua (a.k.a vout)
email: voutcn@gmail.com

**Comment by ghoshal** [comment]
Hi,

This is the out from the g++ --version

[biba@penguin megahit-0.2.1]$ g++ --version
g++44 (GCC) 4.4.7 20120313 (Red Hat 4.4.7-1)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Still the same error message. I'll try from the binary.

Thanks,

Bibaswan

**Comment by tseemann** [comment]
Although *experimental* ```-std=cx00``` was added in g++ 4.4 I don't think it supported everything properly: https://gcc.gnu.org/projects/cxx0x.html

I think you will need g++ 4.7 based on my experience.

**Comment by voutcn** [comment]
Although g++ 4.4 doesn't support every c++11 features, I can build MEGAHIT with g++ 4.4.7 without any problem in my CentOS server.

**Comment by tseemann** [comment]
@ghoshal You can use Linuxbrew and there is a megahit formula in there to use: https://github.com/Homebrew/linuxbrew

**Comment by little-hunter** [comment]
Dear Voutcn
         I have the same problem and I have down load the binary release from the site https://github.com/voutcn/megahit/releases/tag/v0.2.1-a. Then I found the grammar is different from what you listed in another site (https://github.com/voutcn/megahit). For v0.2.1-a, the grammar is ./megahit [options] -m <max_memory_to_use> -l <max_read_len> {-r <reads.fa> | --input_cmd <command>}. Would results come from v0.2.1-a be the same as the latest version?
