### ISSUE TITLE
source tree is missing citycrc.h

### ISSUE THREAD

**Issue by bjpop** [voutcn/megahit#39]
On line 632 of city.cpp you have:

#ifdef __SSE4_2__
#include <citycrc.h>

However citycrc.h is not in the source tree on github.

Copying the file from the city hash source repo appears to fix the problem: 
https://code.google.com/p/cityhash/source/browse/trunk/src/citycrc.h

If you were expecting city hash to be installed separately then it would be good to mention that in the documentation for the build (though it seems that you don't because you have city.cpp and city.h in the source tree).

Cheers,
Bernie.

**Comment by voutcn** [comment]
Thanks Bernie. The missing file is added.
