### ISSUE TITLE
Error occurs when running "sdbg_builder count/read2sdbg"

### ISSUE THREAD

**Issue by arivers** [voutcn/megahit#47]
I encountered this error running Megahit 0.3.0-beta-3:
MEGAHIT 0.3.0-beta3
--- [Fri Jun 26 11:20:33 2015] Start assembly. Number of CPU threads 16 ---
--- [Fri Jun 26 11:20:33 2015] k list: 31,41,51,61,71,81,91,101,111,121 ---
--- [LIB INFO] interleaved PE reads: unmerged/S.174_CBK.fastq.gz
--- [LIB INFO] interleaved PE reads: unmerged/S.178_YBM.fastq.gz
--- [LIB INFO] interleaved PE reads: unmerged/S.180_BBC.fastq.gz
--- [LIB INFO] interleaved PE reads: unmerged/S.182_BBI.fastq.gz
--- [LIB INFO] interleaved PE reads: unmerged/S.184_BBB.fastq.gz
--- [LIB INFO] interleaved PE reads: unmerged/S.186_BBA.fastq.gz
--- [LIB INFO] interleaved PE reads: unmerged/S.188_CBA.fastq.gz
--- [LIB INFO] interleaved PE reads: unmerged/S.190_CBC.fastq.gz
--- [LIB INFO] interleaved PE reads: unmerged/S.41_BBB.fastq.gz
--- [LIB INFO] interleaved PE reads: unmerged/S.42_YBB.fastq.gz
--- [LIB INFO] interleaved PE reads: unmerged/S.43_YBM.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.174_CBK.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.178_YBM.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.180_BBC.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.182_BBI.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.184_BBB.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.186_BBA.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.188_CBA.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.190_CBC.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.41_BBB.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.42_YBB.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.43_YBM.fastq.gz
--- [Fri Jun 26 11:20:33 2015] Extracting solid (k+1)-mers for k = 31 ---
Error occurs when running "sdbg_builder count/read2sdbg"
[Exit code 255]

The program was run with these settings:
$HOME/lib/megahit-0.3.0-beta3/megahit -r \
merged/S.174_CBK.fastq.gz,\
merged/S.178_YBM.fastq.gz,\
merged/S.180_BBC.fastq.gz,\
merged/S.182_BBI.fastq.gz,\
merged/S.184_BBB.fastq.gz,\
merged/S.186_BBA.fastq.gz,\
merged/S.188_CBA.fastq.gz,\
merged/S.190_CBC.fastq.gz,\
merged/S.41_BBB.fastq.gz,\
merged/S.42_YBB.fastq.gz,\
merged/S.43_YBM.fastq.gz \
--12 unmerged/S.174_CBK.fastq.gz,\
unmerged/S.178_YBM.fastq.gz,\
unmerged/S.180_BBC.fastq.gz,\
unmerged/S.182_BBI.fastq.gz,\
unmerged/S.184_BBB.fastq.gz,\
unmerged/S.186_BBA.fastq.gz,\
unmerged/S.188_CBA.fastq.gz,\
unmerged/S.190_CBC.fastq.gz,\
unmerged/S.41_BBB.fastq.gz,\
unmerged/S.42_YBB.fastq.gz,\
unmerged/S.43_YBM.fastq.gz \
-m 220e9 \
--k-min 31 \
--k-max 121 \
--k-step 10 \
-t 16 \

 Any insight would be appreciated.

**Comment by voutcn** [comment]
Hi Adam,

Would you provide the content of the log file in the output directory? I
guess that the number of reads are too big so that 220G memory is not large
enough to hold them.

Regards,
Dinghua

On Sat, Jun 27, 2015 at 6:09 AM, Adam Rivers <notifications@github.com>
wrote:

> I encountered this error running Megahit 0.3.0-beta-3:
> MEGAHIT 0.3.0-beta3
> --- [Fri Jun 26 11:20:33 2015] Start assembly. Number of CPU threads 16 ---
> --- [Fri Jun 26 11:20:33 2015] k list: 31,41,51,61,71,81,91,101,111,121 ---
> --- [LIB INFO] interleaved PE reads: unmerged/S.174_CBK.fastq.gz
> --- [LIB INFO] interleaved PE reads: unmerged/S.178_YBM.fastq.gz
> --- [LIB INFO] interleaved PE reads: unmerged/S.180_BBC.fastq.gz
> --- [LIB INFO] interleaved PE reads: unmerged/S.182_BBI.fastq.gz
> --- [LIB INFO] interleaved PE reads: unmerged/S.184_BBB.fastq.gz
> --- [LIB INFO] interleaved PE reads: unmerged/S.186_BBA.fastq.gz
> --- [LIB INFO] interleaved PE reads: unmerged/S.188_CBA.fastq.gz
> --- [LIB INFO] interleaved PE reads: unmerged/S.190_CBC.fastq.gz
> --- [LIB INFO] interleaved PE reads: unmerged/S.41_BBB.fastq.gz
> --- [LIB INFO] interleaved PE reads: unmerged/S.42_YBB.fastq.gz
> --- [LIB INFO] interleaved PE reads: unmerged/S.43_YBM.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.174_CBK.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.178_YBM.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.180_BBC.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.182_BBI.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.184_BBB.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.186_BBA.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.188_CBA.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.190_CBC.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.41_BBB.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.42_YBB.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.43_YBM.fastq.gz
> --- [Fri Jun 26 11:20:33 2015] Extracting solid (k+1)-mers for k = 31 ---
> Error occurs when running "sdbg_builder count/read2sdbg"
> [Exit code 255]
>
> The program was run with these settings:
> $HOME/lib/megahit-0.3.0-beta3/megahit -r \
> merged/S.174_CBK.fastq.gz,\
> merged/S.178_YBM.fastq.gz,\
> merged/S.180_BBC.fastq.gz,\
> merged/S.182_BBI.fastq.gz,\
> merged/S.184_BBB.fastq.gz,\
> merged/S.186_BBA.fastq.gz,\
> merged/S.188_CBA.fastq.gz,\
> merged/S.190_CBC.fastq.gz,\
> merged/S.41_BBB.fastq.gz,\
> merged/S.42_YBB.fastq.gz,\
> merged/S.43_YBM.fastq.gz \
> --12 unmerged/S.174_CBK.fastq.gz,\
> unmerged/S.178_YBM.fastq.gz,\
> unmerged/S.180_BBC.fastq.gz,\
> unmerged/S.182_BBI.fastq.gz,\
> unmerged/S.184_BBB.fastq.gz,\
> unmerged/S.186_BBA.fastq.gz,\
> unmerged/S.188_CBA.fastq.gz,\
> unmerged/S.190_CBC.fastq.gz,\
> unmerged/S.41_BBB.fastq.gz,\
> unmerged/S.42_YBB.fastq.gz,\
> unmerged/S.43_YBM.fastq.gz \
> -m 220e9 \
> --k-min 31 \
> --k-max 121 \
> --k-step 10 \
> -t 16 \
>
> Any insight would be appreciated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/voutcn/megahit/issues/47>.
>



-- 
Sincerely,
Dinghua (a.k.a vout)
email: voutcn@gmail.com

**Comment by arivers** [comment]
Hi Dinghua,
Thanks for your help. It does appear to be a memory issue.
Adam

MEGAHIT 0.3.0-beta3
--- [Fri Jun 26 11:20:33 2015] Start assembly. Number of CPU threads 16 ---
--- [Fri Jun 26 11:20:33 2015] k list: 31,41,51,61,71,81,91,101,111,121 ---
--- [LIB INFO] interleaved PE reads: unmerged/S.174_CBK.fastq.gz
--- [LIB INFO] interleaved PE reads: unmerged/S.178_YBM.fastq.gz
--- [LIB INFO] interleaved PE reads: unmerged/S.180_BBC.fastq.gz
--- [LIB INFO] interleaved PE reads: unmerged/S.182_BBI.fastq.gz
--- [LIB INFO] interleaved PE reads: unmerged/S.184_BBB.fastq.gz
--- [LIB INFO] interleaved PE reads: unmerged/S.186_BBA.fastq.gz
--- [LIB INFO] interleaved PE reads: unmerged/S.188_CBA.fastq.gz
--- [LIB INFO] interleaved PE reads: unmerged/S.190_CBC.fastq.gz
--- [LIB INFO] interleaved PE reads: unmerged/S.41_BBB.fastq.gz
--- [LIB INFO] interleaved PE reads: unmerged/S.42_YBB.fastq.gz
--- [LIB INFO] interleaved PE reads: unmerged/S.43_YBM.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.174_CBK.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.178_YBM.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.180_BBC.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.182_BBI.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.184_BBB.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.186_BBA.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.188_CBA.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.190_CBC.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.41_BBB.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.42_YBB.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.43_YBM.fastq.gz
--- [Fri Jun 26 11:20:33 2015] Extracting solid (k+1)-mers for k = 31 ---
cmd: /global/u2/a/arrivers/lib/megahit-0.3.0-beta3/megahit_sdbg_build count -k 31 -m 2 --host_mem 220000000000 --mem_flag 1 --gpu_mem 0 --output_prefix megahit/tmp/k31 --num_cpu_threads 16 --num_output_threads 5 --read_lib_file megahit/tmp/reads.lib
    [sdbg_builder.cpp          : 101]     Host memory to be used: 220000000000
    [sdbg_builder.cpp          : 102]     Number CPU threads: 16
    [cx1.h                     : 313]     Preparing data...
    [cx1_kmer_count.cpp        : 101]     2638008706 reads, 191 max read length
    [cx1_kmer_count.cpp        : 102]     Read libs:
    [cx1_kmer_count.cpp        : 104]     Paired-end: unmerged/S.174_CBK.fastq.gz, 206464790 reads
    [cx1_kmer_count.cpp        : 104]     Paired-end: unmerged/S.178_YBM.fastq.gz, 152562230 reads
    [cx1_kmer_count.cpp        : 104]     Paired-end: unmerged/S.180_BBC.fastq.gz, 100669248 reads
    [cx1_kmer_count.cpp        : 104]     Paired-end: unmerged/S.182_BBI.fastq.gz, 152136796 reads
    [cx1_kmer_count.cpp        : 104]     Paired-end: unmerged/S.184_BBB.fastq.gz, 111605760 reads
    [cx1_kmer_count.cpp        : 104]     Paired-end: unmerged/S.186_BBA.fastq.gz, 101075106 reads
    [cx1_kmer_count.cpp        : 104]     Paired-end: unmerged/S.188_CBA.fastq.gz, 170176106 reads
    [cx1_kmer_count.cpp        : 104]     Paired-end: unmerged/S.190_CBC.fastq.gz, 157577176 reads
    [cx1_kmer_count.cpp        : 104]     Paired-end: unmerged/S.41_BBB.fastq.gz, 275478662 reads
    [cx1_kmer_count.cpp        : 104]     Paired-end: unmerged/S.42_YBB.fastq.gz, 350086598 reads
    [cx1_kmer_count.cpp        : 104]     Paired-end: unmerged/S.43_YBM.fastq.gz, 334900366 reads
    [cx1_kmer_count.cpp        : 104]     Single-end: merged/S.174_CBK.fastq.gz, 76280234 reads
    [cx1_kmer_count.cpp        : 104]     Single-end: merged/S.178_YBM.fastq.gz, 71592929 reads
    [cx1_kmer_count.cpp        : 104]     Single-end: merged/S.180_BBC.fastq.gz, 56122543 reads
    [cx1_kmer_count.cpp        : 104]     Single-end: merged/S.182_BBI.fastq.gz, 57131214 reads
    [cx1_kmer_count.cpp        : 104]     Single-end: merged/S.184_BBB.fastq.gz, 59967882 reads
    [cx1_kmer_count.cpp        : 104]     Single-end: merged/S.186_BBA.fastq.gz, 43893504 reads
    [cx1_kmer_count.cpp        : 104]     Single-end: merged/S.188_CBA.fastq.gz, 68513136 reads
    [cx1_kmer_count.cpp        : 104]     Single-end: merged/S.190_CBC.fastq.gz, 76252178 reads
    [cx1_kmer_count.cpp        : 104]     Single-end: merged/S.41_BBB.fastq.gz, clean.sh              megahit2               megahit4.sh.pe9109325
cleaned               megahit2.sh            megahit4.sh.po9109325
MEGAHIT 0.3.0-beta3
--- [Fri Jun 26 11:20:33 2015] Start assembly. Number of CPU threads 16 ---
--- [Fri Jun 26 11:20:33 2015] k list: 31,41,51,61,71,81,91,101,111,121 ---
--- [LIB INFO] interleaved PE reads: unmerged/S.174_CBK.fastq.gz
--- [LIB INFO] interleaved PE reads: unmerged/S.178_YBM.fastq.gz
--- [LIB INFO] interleaved PE reads: unmerged/S.180_BBC.fastq.gz
--- [LIB INFO] interleaved PE reads: unmerged/S.182_BBI.fastq.gz
--- [LIB INFO] interleaved PE reads: unmerged/S.184_BBB.fastq.gz
--- [LIB INFO] interleaved PE reads: unmerged/S.186_BBA.fastq.gz
--- [LIB INFO] interleaved PE reads: unmerged/S.188_CBA.fastq.gz
--- [LIB INFO] interleaved PE reads: unmerged/S.190_CBC.fastq.gz
--- [LIB INFO] interleaved PE reads: unmerged/S.41_BBB.fastq.gz
--- [LIB INFO] interleaved PE reads: unmerged/S.42_YBB.fastq.gz
--- [LIB INFO] interleaved PE reads: unmerged/S.43_YBM.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.174_CBK.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.178_YBM.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.180_BBC.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.182_BBI.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.184_BBB.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.186_BBA.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.188_CBA.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.190_CBC.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.41_BBB.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.42_YBB.fastq.gz
--- [LIB INFO] Single-end reads: merged/S.43_YBM.fastq.gz
--- [Fri Jun 26 11:20:33 2015] Extracting solid (k+1)-mers for k = 31 ---
cmd: /global/u2/a/arrivers/lib/megahit-0.3.0-beta3/megahit_sdbg_build count -k 31 -m 2 --host_mem 220000000000 --mem_flag 1 --gpu_mem 0 --output_prefix megahit/tmp/k31 --num_cpu_threads 16 --num_output_threads 5 --read_lib_file megahit/tmp/reads.lib
    [sdbg_builder.cpp          : 101]     Host memory to be used: 220000000000
    [sdbg_builder.cpp          : 102]     Number CPU threads: 16
    [cx1.h                     : 313]     Preparing data...
    [cx1_kmer_count.cpp        : 101]     2638008706 reads, 191 max read length
    [cx1_kmer_count.cpp        : 102]     Read libs:
    [cx1_kmer_count.cpp        : 104]     Paired-end: unmerged/S.174_CBK.fastq.gz, 206464790 reads
    [cx1_kmer_count.cpp        : 104]     Paired-end: unmerged/S.178_YBM.fastq.gz, 152562230 reads
    [cx1_kmer_count.cpp        : 104]     Paired-end: unmerged/S.180_BBC.fastq.gz, 100669248 reads
    [cx1_kmer_count.cpp        : 104]     Paired-end: unmerged/S.182_BBI.fastq.gz, 152136796 reads
    [cx1_kmer_count.cpp        : 104]     Paired-end: unmerged/S.184_BBB.fastq.gz, 111605760 reads
    [cx1_kmer_count.cpp        : 104]     Paired-end: unmerged/S.186_BBA.fastq.gz, 101075106 reads
    [cx1_kmer_count.cpp        : 104]     Paired-end: unmerged/S.188_CBA.fastq.gz, 170176106 reads
    [cx1_kmer_count.cpp        : 104]     Paired-end: unmerged/S.190_CBC.fastq.gz, 157577176 reads
    [cx1_kmer_count.cpp        : 104]     Paired-end: unmerged/S.41_BBB.fastq.gz, 275478662 reads
    [cx1_kmer_count.cpp        : 104]     Paired-end: unmerged/S.42_YBB.fastq.gz, 350086598 reads
    [cx1_kmer_count.cpp        : 104]     Paired-end: unmerged/S.43_YBM.fastq.gz, 334900366 reads
    [cx1_kmer_count.cpp        : 104]     Single-end: merged/S.174_CBK.fastq.gz, 76280234 reads
    [cx1_kmer_count.cpp        : 104]     Single-end: merged/S.178_YBM.fastq.gz, 71592929 reads
    [cx1_kmer_count.cpp        : 104]     Single-end: merged/S.180_BBC.fastq.gz, 56122543 reads
    [cx1_kmer_count.cpp        : 104]     Single-end: merged/S.182_BBI.fastq.gz, 57131214 reads
    [cx1_kmer_count.cpp        : 104]     Single-end: merged/S.184_BBB.fastq.gz, 59967882 reads
    [cx1_kmer_count.cpp        : 104]     Single-end: merged/S.186_BBA.fastq.gz, 43893504 reads
    [cx1_kmer_count.cpp        : 104]     Single-end: merged/S.188_CBA.fastq.gz, 68513136 reads
    [cx1_kmer_count.cpp        : 104]     Single-end: merged/S.190_CBC.fastq.gz, 76252178 reads
    [cx1_kmer_count.cpp        : 104]     Single-end: merged/S.41_BBB.fastq.gz, 5694059 reads
    [cx1_kmer_count.cpp        : 104]     Single-end: merged/S.42_YBB.fastq.gz, 4680482 reads
    [cx1_kmer_count.cpp        : 104]     Single-end: merged/S.43_YBM.fastq.gz, 5147707 reads
    [cx1.h                     : 320]     Preparing data... Done. Time elapsed: 6217.5594
    [cx1.h                     : 327]     Preparing partitions and initialing global data...
    [cx1_kmer_count.cpp        : 191]     2 words per substring, 3 words per edge
    [cx1_kmer_count.cpp        : 224]     Memory for reads: 91067429044
    [cx1_kmer_count.cpp        : 225]     max # lv.1 items = 26415623028
    [cx1_kmer_count.cpp        : 226]     max # lv.2 items = 42922785
[ERROR] Ran out of memory while applying 105662492112bytes
In file: cx1_kmer_count.cpp, line 230
There may be errors as follows:
1) Not enough memory.
2) The ARRAY may be overrode.
3) The wild pointers.
    [utils.h                   : 114]     Real: 6476.5651       user: 4934.5708 sys: 272.4196   maxrss: 154543204
Error occurs when running "sdbg_builder count/read2sdbg"
[Exit code 255]

**Comment by voutcn** [comment]
Hi Adam,

May I ask how much memory does your server have? It seems that 220e9 is
quite closed to your memory capacity. I suggest you leave -m default or set
a smaller one say 180e9.

On Sat, Jun 27, 2015 at 11:58 PM, Adam Rivers <notifications@github.com>
wrote:

> Hi Dinghua,
> Thanks for your help. It does appear to be a memory issue.
> Adam
>
> MEGAHIT 0.3.0-beta3
> --- [Fri Jun 26 11:20:33 2015] Start assembly. Number of CPU threads 16 ---
> --- [Fri Jun 26 11:20:33 2015] k list: 31,41,51,61,71,81,91,101,111,121 ---
> --- [LIB INFO] interleaved PE reads: unmerged/S.174_CBK.fastq.gz
> --- [LIB INFO] interleaved PE reads: unmerged/S.178_YBM.fastq.gz
> --- [LIB INFO] interleaved PE reads: unmerged/S.180_BBC.fastq.gz
> --- [LIB INFO] interleaved PE reads: unmerged/S.182_BBI.fastq.gz
> --- [LIB INFO] interleaved PE reads: unmerged/S.184_BBB.fastq.gz
> --- [LIB INFO] interleaved PE reads: unmerged/S.186_BBA.fastq.gz
> --- [LIB INFO] interleaved PE reads: unmerged/S.188_CBA.fastq.gz
> --- [LIB INFO] interleaved PE reads: unmerged/S.190_CBC.fastq.gz
> --- [LIB INFO] interleaved PE reads: unmerged/S.41_BBB.fastq.gz
> --- [LIB INFO] interleaved PE reads: unmerged/S.42_YBB.fastq.gz
> --- [LIB INFO] interleaved PE reads: unmerged/S.43_YBM.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.174_CBK.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.178_YBM.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.180_BBC.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.182_BBI.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.184_BBB.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.186_BBA.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.188_CBA.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.190_CBC.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.41_BBB.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.42_YBB.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.43_YBM.fastq.gz
> --- [Fri Jun 26 11:20:33 2015] Extracting solid (k+1)-mers for k = 31 ---
> cmd: /global/u2/a/arrivers/lib/megahit-0.3.0-beta3/megahit_sdbg_build
> count -k 31 -m 2 --host_mem 220000000000 --mem_flag 1 --gpu_mem 0
> --output_prefix megahit/tmp/k31 --num_cpu_threads 16 --num_output_threads 5
> --read_lib_file megahit/tmp/reads.lib
> [sdbg_builder.cpp : 101] Host memory to be used: 220000000000
> [sdbg_builder.cpp : 102] Number CPU threads: 16
> [cx1.h : 313] Preparing data...
> [cx1_kmer_count.cpp : 101] 2638008706 reads, 191 max read length
> [cx1_kmer_count.cpp : 102] Read libs:
> [cx1_kmer_count.cpp : 104] Paired-end: unmerged/S.174_CBK.fastq.gz,
> 206464790 reads
> [cx1_kmer_count.cpp : 104] Paired-end: unmerged/S.178_YBM.fastq.gz,
> 152562230 reads
> [cx1_kmer_count.cpp : 104] Paired-end: unmerged/S.180_BBC.fastq.gz,
> 100669248 reads
> [cx1_kmer_count.cpp : 104] Paired-end: unmerged/S.182_BBI.fastq.gz,
> 152136796 reads
> [cx1_kmer_count.cpp : 104] Paired-end: unmerged/S.184_BBB.fastq.gz,
> 111605760 reads
> [cx1_kmer_count.cpp : 104] Paired-end: unmerged/S.186_BBA.fastq.gz,
> 101075106 reads
> [cx1_kmer_count.cpp : 104] Paired-end: unmerged/S.188_CBA.fastq.gz,
> 170176106 reads
> [cx1_kmer_count.cpp : 104] Paired-end: unmerged/S.190_CBC.fastq.gz,
> 157577176 reads
> [cx1_kmer_count.cpp : 104] Paired-end: unmerged/S.41_BBB.fastq.gz,
> 275478662 reads
> [cx1_kmer_count.cpp : 104] Paired-end: unmerged/S.42_YBB.fastq.gz,
> 350086598 reads
> [cx1_kmer_count.cpp : 104] Paired-end: unmerged/S.43_YBM.fastq.gz,
> 334900366 reads
> [cx1_kmer_count.cpp : 104] Single-end: merged/S.174_CBK.fastq.gz, 76280234
> reads
> [cx1_kmer_count.cpp : 104] Single-end: merged/S.178_YBM.fastq.gz, 71592929
> reads
> [cx1_kmer_count.cpp : 104] Single-end: merged/S.180_BBC.fastq.gz, 56122543
> reads
> [cx1_kmer_count.cpp : 104] Single-end: merged/S.182_BBI.fastq.gz, 57131214
> reads
> [cx1_kmer_count.cpp : 104] Single-end: merged/S.184_BBB.fastq.gz, 59967882
> reads
> [cx1_kmer_count.cpp : 104] Single-end: merged/S.186_BBA.fastq.gz, 43893504
> reads
> [cx1_kmer_count.cpp : 104] Single-end: merged/S.188_CBA.fastq.gz, 68513136
> reads
> [cx1_kmer_count.cpp : 104] Single-end: merged/S.190_CBC.fastq.gz, 76252178
> reads
> [cx1_kmer_count.cpp : 104] Single-end: merged/S.41_BBB.fastq.gz, clean.sh
> megahit2 megahit4.sh.pe9109325
> cleaned megahit2.sh megahit4.sh.po9109325
>
> MEGAHIT 0.3.0-beta3
> --- [Fri Jun 26 11:20:33 2015] Start assembly. Number of CPU threads 16 ---
> --- [Fri Jun 26 11:20:33 2015] k list: 31,41,51,61,71,81,91,101,111,121 ---
> --- [LIB INFO] interleaved PE reads: unmerged/S.174_CBK.fastq.gz
> --- [LIB INFO] interleaved PE reads: unmerged/S.178_YBM.fastq.gz
> --- [LIB INFO] interleaved PE reads: unmerged/S.180_BBC.fastq.gz
> --- [LIB INFO] interleaved PE reads: unmerged/S.182_BBI.fastq.gz
> --- [LIB INFO] interleaved PE reads: unmerged/S.184_BBB.fastq.gz
> --- [LIB INFO] interleaved PE reads: unmerged/S.186_BBA.fastq.gz
> --- [LIB INFO] interleaved PE reads: unmerged/S.188_CBA.fastq.gz
> --- [LIB INFO] interleaved PE reads: unmerged/S.190_CBC.fastq.gz
> --- [LIB INFO] interleaved PE reads: unmerged/S.41_BBB.fastq.gz
> --- [LIB INFO] interleaved PE reads: unmerged/S.42_YBB.fastq.gz
> --- [LIB INFO] interleaved PE reads: unmerged/S.43_YBM.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.174_CBK.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.178_YBM.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.180_BBC.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.182_BBI.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.184_BBB.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.186_BBA.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.188_CBA.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.190_CBC.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.41_BBB.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.42_YBB.fastq.gz
> --- [LIB INFO] Single-end reads: merged/S.43_YBM.fastq.gz
> --- [Fri Jun 26 11:20:33 2015] Extracting solid (k+1)-mers for k = 31 ---
> cmd: /global/u2/a/arrivers/lib/megahit-0.3.0-beta3/megahit_sdbg_build
> count -k 31 -m 2 --host_mem 220000000000 --mem_flag 1 --gpu_mem 0
> --output_prefix megahit/tmp/k31 --num_cpu_threads 16 --num_output_threads 5
> --read_lib_file megahit/tmp/reads.lib
> [sdbg_builder.cpp : 101] Host memory to be used: 220000000000
> [sdbg_builder.cpp : 102] Number CPU threads: 16
> [cx1.h : 313] Preparing data...
> [cx1_kmer_count.cpp : 101] 2638008706 reads, 191 max read length
> [cx1_kmer_count.cpp : 102] Read libs:
> [cx1_kmer_count.cpp : 104] Paired-end: unmerged/S.174_CBK.fastq.gz,
> 206464790 reads
> [cx1_kmer_count.cpp : 104] Paired-end: unmerged/S.178_YBM.fastq.gz,
> 152562230 reads
> [cx1_kmer_count.cpp : 104] Paired-end: unmerged/S.180_BBC.fastq.gz,
> 100669248 reads
> [cx1_kmer_count.cpp : 104] Paired-end: unmerged/S.182_BBI.fastq.gz,
> 152136796 reads
> [cx1_kmer_count.cpp : 104] Paired-end: unmerged/S.184_BBB.fastq.gz,
> 111605760 reads
> [cx1_kmer_count.cpp : 104] Paired-end: unmerged/S.186_BBA.fastq.gz,
> 101075106 reads
> [cx1_kmer_count.cpp : 104] Paired-end: unmerged/S.188_CBA.fastq.gz,
> 170176106 reads
> [cx1_kmer_count.cpp : 104] Paired-end: unmerged/S.190_CBC.fastq.gz,
> 157577176 reads
> [cx1_kmer_count.cpp : 104] Paired-end: unmerged/S.41_BBB.fastq.gz,
> 275478662 reads
> [cx1_kmer_count.cpp : 104] Paired-end: unmerged/S.42_YBB.fastq.gz,
> 350086598 reads
> [cx1_kmer_count.cpp : 104] Paired-end: unmerged/S.43_YBM.fastq.gz,
> 334900366 reads
> [cx1_kmer_count.cpp : 104] Single-end: merged/S.174_CBK.fastq.gz, 76280234
> reads
> [cx1_kmer_count.cpp : 104] Single-end: merged/S.178_YBM.fastq.gz, 71592929
> reads
> [cx1_kmer_count.cpp : 104] Single-end: merged/S.180_BBC.fastq.gz, 56122543
> reads
> [cx1_kmer_count.cpp : 104] Single-end: merged/S.182_BBI.fastq.gz, 57131214
> reads
> [cx1_kmer_count.cpp : 104] Single-end: merged/S.184_BBB.fastq.gz, 59967882
> reads
> [cx1_kmer_count.cpp : 104] Single-end: merged/S.186_BBA.fastq.gz, 43893504
> reads
> [cx1_kmer_count.cpp : 104] Single-end: merged/S.188_CBA.fastq.gz, 68513136
> reads
> [cx1_kmer_count.cpp : 104] Single-end: merged/S.190_CBC.fastq.gz, 76252178
> reads
> [cx1_kmer_count.cpp : 104] Single-end: merged/S.41_BBB.fastq.gz, 5694059
> reads
> [cx1_kmer_count.cpp : 104] Single-end: merged/S.42_YBB.fastq.gz, 4680482
> reads
> [cx1_kmer_count.cpp : 104] Single-end: merged/S.43_YBM.fastq.gz, 5147707
> reads
> [cx1.h : 320] Preparing data... Done. Time elapsed: 6217.5594
> [cx1.h : 327] Preparing partitions and initialing global data...
> [cx1_kmer_count.cpp : 191] 2 words per substring, 3 words per edge
> [cx1_kmer_count.cpp : 224] Memory for reads: 91067429044
> [cx1_kmer_count.cpp : 225] max # lv.1 items = 26415623028
> [cx1_kmer_count.cpp : 226] max # lv.2 items = 42922785
> [ERROR] Ran out of memory while applying 105662492112bytes
> In file: cx1_kmer_count.cpp, line 230
> There may be errors as follows:
> 1) Not enough memory.
> 2) The ARRAY may be overrode.
> 3) The wild pointers.
> [utils.h : 114] Real: 6476.5651 user: 4934.5708 sys: 272.4196 maxrss:
> 154543204
> Error occurs when running "sdbg_builder count/read2sdbg"
> [Exit code 255]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/voutcn/megahit/issues/47#issuecomment-116091448>.
>



-- 
Sincerely,
Dinghua (a.k.a vout)
email: voutcn@gmail.com

**Comment by arivers** [comment]
The node I used has 248GB.

**Comment by voutcn** [comment]
I see. Please use -m 180e9 as temporary solution.

On Sun, Jun 28, 2015 at 12:11 AM, Adam Rivers <notifications@github.com>
wrote:

> The node I used has 248GB.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/voutcn/megahit/issues/47#issuecomment-116092109>.
>



-- 
Sincerely,
Dinghua (a.k.a vout)
email: voutcn@gmail.com

**Comment by voutcn** [comment]
Hi Adam,

Not sure whether you've successfully assembled your reads. The last commit should work with `-m 220e9` (as well as the default setting).

**Comment by arivers** [comment]
Letting the program set -m automatically and switching to a 1TB memory node solved this.
