### ISSUE TITLE
Is multi-threaded megahit deterministic?

### ISSUE THREAD

**Issue by tseemann** [voutcn/megahit#48]
If I run megahit multiple times with 64 threads say, will I get a different assembly result?

ie. is the algorithm deterministic?

(Velvet was **not** deterministic in scaffolding PE reads, but gave similar results)

**Comment by voutcn** [comment]
It will give *almost* identical results. The only difference is the looped contigs; MEGAHIT will break a looped contig at an arbitrary point.

**Comment by tseemann** [comment]
Thanks for the response!
