### ISSUE TITLE
0.3.2b - error occurs when running "sdbg_builder count/read2sdbg"

### ISSUE THREAD

**Issue by tseemann** [voutcn/megahit#52]
I'm using latest git 0.3.2b and it seems to be spawning the *old* binary name?

```
--- [Sat Jul  4 11:46:34 2015] Extracting solid (k+1)-mers for k = 21 ---
Error occurs when running "sdbg_builder count/read2sdbg", please refer to ./megahit_out/log for detail
```

Should be `megahit_sdbg_build count` ?

**Comment by voutcn** [comment]
Noted this and will draft a new release today.

**Comment by voutcn** [comment]
Fixed by this commit https://github.com/voutcn/megahit/commit/b177c734a575b9f0e5cff43e9e115e6a189c63ac.

**Comment by tseemann** [comment]
Thanks - seems to work with 0.3.3 release now!
