### ISSUE TITLE
Error when running "sdbg_builder count/read2sdbg"

### ISSUE THREAD

**Issue by miasteinberg** [voutcn/megahit#55]
I'm using v.0.3.3-a on a node with 128 GB RAM and get this error. I saw that there were a few other issues with this step, but the new version update didn't seem to help for me. Any idea what this error is about?

MEGAHIT v0.3.3-a
--- [Mon Jul 20 13:43:28 2015] Start assembly. Number of CPU threads 64 ---
--- [Mon Jul 20 13:43:28 2015] k list: 21,41,61,81,99 ---
--- [Mon Jul 20 13:43:28 2015] Converting reads to binaries ---
/p/home/mstein/tools/megahit_v0.3.3-a/megahit_asm_core buildlib ./megahit_out/tmp/reads.lib ./megahit_out/tmp/reads.lib
    [read_lib_functions-inl.h  : 194]     Lib 0 (ALAn-2A_R1.trim.fastq.gz,ALAn-2A_R2.trim.fastq.gz): pe, 74864708 reads, 101 max length
    [utils.h                   : 114]     Real: 80.5623 user: 51.8952   sys: 4.7203     maxrss: 153216
--- [Mon Jul 20 13:44:49 2015] Extracting solid (k+1)-mers for k = 21 ---
cmd: /p/home/mstein/tools/megahit_v0.3.3-a/megahit_sdbg_build count -k 21 -m 2 --host_mem 121800974745 --mem_flag 1 --gpu_mem 0 --output_prefix ./megahit
_out/tmp/k21 --num_cpu_threads 64 --num_output_threads 21 --read_lib_file ./megahit_out/tmp/reads.lib
    [sdbg_builder.cpp          : 102]     Host memory to be used: 121800974745
    [sdbg_builder.cpp          : 103]     Number CPU threads: 64
    [cx1.h                     : 313]     Preparing data...
    [cx1_kmer_count.cpp        : 101]     74864708 reads, 101 max read length
    [cx1.h                     : 320]     Preparing data... Done. Time elapsed: 10.1978
    [cx1.h                     : 327]     Preparing partitions and initialing global data...
    [cx1_kmer_count.cpp        : 195]     2 words per substring, 2 words per edge
    [cx1_kmer_count.cpp        : 228]     Memory for reads: 2470583652
    [cx1_kmer_count.cpp        : 229]     max # lv.1 items = 788624446
    [cx1_kmer_count.cpp        : 230]     max # lv.2 items = 3809570
    [cx1.h                     : 339]     Preparing partitions and initialing global data... Done. Time elapsed: 2.6485
    [cx1.h                     : 345]     Start main loop...
    [cx1.h                     : 366]     Lv1 scanning from bucket 0 to 3359
    [cx1.h                     : 378]     Lv1 scanning done. Large diff: 0. Time elapsed: 2.6994
Error occurs when running "sdbg_builder count/read2sdbg", please refer to ./megahit_out/log for detail
[Exit code -11]

**Comment by voutcn** [comment]
I've never seen such error before. It looks like segmentation fault at the sorting stage.
To dig out what is happening, I have to use your data to reproduce the error. Is it convinient for you to share the data with me?

**Comment by voutcn** [comment]
You could also try the latest commit in the [`dev` branch](https://github.com/voutcn/megahit/tree/dev), which has a totally new algorithm design.

**Comment by voutcn** [comment]
I draft a new release, please try https://github.com/voutcn/megahit/releases/tag/v1.0.0-beta

**Comment by miasteinberg** [comment]
That did the trick! Thank you!

**Comment by elliot-sawyer** [comment]
I ran into this error when providing megahit (v1.0.6) with 60GB of memory. I decreased to `--memory 0.25` and the program worked after that.
