### ISSUE TITLE
250bp PE Miseq reads assembly k-max ?

### ISSUE THREAD

**Issue by eamorin** [voutcn/megahit#57]
Hello,

I'm working on soil metagenomic data, I've 250bp PE Miseq reads to assemble. After trimming the average length is 190 bp.
I have performed an assembly with --k-min 27 --k-max 127 --k-step 10.

I have 2 questions:

- is K-max 127 long enough in this case ? is there a "rule" to determine k-max ?
- can we set k-max to a higher value ? does it make any sense ?

Thanks for your help,

**Comment by chuckpr** [comment]
+1 I am curious about this myself as many of our 2x150 reads can be merged before assembly.

**Comment by voutcn** [comment]
> is K-max 127 long enough in this case ? is there a "rule" to determine k-max ?

Honestly, I am not sure. Basically, I would not recommend setting k to larger than 100, unless the sequencing depth is very high (some single-cell data can be > 1000x). Roughly speaking, the error rate of HiSeq is about 1%, when k goes as large as 100, you may rarely see any correct kmers from reads.

However, I don't have much experience with MiSeq. So I leave this issue open here for more discussion.

> can we set k-max to a higher value ? does it make any sense ?

As I know the A5-Miseq pipeline makes use of very large k-mer size for MiSeq data. So I think probably it makes sense, but you still had to try and compare before going ahead.

To use larger k value. Two files should be modified

* modify `kMaxK ` to the value you want at https://github.com/voutcn/megahit/blob/master/definitions.h#L56 

* modify the `> 127` to the k-max you want at https://github.com/voutcn/megahit/blob/master/megahit#L374

**Comment by chuckpr** [comment]
Thanks, I'll give it a shot.

If I change the ```--k-max``` value in the ```opts.txt``` file and run ```megahit``` with the ```--continue``` flag can I start an assembly where a previous assembly left off? This would be a quick way to see if k > 127 helps with my data. Thanks again!

**Comment by voutcn** [comment]
@chuckpr No, you have to rerun it from the beginning. You can let k-max go as large as you want, and then evaluate the contigs assembled from different k in `intermediate_contigs/k*.contigs.fa`

**Comment by jvollme** [comment]
> Honestly, I am not sure. Basically, I would not recommend setting k to larger than 100, unless the sequencing depth is very high

But I thought there is an iterative read correction beginning at lower kmer steps (I thought that was one of the points of doing assemblies using iterative kmer sizes)? Shouldn't that remove most such errors before you reach the high kmers? 
For Miseq Data of up to 300bp l got huge improvements (concerning N50 and maximum contig length) with IDBA_UD after modifying it to allow kmer lengths upto 251 bp. I am really looking forward to trying this with megahit as megahit is far more user friendly.

**Comment by jvollme** [comment]
But I have a question regarding the exact modification for megahit:
The first is straigntforward. But what do I have to change here:

> modify the > 127 to the k-max you want at https://github.com/voutcn/megahit/blob/master/megahit#L374

Can't find the value I am supposed to change here.

**Comment by voutcn** [comment]
@jvollme if you are using the latest codes, simple change the value `kMaxK` in `definitions.h` works.

**Comment by jvollme** [comment]
Thanks!
Maybe you could mention that info in your manual or readme somewehere? I think this info might be interesting for a number of people also but may be hard to find (even though Megahit is quite well documented otherwise).
