### ISSUE TITLE
"builder build" error: 'std::bad_alloc'

### ISSUE THREAD

**Issue by xvazquezc** [voutcn/megahit#58]
Hi,
I've been trying to run Megahit with the following parameters:
megahit -m 92e9 --k-min 27 --k-max 127 --k-step 10 -o megahitout --continue \
-1 [list of R1 libraries] \
-2 [list of R2 libraries]

I allocate 16 processes and 96 GB memory for this in our cluster
But I get  'std::bad_alloc' error when it tries the k27. Any idea why?

See the ending of the log below
--- [Fri Oct  2 17:42:55 2015] Building graph for k = 27 ---
/home/z3382651/bin/megahit/megahit_sdbg_build seq2sdbg --host_mem 70000000000 --mem_flag 1 --gpu_mem 0 --output_prefix megahitout/tmp/k27/27 --num_cpu_threads 16 -k 27 --kmer_from 0 --num_edge_files 5 --input_prefix megahitout/tmp/k27/27 --need_mercy
    [sdbg_builder.cpp          : 341]     Host memory to be used: 70000000000
    [sdbg_builder.cpp          : 342]     Number CPU threads: 16
    [cx1.h                     : 450]     Preparing data...
    [cx1_seq2sdbg.cpp          : 406]     Number edges: 6770942229
    [cx1_seq2sdbg.cpp          : 446]     Bases to reserve: 236982978008, number contigs: 0, number multiplicity: 8463677786
    [cx1_seq2sdbg.cpp          : 452]     Before reading, sizeof seq_package: 59245744512, multiplicity vector: 8463677786
    [cx1_seq2sdbg.cpp          : 467]     Adding mercy edges...
terminate called after throwing an instance of 'St9bad_alloc'
  what():  std::bad_alloc
Error occurs when running "builder build" for k = 27; please refer to megahitout/log for detail
[Exit code -6]
MEGAHIT v1.0.2
--- [Wed Oct  7 01:29:17 2015] Start assembly. Number of CPU threads 16 ---
--- [Wed Oct  7 01:29:17 2015] k list: 27,37,47,57,67,77,87,97,107,117,127 ---
--- [Wed Oct  7 01:29:17 2015] Building graph for k = 27 ---
/home/z3382651/bin/megahit/megahit_sdbg_build seq2sdbg --host_mem 70000000000 --mem_flag 1 --gpu_mem 0 --output_prefix megahitout/tmp/k27/27 --num_cpu_threads 16 -k 27 --kmer_from 0 --num_edge_files 5 --input_prefix megahitout/tmp/k27/27 --need_mercy
    [sdbg_builder.cpp          : 341]     Host memory to be used: 70000000000
    [sdbg_builder.cpp          : 342]     Number CPU threads: 16
    [cx1.h                     : 450]     Preparing data...
    [cx1_seq2sdbg.cpp          : 406]     Number edges: 6770942229
    [cx1_seq2sdbg.cpp          : 446]     Bases to reserve: 236982978008, number contigs: 0, number multiplicity: 8463677786
    [cx1_seq2sdbg.cpp          : 452]     Before reading, sizeof seq_package: 59245744512, multiplicity vector: 8463677786
    [cx1_seq2sdbg.cpp          : 467]     Adding mercy edges...
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Error occurs when running "builder build" for k = 27; please refer to megahitout/log for detail
[Exit code -6]

**Comment by voutcn** [comment]
@xvazquezc It seems that the memory is insufficient. Running MEGAHIT with `--kmin-1pass` option may help.

It is also strange that you've set `-m` to 92e9, but the subprogram uses 70e9 memory only. Could you attach the complete log for my inspection?

**Comment by xvazquezc** [comment]
mm for some reason I get an error attaching the file even with the right extension. Check the link for the log. Thanks

https://drive.google.com/file/d/0ByeVFWM8YnItdTE1SmhCNWl3NXM/view?usp=sharing

**Comment by voutcn** [comment]
Thanks. I believe that with `--kmin-1pass` option it will work.
BTW, could you also provide `opts.txt` in the output directory?

**Comment by xvazquezc** [comment]
Thanks, I will try with '--min-1pass' and setting '-m' to 70e9

Here you are:

https://drive.google.com/file/d/0ByeVFWM8YnItLWVSUDNhRldNS3c/view?usp=sharing

**Comment by voutcn** [comment]
Okay. It seems that you've set `-m` to 70e9 instead of 92e9 in your first experiment. I guess 70e9 should be okay, but a higher value (but no more than 95% of your machine's memory) is recommended.

**Comment by xvazquezc** [comment]
It failed again so I decided to delete all the files generated by the previous runs and now works and even resumes the job after time out from server without problem.
Thanks
