### ISSUE TITLE
error while compiling extract_pe_reads.cpp 

### ISSUE THREAD

**Issue by wdeleeuw** [voutcn/megahit#60]
Trying to make on Centos release 6.7 system: 
everything "makes" fine (megahit/megahit_asm_core/megahit_sdbg_build are all build)
make megahit_toolkit breaks on the compilation of tools/extract_pe_reads.cpp

g++ -g -O2 -Wall -Wno-unused-function -Wno-array-bounds -D__STDC_FORMAT_MACROS -funroll-loops -fprefetch-loop-arrays -fopenmp -I. -std=c++0x -static-libgcc -m64 -mpopcnt -DPACKAGE_VERSION="\"v1.0.3-5-g2efa1ec\"" tools/toolkit.cpp tools/contigs_to_fastg.cpp tools/read_stat.cpp tools/trim_low_qual_tail.cpp tools/filter_by_len.cpp tools/extract_pe_reads.cpp -lm -lz -lpthread -o megahit_toolkit
tools/extract_pe_reads.cpp: In function ‘int main_extract_pe(int, char**)’:
tools/extract_pe_reads.cpp:106: error: expected initializer before ‘:’ token
tools/extract_pe_reads.cpp:110: error: could not convert ‘kseq_destroy(seq)’ to ‘bool’
tools/extract_pe_reads.cpp:111: error: expected ‘)’ before ‘;’ token
make: *** [megahit_toolkit] Error 1

I'm running: g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)

**Comment by voutcn** [comment]
@wdeleeuw Thanks for reporting the issue. It is fixed now.

**Comment by wdeleeuw** [comment]
Hi Dinghua Li,

Thank you for your fast reaction. It compiles OK now.

Wim
