### ISSUE TITLE
Error 9

### ISSUE THREAD

**Issue by atfric** [voutcn/megahit#61]
I am restarting calculations from version 1.0.2 now with version 1.0.3. 
Is it possible that the relase 1.0.3 is tackling the "Error 9", which I had several times to fight with in a 17 Samples assembly with 17*90 MegaReads on a 512GB Ram Server ?

**Comment by voutcn** [comment]
Not sure. Could you attach your log? "Error 9" means your progress got killed (probably by your system admin?).

**Comment by atfric** [comment]
Than its possible that the OOM-kill shut the program down due to over-swap condition. Do you suggest then to go in smaller steps from kmin to kmax, setting -m smaller at the same time?

**Comment by voutcn** [comment]
Smaller step will not work. -m smaller might work.

**Comment by voutcn** [comment]
BTW, how big is your data (# of reads & total bp)?

**Comment by atfric** [comment]
its 1.5 Giga reads, max 150bp PE. 
The funny thing is that a much bigger set was aseembled succsessfully with 1.0.2 version. 
With -m option and smaller memory-requested I still ended in swap space. 
Is there a new memory-leak in 1.0.3?
Smaller k-step (10) succeeded with version 1.0.3.

**Comment by atfric** [comment]
Here a log before the Error 9
MEGAHIT v1.0.3
--- [Wed Nov 18 12:55:13 2015] Start assembly. Number of CPU threads 20 ---
--- [Wed Nov 18 12:55:13 2015] k list: 21,41,61,81,99 ---
--- [Wed Nov 18 12:55:13 2015] Converting reads to binaries ---
/opt/bio/megahit-1.0.3/megahit_asm_core buildlib Ant_17samples_20/tmp/reads.lib Ant_17samples_20/tmp/reads.lib
    [read_lib_functions-inl.h  : 209]     Lib 0 (./Ant_7/8176.5.92486.CGATGT.anqrpt.fastq.gz): interleaved, 78307480 reads, 150 max length
    [read_lib_functions-inl.h  : 209]     Lib 1 (./Ant_4/8176.5.92486.ATCACG.anqrpt.fastq.gz): interleaved, 70153722 reads, 150 max length
    [read_lib_functions-inl.h  : 209]     Lib 2 (./Ant_13/8176.3.92476.GGCTAC.anqrpt.fastq.gz): interleaved, 74103128 reads, 150 max length
    [read_lib_functions-inl.h  : 209]     Lib 3 (./Ant_14/8176.3.92476.CTTGTA.anqrpt.fastq.gz): interleaved, 113949762 reads, 150 max length
    [read_lib_functions-inl.h  : 209]     Lib 4 (./Ant_10/8176.6.92491.CGATGT.anqrpt.fastq.gz): interleaved, 85932630 reads, 150 max length
    [read_lib_functions-inl.h  : 209]     Lib 5 (./Ant_3/8176.8.92500.ATTCCT.anqrpt.fastq.gz): interleaved, 88136444 reads, 150 max length
    [read_lib_functions-inl.h  : 209]     Lib 6 (./Ant_1/8176.8.92500.ATGAGC.anqrpt.fastq.gz): interleaved, 68987286 reads, 150 max length
    [read_lib_functions-inl.h  : 209]     Lib 7 (./Ant_5/8176.8.92500.CAAAAG.anqrpt.fastq.gz): interleaved, 104614166 reads, 150 max length
    [read_lib_functions-inl.h  : 209]     Lib 8 (./Ant_15/8176.4.92481.AGTCAA.anqrpt.fastq.gz): interleaved, 84125876 reads, 150 max length
    [read_lib_functions-inl.h  : 209]     Lib 9 (./Ant_11/8176.3.92476.GATCAG.anqrpt.fastq.gz): interleaved, 117301706 reads, 150 max length
    [read_lib_functions-inl.h  : 209]     Lib 10 (./Ant_17/8176.4.92481.ATGTCA.anqrpt.fastq.gz): interleaved, 112474402 reads, 150 max length
    [read_lib_functions-inl.h  : 209]     Lib 11 (./Ant_9/8176.1.92466.CACGAT.anqrpt.fastq.gz): interleaved, 95037254 reads, 150 max length
    [read_lib_functions-inl.h  : 209]     Lib 12 (./Ant_2/8176.6.92491.ATCACG.anqrpt.fastq.gz): interleaved, 82904880 reads, 150 max length
    [read_lib_functions-inl.h  : 209]     Lib 13 (./Ant_6/8176.8.92500.CAACTA.anqrpt.fastq.gz): interleaved, 111582848 reads, 150 max length
    [read_lib_functions-inl.h  : 209]     Lib 14 (./Ant_16/8176.4.92481.AGTTCC.anqrpt.fastq.gz): interleaved, 106843662 reads, 150 max length
    [read_lib_functions-inl.h  : 209]     Lib 15 (./Ant_8/8176.1.92466.CACCGG.anqrpt.fastq.gz): interleaved, 91528886 reads, 150 max length
    [read_lib_functions-inl.h  : 209]     Lib 16 (./Ant_12/8176.3.92476.TAGCTT.anqrpt.fastq.gz): interleaved, 107119826 reads, 150 max length
    [utils.h                   : 124]     Real: 3733.0858	user: 1647.4244	sys: 168.2044	maxrss: 164400
--- [Wed Nov 18 13:57:26 2015] Extracting solid (k+1)-mers for k = 21 ---
cmd: /opt/bio/megahit-1.0.3/megahit_sdbg_build count -k 21 -m 2 --host_mem 475000000000 --mem_flag 2 --gpu_mem 0 --output_prefix Ant_17samples_20/tmp/k21/21 --num_cpu_threads 20 --num_output_threads 6 --read_lib_file Ant_17samples_20/tmp/reads.lib
    [sdbg_builder.cpp          : 114]     Host memory to be used: 475000000000
    [sdbg_builder.cpp          : 115]     Number CPU threads: 20
    [cx1.h                     : 450]     Preparing data...
    [read_lib_functions-inl.h  : 253]     Before reading, sizeof seq_package: 71471546376
    [read_lib_functions-inl.h  : 258]     After reading, sizeof seq_package: 71471546376
    [cx1_kmer_count.cpp        : 104]     1593103958 reads, 150 max read length
    [cx1.h                     : 457]     Preparing data... Done. Time elapsed: 250.8835
    [cx1.h                     : 464]     Preparing partitions and initialing global data...
    [cx1_kmer_count.cpp        : 195]     2 words per substring, 2 words per edge
    [cx1_kmer_count.cpp        : 332]     Memory for reads: 71471546376
    [cx1_kmer_count.cpp        : 333]     max # lv.1 items = 98965585083
    [cx1.h                     : 480]     Preparing partitions and initialing global data... Done. Time elapsed: 198.3847
    [cx1.h                     : 486]     Start main loop...
    [cx1.h                     : 515]     Lv1 scanning from bucket 0 to 12032
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 844.3646
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 3995.1977
    [cx1.h                     : 515]     Lv1 scanning from bucket 12032 to 51262
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 692.3605
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 3548.9439
    [cx1.h                     : 515]     Lv1 scanning from bucket 51262 to 65536
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 3. Time elapsed: 249.1910
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 147.9039
    [cx1.h                     : 607]     Main loop done. Time elapsed: 9477.9967
    [cx1.h                     : 613]     Postprocessing...
    [cx1_kmer_count.cpp        : 831]     Total number of candidate reads: 346456825(634506253)
    [cx1_kmer_count.cpp        : 842]     Total number of solid edges: 32424764011
    [cx1.h                     : 621]     Postprocess done. Time elapsed: 635.0562
    [utils.h                   : 124]     Real: 10564.6906	user: 155941.2086	sys: 21438.5502	maxrss: 466976900
--- [Wed Nov 18 16:53:31 2015] Building graph for k = 21 ---
/opt/bio/megahit-1.0.3/megahit_sdbg_build seq2sdbg --host_mem 475000000000 --mem_flag 2 --gpu_mem 0 --output_prefix Ant_17samples_20/tmp/k21/21 --num_cpu_threads 20 -k 21 --kmer_from 0 --num_edge_files 6 --input_prefix Ant_17samples_20/tmp/k21/21 --need_mercy
    [sdbg_builder.cpp          : 341]     Host memory to be used: 475000000000
    [sdbg_builder.cpp          : 342]     Number CPU threads: 20
    [cx1.h                     : 450]     Preparing data...
    [cx1_seq2sdbg.cpp          : 406]     Number edges: 32424764011
    [cx1_seq2sdbg.cpp          : 446]     Bases to reserve: 891681010286, number contigs: 0, number multiplicity: 40530955013
    [cx1_seq2sdbg.cpp          : 452]     Before reading, sizeof seq_package: 222920252580, multiplicity vector: 40530955013
    [cx1_seq2sdbg.cpp          : 467]     Adding mercy edges...
    [cx1_seq2sdbg.cpp          : 385]     Number of reads: 346456825, Number of mercy edges: 3733008802
    [cx1_seq2sdbg.cpp          : 474]     Done. Time elapsed: 9188.5361
    [cx1_seq2sdbg.cpp          : 526]     After reading, sizeof seq_package: 222920252580, multiplicity vector: 40530955013
    [cx1.h                     : 457]     Preparing data... Done. Time elapsed: 12952.0808
    [cx1.h                     : 464]     Preparing partitions and initialing global data...
    [cx1_seq2sdbg.cpp          : 733]     Memory for sequence: 301450415438
    [cx1_seq2sdbg.cpp          : 734]     max # lv.1 items = 42582296996
    [cx1.h                     : 480]     Preparing partitions and initialing global data... Done. Time elapsed: 160.1558
    [cx1.h                     : 486]     Start main loop...
    [cx1.h                     : 515]     Lv1 scanning from bucket 0 to 5686
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 2281. Time elapsed: 327.7453
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 954.4353
    [cx1.h                     : 515]     Lv1 scanning from bucket 5686 to 13905
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 3029. Time elapsed: 213.0973
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 951.8936
    [cx1.h                     : 515]     Lv1 scanning from bucket 13905 to 24319
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 3694. Time elapsed: 227.3153
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 924.6004
    [cx1.h                     : 515]     Lv1 scanning from bucket 24319 to 38099
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 5014. Time elapsed: 229.1465
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 907.8242
    [cx1.h                     : 515]     Lv1 scanning from bucket 38099 to 61960
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 10597. Time elapsed: 266.2687
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 828.9884
    [cx1.h                     : 515]     Lv1 scanning from bucket 61960 to 65536
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 1780. Time elapsed: 137.4704
    [cx1.h                     : 594]     Lv1 fetching & sorting done. Time elapsed: 53.0819
    [cx1.h                     : 607]     Main loop done. Time elapsed: 6021.8680
    [cx1.h                     : 613]     Postprocessing...
    [cx1_seq2sdbg.cpp          :1132]     Number of $ A C G T A- C- G- T-:
    [cx1_seq2sdbg.cpp          :1135]     709656331 16838359861 18527594206 18587085706 16829753927 492949624 642628938 641118076 465640169
    [cx1_seq2sdbg.cpp          :1144]     Total number of edges: 73734786838
    [cx1_seq2sdbg.cpp          :1145]     Total number of ONEs: 70782793700
    [cx1_seq2sdbg.cpp          :1146]     Total number of $v edges: 709656331
    [cx1.h                     : 621]     Postprocess done. Time elapsed: 15.7390
    [utils.h                   : 124]     Real: 19161.7716	user: 265203.7816	sys: 7629.9772	maxrss: 434315984
--- [Wed Nov 18 22:13:01 2015] Assembling contigs from SdBG for k = 21 ---
cmd: /opt/bio/megahit-1.0.3/megahit_asm_core assemble -s Ant_17samples_20/tmp/k21/21 -o Ant_17samples_20/intermediate_contigs/k21 -t 20 --max_tip_len -1 --min_standalone 296 --prune_level 2 --merge_len 20 --merge_similar 0.98 --low_local_ratio 0.2 --min_depth 2 --careful_bubble
    [assembler.cpp             : 141]     Loading succinct de Bruijn graph: Ant_17samples_20/tmp/k21/21 Done. Time elapsed: 2064.621408
    [assembler.cpp             : 145]     Number of Edges: 73734786838; K value: 21
    [assembler.cpp             : 155]     Number of CPU threads: 20
    [assembly_algorithms.cpp   : 135]     Removing tips with length less than 2; Accumulated tips removed: 106942354; time elapsed: 385.6129
    [assembly_algorithms.cpp   : 135]     Removing tips with length less than 4; Accumulated tips removed: 317957625; time elapsed: 468.7073
    [assembly_algorithms.cpp   : 135]     Removing tips with length less than 8; Accumulated tips removed: 478072052; time elapsed: 637.6242
    [assembly_algorithms.cpp   : 135]     Removing tips with length less than 16; Accumulated tips removed: 673375349; time elapsed: 912.5227
    [assembly_algorithms.cpp   : 135]     Removing tips with length less than 32; Accumulated tips removed: 880211016; time elapsed: 1342.0221
    [assembly_algorithms.cpp   : 143]     Removing tips with length less than 42; Accumulated tips removed: 954791326; time elapsed: 1184.4765
    [assembler.cpp             : 167]     Tips removal done! Time elapsed(sec): 4933.200739
    [assembler.cpp             : 176]     unitig graph size: 2328926097, time for building: 21427.657452
    [assembler.cpp             : 191]     Number of bubbles/complex bubbles removed: 1121145/0, Time elapsed(sec): 1412.538277
    [assembler.cpp             : 203]     Unitigs removed in excessive pruning: 1140449, time: 470.285503
    [assembler.cpp             : 125]     Total length: 79596751067, N50: 33, Mean: 34, number of contigs: 2324227686
    [assembler.cpp             : 126]     Maximum length: 693
    [assembler.cpp             : 225]     Time to output: 4421.080391
    [assembler.cpp             : 253]     Number of local low depth unitigs removed: 57836516, complex bubbles removed: 0, time: 35874.277079
    [assembler.cpp             : 125]     Total length: 74465853070, N50: 34, Mean: 34, number of contigs: 2160426776
    [assembler.cpp             : 126]     Maximum length: 739
    [utils.h                   : 124]     Real: 73472.2525	user: 1338344.9430	sys: 10772.9635	maxrss: 360046764
--- [Thu Nov 19 18:37:35 2015] Local assembling k = 21 ---
cmd: /opt/bio/megahit-1.0.3/megahit_asm_core local -c Ant_17samples_20/intermediate_contigs/k21.contigs.fa -l Ant_17samples_20/tmp/reads.lib -t 20 -o Ant_17samples_20/intermediate_contigs/k21.local.fa --kmax 41
    [local_assembler.cpp       :  89]     Number of contigs: 1190431, Mapper size: 30170355
    [read_lib_functions-inl.h  : 253]     Before reading, sizeof seq_package: 71471546376
    [read_lib_functions-inl.h  : 258]     After reading, sizeof seq_package: 71471546376
    [local_assembler.cpp       : 330]     Lib 0, insert size: 217.19 sd: 34.56
    [local_assembler.cpp       : 330]     Lib 1, insert size: 216.86 sd: 35.10
    [local_assembler.cpp       : 330]     Lib 2, insert size: 208.59 sd: 43.52
    [local_assembler.cpp       : 330]     Lib 3, insert size: 204.91 sd: 44.13
    [local_assembler.cpp       : 330]     Lib 4, insert size: 215.46 sd: 39.85
    [local_assembler.cpp       : 330]     Lib 5, insert size: 212.19 sd: 40.09
    [local_assembler.cpp       : 330]     Lib 6, insert size: 215.87 sd: 36.58
    [local_assembler.cpp       : 330]     Lib 7, insert size: 212.57 sd: 41.07
    [local_assembler.cpp       : 330]     Lib 8, insert size: 205.22 sd: 43.40
    [local_assembler.cpp       : 330]     Lib 9, insert size: 206.20 sd: 43.44
    [local_assembler.cpp       : 330]     Lib 10, insert size: 206.76 sd: 42.37
    [local_assembler.cpp       : 330]     Lib 11, insert size: 212.71 sd: 41.07
    [local_assembler.cpp       : 330]     Lib 12, insert size: 218.41 sd: 38.88
    [local_assembler.cpp       : 330]     Lib 13, insert size: 213.04 sd: 42.04
    [local_assembler.cpp       : 330]     Lib 14, insert size: 205.43 sd: 43.72
    [local_assembler.cpp       : 330]     Lib 15, insert size: 217.34 sd: 39.18
    [local_assembler.cpp       : 330]     Lib 16, insert size: 206.46 sd: 43.73
    [local_assembler.cpp       : 462]     Lib 0: total 78307480 reads, aligned 498768, added 356017 reads for local assembly
    [local_assembler.cpp       : 462]     Lib 1: total 70153722 reads, aligned 385123, added 288654 reads for local assembly
    [local_assembler.cpp       : 462]     Lib 2: total 74103128 reads, aligned 389469, added 396584 reads for local assembly
    [local_assembler.cpp       : 462]     Lib 3: total 113949762 reads, aligned 472243, added 496134 reads for local assembly
    [local_assembler.cpp       : 462]     Lib 4: total 85932630 reads, aligned 397882, added 375708 reads for local assembly
    [local_assembler.cpp       : 462]     Lib 5: total 88136444 reads, aligned 408672, added 386407 reads for local assembly
    [local_assembler.cpp       : 462]     Lib 6: total 68987286 reads, aligned 395620, added 332731 reads for local assembly
    [local_assembler.cpp       : 462]     Lib 7: total 104614166 reads, aligned 453320, added 454084 reads for local assembly
    [local_assembler.cpp       : 462]     Lib 8: total 84125876 reads, aligned 350459, added 364895 reads for local assembly
    [local_assembler.cpp       : 462]     Lib 9: total 117301706 reads, aligned 555055, added 572782 reads for local assembly
    [local_assembler.cpp       : 462]     Lib 10: total 112474402 reads, aligned 424249, added 449754 reads for local assembly
    [local_assembler.cpp       : 462]     Lib 11: total 95037254 reads, aligned 468577, added 472528 reads for local assembly
    [local_assembler.cpp       : 462]     Lib 12: total 82904880 reads, aligned 403880, added 390763 reads for local assembly
    [local_assembler.cpp       : 462]     Lib 13: total 111582848 reads, aligned 544373, added 564632 reads for local assembly
    [local_assembler.cpp       : 462]     Lib 14: total 106843662 reads, aligned 415223, added 436435 reads for local assembly
    [local_assembler.cpp       : 462]     Lib 15: total 91528886 reads, aligned 407415, added 418548 reads for local assembly
    [local_assembler.cpp       : 462]     Lib 16: total 107119826 reads, aligned 501451, added 514780 reads for local assembly
    [utils.h                   : 124]     Real: 5075.7535	user: 89315.0316	sys: 107.3418	maxrss: 72354256
--- [Thu Nov 19 20:02:11 2015] Extracting iterative edges from k = 21 to 41 ---
cmd: /opt/bio/megahit-1.0.3/megahit_asm_core iterate -c Ant_17samples_20/intermediate_contigs/k21.contigs.fa -t 20 -k 21 -s 20 -o Ant_17samples_20/tmp/k41/41 -r Ant_17samples_20/tmp/reads.lib.bin -f binary
    [iterate_edges.cpp         : 563]     Number of crusial kmers: 4012655862
    [iterate_edges.cpp         : 436]     Processed: 67108864, aligned: 65675738. Iterative edges: 763975584
    [iterate_edges.cpp         : 436]     Processed: 134217728, aligned: 129601592. Iterative edges: 2039808541
    [iterate_edges.cpp         : 436]     Processed: 201326592, aligned: 187589397. Iterative edges: 3404059467
    [iterate_edges.cpp         : 436]     Processed: 268435456, aligned: 243237671. Iterative edges: 4894257877
    [iterate_edges.cpp         : 436]     Processed: 335544320, aligned: 298424393. Iterative edges: 6089494092
    [iterate_edges.cpp         : 436]     Processed: 402653184, aligned: 359050375. Iterative edges: 7414814062
    [iterate_edges.cpp         : 436]     Processed: 469762048, aligned: 417157625. Iterative edges: 8610506973
    [iterate_edges.cpp         : 436]     Processed: 536870912, aligned: 475363744. Iterative edges: 9783055849
    [iterate_edges.cpp         : 436]     Processed: 603979776, aligned: 533471203. Iterative edges: 10752267517
    [iterate_edges.cpp         : 436]     Processed: 671088640, aligned: 588195636. Iterative edges: 11610529249
    [iterate_edges.cpp         : 436]     Processed: 738197504, aligned: 643277623. Iterative edges: 12575784826
    [iterate_edges.cpp         : 436]     Processed: 805306368, aligned: 700265714. Iterative edges: 13509137795
    [iterate_edges.cpp         : 436]     Processed: 872415232, aligned: 758722856. Iterative edges: 14286777729
    [iterate_edges.cpp         : 436]     Processed: 939524096, aligned: 813773458. Iterative edges: 15162002323
MEGAHIT v1.0.3
--- [Fri Nov 20 08:22:27 2015] Start assembly. Number of CPU threads 20 ---
--- [Fri Nov 20 08:22:27 2015] k list: 21,41,61,81,99 ---
--- [Fri Nov 20 08:22:27 2015] Extracting iterative edges from k = 21 to 41 ---
cmd: /opt/bio/megahit-1.0.3/megahit_asm_core iterate -c Ant_17samples_20/intermediate_contigs/k21.contigs.fa -t 20 -k 21 -s 20 -o Ant_17samples_20/tmp/k41/41 -r Ant_17samples_20/tmp/reads.lib.bin -f binary
    [iterate_edges.cpp         : 563]     Number of crusial kmers: 4012655862
    [iterate_edges.cpp         : 436]     Processed: 67108864, aligned: 65675738. Iterative edges: 763975584
    [iterate_edges.cpp         : 436]     Processed: 134217728, aligned: 129601592. Iterative edges: 2039808541
    [iterate_edges.cpp         : 436]     Processed: 201326592, aligned: 187589397. Iterative edges: 3404059467
    [iterate_edges.cpp         : 436]     Processed: 268435456, aligned: 243237671. Iterative edges: 4894257877
    [iterate_edges.cpp         : 436]     Processed: 335544320, aligned: 298424393. Iterative edges: 6089494092
    [iterate_edges.cpp         : 436]     Processed: 402653184, aligned: 359050375. Iterative edges: 7414814062
    [iterate_edges.cpp         : 436]     Processed: 469762048, aligned: 417157625. Iterative edges: 8610506973
    [iterate_edges.cpp         : 436]     Processed: 536870912, aligned: 475363744. Iterative edges: 9783055849
    [iterate_edges.cpp         : 436]     Processed: 603979776, aligned: 533471203. Iterative edges: 10752267517
    [iterate_edges.cpp         : 436]     Processed: 671088640, aligned: 588195636. Iterative edges: 11610529249
    [iterate_edges.cpp         : 436]     Processed: 738197504, aligned: 643277623. Iterative edges: 12575784826
    [iterate_edges.cpp         : 436]     Processed: 805306368, aligned: 700265714. Iterative edges: 13509137795
    [iterate_edges.cpp         : 436]     Processed: 872415232, aligned: 758722856. Iterative edges: 14286777729
    [iterate_edges.cpp         : 436]     Processed: 939524096, aligned: 813773458. Iterative edges: 15162002323
MEGAHIT v1.0.3
--- [Fri Nov 20 13:23:43 2015] Start assembly. Number of CPU threads 20 ---
--- [Fri Nov 20 13:23:43 2015] k list: 21,41,61,81,99 ---
--- [Fri Nov 20 13:23:43 2015] Extracting iterative edges from k = 21 to 41 ---
cmd: /opt/bio/megahit-1.0.3/megahit_asm_core iterate -c Ant_17samples_20/intermediate_contigs/k21.contigs.fa -t 20 -k 21 -s 20 -o Ant_17samples_20/tmp/k41/41 -r Ant_17samples_20/tmp/reads.lib.bin -f binary
    [iterate_edges.cpp         : 563]     Number of crusial kmers: 4012655862
    [iterate_edges.cpp         : 436]     Processed: 67108864, aligned: 65675738. Iterative edges: 763975584
    [iterate_edges.cpp         : 436]     Processed: 134217728, aligned: 129601592. Iterative edges: 2039808541
    [iterate_edges.cpp         : 436]     Processed: 201326592, aligned: 187589397. Iterative edges: 3404059467
    [iterate_edges.cpp         : 436]     Processed: 268435456, aligned: 243237671. Iterative edges: 4894257877
    [iterate_edges.cpp         : 436]     Processed: 335544320, aligned: 298424393. Iterative edges: 6089494092
    [iterate_edges.cpp         : 436]     Processed: 402653184, aligned: 359050375. Iterative edges: 7414814062
    [iterate_edges.cpp         : 436]     Processed: 469762048, aligned: 417157625. Iterative edges: 8610506973
    [iterate_edges.cpp         : 436]     Processed: 536870912, aligned: 475363744. Iterative edges: 9783055849
    [iterate_edges.cpp         : 436]     Processed: 603979776, aligned: 533471203. Iterative edges: 10752267517
    [iterate_edges.cpp         : 436]     Processed: 671088640, aligned: 588195636. Iterative edges: 11610529249
    [iterate_edges.cpp         : 436]     Processed: 738197504, aligned: 643277623. Iterative edges: 12575784826
    [iterate_edges.cpp         : 436]     Processed: 805306368, aligned: 700265714. Iterative edges: 13509137795
    [iterate_edges.cpp         : 436]     Processed: 872415232, aligned: 758722856. Iterative edges: 14286777729
    [iterate_edges.cpp         : 436]     Processed: 939524096, aligned: 813773458. Iterative edges: 15162002323
Error occurs when running iterator for k = 21 to k = 41, please refer to Ant_17samples_20/log for detail
[Exit code -9]

**Comment by voutcn** [comment]
Oh I see. It's out of memory in the iteration part. Generally the memory is peaked at building the first graph, but when the genome to assemble has many short repeats, the peak will be at the iteration part. That's why smaller step worked. It's not the new version's problem.

I'd suggest you start from a larger k (say 27 or 31). 21 is too small so that the N50 and max contig length at k = 21 looks too short.

**Comment by atfric** [comment]
Oh, Thanks!
Is there a way to set / check maximum contig length?

**Comment by voutcn** [comment]
You cannot set the maximum contig length, but can check this stat from the log file (for each k).
```
[assembler.cpp : 125] Total length: 79596751067, N50: 33, Mean: 34, number of contigs: 2324227686
[assembler.cpp : 126] Maximum length: 693
[assembler.cpp : 225] Time to output: 4421.080391
```
