### ISSUE TITLE
--mincount scaling to kmer size?

### ISSUE THREAD

**Issue by tseemann** [voutcn/megahit#64]
I notice that `--min-count` is a fixed number that applies to all of the `k` values that are used?

Do you think it would make sense to scale this `k` some way?

ie. Big k values are more likely to be unique than small k values.

**Comment by voutcn** [comment]
`--min-count` is only for the minimum `k`. We don't consider the `--min-count` in the iteration of `k`.

e.g. if the k-list is 21, 41, we only filter the 21-mers whose frequcency < `--min-count`. The 41 graph is based on the 21-graph, i.e. each sub 21-mers of a 41-mer should have freq >= `min-count`.

**Comment by tseemann** [comment]
Ok, thanks for explaining that!  

I have another question but I'll start another topic.
