### ISSUE TITLE
Can megahit be used to assemble large genome (~1G)?

### ISSUE THREAD

**Issue by billzt** [voutcn/megahit#66]
Traditionally SOAPdenovo2 is used to assemble large genome, however it stops update since two years ago. In https://github.com/aquaskyline/SOAPdenovo2 , @aquaskyline claims that MEGAHIT is the formal successor of SOAPdenovo2. Is there any examples for megahit in large genome assembling?

**Comment by voutcn** [comment]
Sure, and it is likely that MEGAHIT is better than SOAPdenovo2 in **contig assembly**. We will do some tests to link MEGAHIT's contigs with scaffolders to see how well does it work in scaffolding. Hopefully I will give some examples in the near future.

**Comment by billzt** [comment]
That's no problem. I only need <b>contig assembly</b>, and then use Pacbio long reads to do a mix assbemly using DBG2OLC

**Comment by voutcn** [comment]
DBG2OLC requires contigs that are not heavily repeat-resolved. You may try different contig files assembled with different kmer size in the "intermediate_contigs" directory and choose a best one.

**Comment by billzt** [comment]
Thanks for suggestion. As a outdoor learner, I am not very clear what repeat-resolving is. SOAPdenovo2 has an -R option to turn on/off repeat resolve. In MEGAHIT, no similar document was found.

**Comment by voutcn** [comment]
Typcially the larger the k goes, the more repeats are resolved.
