### ISSUE TITLE
[Exit code -4]

### ISSUE THREAD

**Issue by miguelpmachado** [voutcn/megahit#69]
Hi,

I'm trying to do a run test with MEGAHIT v1.0.3-29-g707d683 with the following comand:

<code>
./megahit --presets meta --num-cpu-threads 2 --out-dir /home/mpmachado/megahit_out --out-prefix teste -1 /scratch/mpmachado/GBSgenomes/GBS_01/GBS_01.L500_SZAIPI031927-94_1.fq.gz -2 /scratch/mpmachado/GBSgenomes/GBS_01/GBS_01.L500_SZAIPI031927-94_2.fq.gz
</code>

However it stopped with a 

> Error occurs when assembling contigs for k = 21, please refer to /home/mpmachado/megahit_out/teste.log for detail
> [Exit code -4]

You can find the log file attached.
Could you please help me solving the problem?

Best regards,

Miguel Machado

[teste.log.txt](https://github.com/voutcn/megahit/files/100825/teste.log.txt)

**Comment by voutcn** [comment]
This should help https://github.com/voutcn/megahit/wiki#q-how-to-solve-the-problem-of-error-occurs-when-assembling-contigs-for-kxxx-exit-code--4

**Comment by miguelpmachado** [comment]
It worked. Thanks
