### ISSUE TITLE
Use megahit to assemble contigs into scaffolds ?

### ISSUE THREAD

**Issue by davidmartinad200** [voutcn/megahit#70]
Hi,
I have successfully used megahit with a metagenome. Can i use also to assemble contigs into scaffolds if not  any suggested program for doing that ? ?

thanks

**Comment by voutcn** [comment]
I have limited experience. You may try SSPACE.

**Comment by davidmartinad200** [comment]
Thanks for the info. Unfortunately SSPACE is not open source......

**Comment by colindaven** [comment]
Others include BESST, search for scaffolders at the omics tools website for example
