### ISSUE TITLE
wanghanchenwhc's issues

### ISSUE THREAD

**Issue by voutcn** [voutcn/megahit#73]
```
MEGAHIT v1.1.0-pre
--- [Sat Feb 13 16:41:28 2016] Start assembly. Number of CPU threads 24 ---
--- [Sat Feb 13 16:41:28 2016] Available memory: 25323257856, used: 22790932070
--- [Sat Feb 13 16:41:28 2016] k list: 21,41,61,81,99 ---
--- [Sat Feb 13 16:41:28 2016] Converting reads to binaries ---
/lustre/home/hcwang/data/megahit-master/megahit_asm_core buildlib /home/hcwang/sample/S9_megahit_output/tmp/reads.lib /home/hcwang/sample/S9_megahit_output/tmp/reads.lib
megahit_asm_core: sequence_manager.cpp:121: int64_t SequenceManager::ReadShortReads(int64_t, int64_t, bool, bool, bool): Assertion `kseq_read(kseq_readers_[1]) >= 0' failed.
Error occurs when running "megahit_asm_core buildlib"; please refer to /home/hcwang/sample/S9_megahit_output/S9_megahit.log for detail
[Exit code -6]
```

@wanghanchenwhc I am opening a separate issue.
Both fasta and fastq should work. What's the value of `$R1` and `$R2`? Could you check whether they have the same number of reads?

**Comment by wanghanchenwhc** [comment]
@voutcn You are right! I double checked the $R1 and $R2 files (stands for forward read and reverse read). There was a mess-up with read numbers (I didn't remove the single reads that didn't have a pair). Do you know any program that can check the read ID and eliminate unmatched reads? 
Thank you for your help! Hope you have a nice day!
HanChen

**Comment by voutcn** [comment]
[khmer])https://github.com/dib-lab/khmer) has a [script](https://github.com/dib-lab/khmer/blob/master/scripts/extract-paired-reads.py) to extract PE reads from one file.
