### ISSUE TITLE
Help with error: p_rec_[bucket].thread_id == -1' failed

### ISSUE THREAD

**Issue by BTBarney** [voutcn/megahit#78]
I am assembling some individual genomes from one of my study organisms (a fish), and I have encountered a technical problem: when I assemble an individual genome, assembly completes satisfactorily.  However, I have an error thrown when I try to assemble 15 samples together in one  combined assembly - the error text is replicated below (as is the command I issued to the server, and the error text and log file):

error thrown: megahit_sdbg_build: edge_io.h:92: void EdgeWriter::write(uint32_t*, int32_t, int): Assertion `p_rec_[bucket].thread_id == -1' failed.
Error occurs when running "sdbg_builder count/read2sdbg", please refer to combined_megahit_asm/log for detail

I could not find a discussion forum to ask, so I'll ask here - what is the nature of the error?  What can I do to proceed?

Thanks!
-Bryan

#### command as issued to server:

megahit \
-1 fastq/C1S1_R1_paired.fastq.gz -2 fastq/C1S1_R2_paired.fastq.gz \
-1 fastq/C1S3_R1_paired.fastq.gz -2 fastq/C1S3_R2_paired.fastq.gz \
-1 fastq/C1S5_R1_paired.fastq.gz -2 fastq/C1S5_R2_paired.fastq.gz \
-1 fastq/C1S6_R1_paired.fastq.gz -2 fastq/C1S6_R2_paired.fastq.gz \
-1 fastq/C1S7_R1_paired.fastq.gz -2 fastq/C1S7_R2_paired.fastq.gz \
-1 fastq/Lib_3_2_R1_paired.fastq.gz -2 fastq/Lib_3_2_R2_paired.fastq.gz \
-1 fastq/Lib_3_3_R1_paired.fastq.gz -2 fastq/Lib_3_3_R2_paired.fastq.gz \
-1 fastq/Lib_3_4_R1_paired.fastq.gz -2 fastq/Lib_3_4_R2_paired.fastq.gz \
-1 fastq/Lib_3_6b_R1_paired.fastq.gz -2 fastq/Lib_3_6b_R2_paired.fastq.gz \
-1 fastq/Lib_3_8_R1_paired.fastq.gz -2 fastq/Lib_3_8_R2_paired.fastq.gz \
-1 fastq/GB15_R1_paired.fastq.gz -2 fastq/GB15_R2_paired.fastq.gz \
-1 fastq/GB17_R1_paired.fastq.gz -2 fastq/GB17_R2_paired.fastq.gz \
-1 fastq/GB18_R1_paired.fastq.gz -2 fastq/GB18_R2_paired.fastq.gz \
-1 fastq/GB19_R1_paired.fastq.gz -2 fastq/GB19_R2_paired.fastq.gz \
-1 fastq/GB20_R1_paired.fastq.gz -2 fastq/GB20_R2_paired.fastq.gz \
-o combined_megahit_asm

##### output from *.err file
1514.0Gb memory in total.
Using: 1363.267Gb.
MEGAHIT v1.0.4-beta
--- [Sat Apr  9 09:10:51 2016] Start assembly. Number of CPU threads 32 ---
--- [Sat Apr  9 09:10:51 2016] Available memory: 1626441322496, used: 1463797190246
--- [Sat Apr  9 09:10:51 2016] k list: 21,41,61,81,99 ---
--- [Sat Apr  9 09:10:51 2016] Converting reads to binaries ---
    [read_lib_functions-inl.h  : 209]     Lib 0 (fastq/C1S1_R1_paired.fastq.gz,fastq/C1S1_R2_paired.fastq.gz): pe, 342933162 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 1 (fastq/C1S3_R1_paired.fastq.gz,fastq/C1S3_R2_paired.fastq.gz): pe, 336517062 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 2 (fastq/C1S5_R1_paired.fastq.gz,fastq/C1S5_R2_paired.fastq.gz): pe, 181538720 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 3 (fastq/C1S6_R1_paired.fastq.gz,fastq/C1S6_R2_paired.fastq.gz): pe, 226896040 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 4 (fastq/C1S7_R1_paired.fastq.gz,fastq/C1S7_R2_paired.fastq.gz): pe, 380638642 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 5 (fastq/Lib_3_2_R1_paired.fastq.gz,fastq/Lib_3_2_R2_paired.fastq.gz): pe, 497845138 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 6 (fastq/Lib_3_3_R1_paired.fastq.gz,fastq/Lib_3_3_R2_paired.fastq.gz): pe, 441604748 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 7 (fastq/Lib_3_4_R1_paired.fastq.gz,fastq/Lib_3_4_R2_paired.fastq.gz): pe, 366968494 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 8 (fastq/Lib_3_6b_R1_paired.fastq.gz,fastq/Lib_3_6b_R2_paired.fastq.gz): pe, 399713092 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 9 (fastq/Lib_3_8_R1_paired.fastq.gz,fastq/Lib_3_8_R2_paired.fastq.gz): pe, 447404130 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 10 (fastq/GB15_R1_paired.fastq.gz,fastq/GB15_R2_paired.fastq.gz): pe, 512970440 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 11 (fastq/GB17_R1_paired.fastq.gz,fastq/GB17_R2_paired.fastq.gz): pe, 493524876 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 12 (fastq/GB18_R1_paired.fastq.gz,fastq/GB18_R2_paired.fastq.gz): pe, 352808346 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 13 (fastq/GB19_R1_paired.fastq.gz,fastq/GB19_R2_paired.fastq.gz): pe, 404935436 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 14 (fastq/GB20_R1_paired.fastq.gz,fastq/GB20_R2_paired.fastq.gz): pe, 470025688 reads, 100 max length
    [utils.h                   : 124]     Real: 7927.9430	user: 5178.6677	sys: 539.4430	maxrss: 153652
--- [Sat Apr  9 11:22:59 2016] Extracting solid (k+1)-mers for k = 21 ---
Error occurs when running "sdbg_builder count/read2sdbg", please refer to combined_megahit_asm/log for detail
[Exit code -6] 

######## 
########

MEGAHIT v1.0.4-beta
--- [Sat Apr  9 09:10:51 2016] Start assembly. Number of CPU threads 32 ---
--- [Sat Apr  9 09:10:51 2016] Available memory: 1626441322496, used: 1463797190246
--- [Sat Apr  9 09:10:51 2016] k list: 21,41,61,81,99 ---
--- [Sat Apr  9 09:10:51 2016] Converting reads to binaries ---
/share/PI/spalumbi/programs/megahit_asm_core buildlib combined_megahit_asm/tmp/reads.lib combined_megahit_asm/tmp/reads.lib
    [read_lib_functions-inl.h  : 209]     Lib 0 (fastq/C1S1_R1_paired.fastq.gz,fastq/C1S1_R2_paired.fastq.gz): pe, 342933162 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 1 (fastq/C1S3_R1_paired.fastq.gz,fastq/C1S3_R2_paired.fastq.gz): pe, 336517062 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 2 (fastq/C1S5_R1_paired.fastq.gz,fastq/C1S5_R2_paired.fastq.gz): pe, 181538720 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 3 (fastq/C1S6_R1_paired.fastq.gz,fastq/C1S6_R2_paired.fastq.gz): pe, 226896040 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 4 (fastq/C1S7_R1_paired.fastq.gz,fastq/C1S7_R2_paired.fastq.gz): pe, 380638642 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 5 (fastq/Lib_3_2_R1_paired.fastq.gz,fastq/Lib_3_2_R2_paired.fastq.gz): pe, 497845138 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 6 (fastq/Lib_3_3_R1_paired.fastq.gz,fastq/Lib_3_3_R2_paired.fastq.gz): pe, 441604748 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 7 (fastq/Lib_3_4_R1_paired.fastq.gz,fastq/Lib_3_4_R2_paired.fastq.gz): pe, 366968494 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 8 (fastq/Lib_3_6b_R1_paired.fastq.gz,fastq/Lib_3_6b_R2_paired.fastq.gz): pe, 399713092 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 9 (fastq/Lib_3_8_R1_paired.fastq.gz,fastq/Lib_3_8_R2_paired.fastq.gz): pe, 447404130 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 10 (fastq/GB15_R1_paired.fastq.gz,fastq/GB15_R2_paired.fastq.gz): pe, 512970440 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 11 (fastq/GB17_R1_paired.fastq.gz,fastq/GB17_R2_paired.fastq.gz): pe, 493524876 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 12 (fastq/GB18_R1_paired.fastq.gz,fastq/GB18_R2_paired.fastq.gz): pe, 352808346 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 13 (fastq/GB19_R1_paired.fastq.gz,fastq/GB19_R2_paired.fastq.gz): pe, 404935436 reads, 100 max length
    [read_lib_functions-inl.h  : 209]     Lib 14 (fastq/GB20_R1_paired.fastq.gz,fastq/GB20_R2_paired.fastq.gz): pe, 470025688 reads, 100 max length
    [utils.h                   : 124]     Real: 7927.9430	user: 5178.6677	sys: 539.4430	maxrss: 153652
--- [Sat Apr  9 11:22:59 2016] Extracting solid (k+1)-mers for k = 21 ---
cmd: /share/PI/spalumbi/programs/megahit_sdbg_build count -k 21 -m 2 --host_mem 1463797190246 --mem_flag 1 --gpu_mem 0 --output_prefix combined_megahit_asm/tmp/k21/21 --num_cpu_threads 32 --num_output_threads 10 --read_lib_file combined_megahit_asm/tmp/reads.lib
    [sdbg_builder.cpp          : 116]     Host memory to be used: 1463797190246
    [sdbg_builder.cpp          : 117]     Number CPU threads: 32
    [cx1.h                     : 450]     Preparing data...
    [read_lib_functions-inl.h  : 256]     Before reading, sizeof seq_package: 191683304264
    [read_lib_functions-inl.h  : 260]     After reading, sizeof seq_package: 191683304264
    [cx1_kmer_count.cpp        : 136]     5856324014 reads, 100 max read length
    [cx1.h                     : 457]     Preparing data... Done. Time elapsed: 1544.9468
    [cx1.h                     : 464]     Preparing partitions and initialing global data...
    [cx1_kmer_count.cpp        : 227]     2 words per substring, 2 words per edge
    [cx1_kmer_count.cpp        : 364]     Memory for reads: 196209326544
    [cx1_kmer_count.cpp        : 365]     max # lv.1 items = 60848127767
    [cx1.h                     : 480]     Preparing partitions and initialing global data... Done. Time elapsed: 581.3141
    [cx1.h                     : 486]     Start main loop...
    [cx1.h                     : 515]     Lv1 scanning from bucket 0 to 230
    [cx1.h                     : 528]     Lv1 scanning done. Large diff: 0. Time elapsed: 587.8190
megahit_sdbg_build: edge_io.h:92: void EdgeWriter::write(uint32_t*, int32_t, int): Assertion `p_rec_[bucket].thread_id == -1' failed.
Error occurs when running "sdbg_builder count/read2sdbg", please refer to combined_megahit_asm/log for detail
[Exit code -6]

**Comment by voutcn** [comment]
It *might* be a bug, but I am not able to reproduce the error so it is a bit difficult to figure out what happened.

Could you check out the `debug` branch and rerun Megahit to see if it will halt at the same place?

Under the directory when you run Megahit for the 15 samples:
```
git clone https://github.com/voutcn/megahit.git
cd megahit
git checkout debug
make -j8
megahit/megahit --continue -o combined_megahit_asm
```

**Comment by BTBarney** [comment]
in process, will update when the job runs in the queue
