### ISSUE TITLE
Error "Assertion `kseq_read(kseq_readers_[1]) >= 0' failed." with trimmed reads

### ISSUE THREAD

**Issue by lorian** [voutcn/megahit#79]
I'm assembling a low-coverage metagenomic dataset. Megahit can assemble the untrimmed reads (PE reads, 45G both R1 and R2), but it throws an error when I try to assemble the reads once they've been trimmed with Trimommatic. The trimmed reads are still paired, although the R1 average length is now shorter than the R2 average length.

./megahit --presets meta -1 CE_trimmed_R1.fastq -2 CE_trimmed_R2.fastq -o megahit_CE_trimmed

410.0Gb memory in total.
Using: 369.09Gb.
MEGAHIT v1.0.4-beta-3-g027c6b6
--- [Thu Apr 14 17:31:49 2016] Start assembly. Number of CPU threads 48 ---
--- [Thu Apr 14 17:31:49 2016] Available memory: 440340946944, used: 396306852249
--- [Thu Apr 14 17:31:49 2016] k list: 21,41,61,81,99 ---
--- [Thu Apr 14 17:31:49 2016] Converting reads to binaries ---
megahit_asm_core: sequence_manager.cpp:121: int64_t SequenceManager::ReadShortReads(int64_t, int64_t, bool, bool, bool): Assertion `kseq_read(kseq_readers_[1]) >= 0' failed.
cat: write error: Broken pipe
Error occurs when running "megahit_asm_core buildlib"; please refer to megahit_CE_trimmed/log for detail
[Exit code -6]

**Comment by voutcn** [comment]
I believe that the number of R1 & R2 reads are not the same after trimming. Please check the two files.
