### ISSUE TITLE
Exit code -6

### ISSUE THREAD

**Issue by bwawrik** [voutcn/megahit#80]
Hi,

I tried megahit today, but get varying errors depending on which system I try it on.  Here is the error I get from my VM:

cat log
MEGAHIT v1.0.4-beta-4-g58b0995
--- [Wed Apr 20 20:32:20 2016] Start assembly. Number of CPU threads 8 ---
--- [Wed Apr 20 20:32:20 2016] Available memory: 67555074048, used: 60799566643
--- [Wed Apr 20 20:32:20 2016] k list: 21,41,61,81,99 ---
--- [Wed Apr 20 20:32:20 2016] Converting reads to binaries ---
/data/software/megahit/megahit_asm_core buildlib megahit/tmp/reads.lib megahit/tmp/reads.lib
megahit_asm_core: sequence_manager.cpp:121: int64_t SequenceManager::ReadShortReads(int64_t, int64_t, bool, bool, bool): Assertion `kseq_read(kseq_readers_[1]) >= 0' failed.
Error occurs when running "megahit_asm_core buildlib"; please refer to megahit/log for detail
[Exit code -6]

Any thoughts what causes this ?

thanks in advance !

**Comment by voutcn** [comment]
The number of reads in the two paired-end files are not the same. Please check.
The assembler assumes that the reads are paired in the two files.

**Comment by bwawrik** [comment]
yupp; that would be the problem. Thanks !
