### ISSUE TITLE
SdbgReader::read_info() assertion failed

### ISSUE THREAD

**Issue by cmorganl** [voutcn/megahit#82]
Hey there,

I'm also getting an error code -6 but from a different function.

```
--- [Wed Apr 20 22:03:34 2016] Assembling contigs from SdBG for k = 51 ---
cmd: /home/alysekh/bin/megahit_v1.0.3_LINUX_CUDA6.5_sm350_x86_64-bin/megahit_asm_core assemble -s TARA_B100001989/tmp/k51/51 -o TARA_B100001989/intermediate_contigs/k51 -
    [assembler.cpp             : 141]     Loading succinct de Bruijn graph: TARA_B100001989/tmp/k51/51 megahit_asm_core: sdbg_multi_io.h:239: void SdbgReader::read_info()
Error occurs when assembling contigs for k = 51, please refer to TARA_B100001989/log for detail
[Exit code -6]
```

It was successfully able to assemble from 21 to 41. Its dealing with 100bp Illumina reads and running on a RHEL system with 100Gb RAM available on 256 Gb nodes.

Let me know if I need to email you the log file or anything else.

Thanks!

**Comment by voutcn** [comment]
Could you provide the contents of the log file in the output directory here?

**Comment by cmorganl** [comment]
I've attached it here:
[log.txt](https://github.com/voutcn/megahit/files/235393/log.txt)

**Comment by voutcn** [comment]
@cmorganl Could you also attach the `TARA_B100001989/tmp/k51/51.edges.info` and `TARA_B100001989/tmp/k51/51.sdbg_info`. Thx.
