### ISSUE TITLE
Number of CPU threads impacts the assembly?

### ISSUE THREAD

**Issue by Isoobel** [voutcn/megahit#84]
To test my pipeline, I tried to assemble a small fasta file with megahit (only 3,000 reads, meta-large option).

Depending on the -t option I obtained a different number of contigs:
- t = 5: 14 contigs
- t = 20: 18 contigs
- t = 40: 29 contigs
no -t option (64 threads then): 29 contigs

Could you explain me why there is such a difference? I guess this only impact small files and it will be ok with larger ones (I never got this problem with large files).

**Comment by voutcn** [comment]
The number of contigs is expected to be the same with different number of threads.
Could you send me (voutcn at gmail dot com) the fasta file so that I can figure out what happened?

**Comment by voutcn** [comment]
Fixed. https://github.com/voutcn/megahit/commit/d03d6e6bc877f12fda1b8ddd23c4c6c2e130f222
