### ISSUE TITLE
Non overlapping sequences are not reported in the contigs

### ISSUE THREAD

**Issue by Isoobel** [voutcn/megahit#85]
I tested megahit on a few reads that I cut from a longer sequence: I produced 140 nt reads with 70nt overlap with the previous one. I was expecting to obtain a contig with the entire sequence, but the first read beginning and the last read end were not reported in the contig.

Let me illustrate this with a short example:
If I have 3 reads as input (imagine they are a little bit longer!):
>seq1
AAAATTTT
>seq2
TTTTCCCC
>seq3
CCCCGGGG

Megahit will report this contig: TTTTCCCC
CLC assembler (and maybe others?) will report this contig: AAAATTTTCCCCGGGG

Is there an option to report the longer contig? I tried min-count 1 but it did not work (and it may be not advised to set this option to 1?!)

**Comment by voutcn** [comment]
If your reads are error-free and the long sequence does not contain repeats > ~70bp,  `--min-count 1` should work to reproduce the entire sequence. Again you can send me the file and let me play with it.

**Comment by voutcn** [comment]
Reproduced with `--min-count 1`. Be careful that `--presets` override other options.
