### ISSUE TITLE
new beginner want to know what is a mercy kmer

### ISSUE THREAD

**Issue by doctorriver** [voutcn/megahit#86]
And I want to know how it affects the results. Thank you.

**Comment by voutcn** [comment]
Excerpted from MEGAHIT [paper](http://bioinformatics.oxfordjournals.org/content/31/10/1674.long)

> Notably, sequencing error is problematic, because a single base of sequencing error leads to k erroneous k-mer singletons, which increases the memory consumption of MEGAHIT significantly. To cope with the problem, before graph construction, all (k + 1)-mers from the input reads are sorted and counted, and only (k + 1)-mers that appear at least d (2 by default) times are kept as solid-kmer. This method removes many spurious edges, but may be risky for metagenomics assembly since many low-abundance species may have been sequenced at very low depth. Thus we introduce a mercy-kmer strategy to recover these low-depth edges. Given two solid (k + 1)-mers x and y from the same read, where x has no outdegree and y has no indegree, if all (k + 1)-mers between x and y in that read are not solid, they will be added to the de Bruijn graph as mercy-kmers. Mercy-kmers strengthen the contiguity of low-depth regions. Without this approach, many authentic low-depth edges would be incorrectly identified as tips and removed.
