### ISSUE TITLE
bug in megahit version reporting 1.0.5

### ISSUE THREAD

**Issue by aclum** [voutcn/megahit#87]
We just installed megahit version 1.0.5.
megahit --version returns "MEGAHIT v0.1.3"

and the assembly log files also incorrectly report 0.1.3.

megahit  -o test_1.0.5 --12 1million.fastq
125.0Gb memory in total.
Using: 113.008Gb.
MEGAHIT v0.1.3

**Comment by voutcn** [comment]
Tested obtaining MEGAHIT form `git clone`, binary release and source codes from the release page, and none of them reproduce the error. Could you double check the installation?

**Comment by danudwary** [comment]
It appears that depending on directory of compilation, I get sometimes get a 
-DPACKAGE_VERSION="\"v0.1.3\"" flag in the compile commands

Compiled from $HOME:
g++ -g -O2 -Wall -Wno-unused-function -Wno-array-bounds -D__STDC_FORMAT_MACROS -funroll-loops -fprefetch-loop-arrays -fopenmp -I. -std=c++0x -static-libgcc -m64 -static-libstdc++ -mpopcnt -c succinct_dbg.cpp -o succinct_dbg.o

Compiled from a dir adjacent to other installed versions (0.1.3 is not one of them):
g++ -g -O2 -Wall -Wno-unused-function -Wno-array-bounds -D__STDC_FORMAT_MACROS -funroll-loops -fprefetch-loop-arrays -fopenmp -I. -std=c++0x -static-libgcc -m64 -static-libstdc++ -mpopcnt -DPACKAGE_VERSION="\"v0.1.3\"" -c succinct_dbg.cpp -o succinct_dbg.o

**Comment by voutcn** [comment]
@danudwary I use `git describe --tag` to define version number, or the string defined in `definitions.h` if git fails. In your case what's the output of `git describe --tag`? Is it possible that the tags on github were not merged to your local branch?
