### ISSUE TITLE
Space in read file names

### ISSUE THREAD

**Issue by AlphaSquad** [voutcn/megahit#89]
Hi,
while trying to run a batch of assemblies, I noticed weird behaviour when processing folders/files with whitespaces in their name:
I was running the following command:
`megahit -1 Yersinia\ pestis_0900/Yersinia\ pestis1.fq -2 Yersinia\ pestis_0900/Yersinia\ pestis2.fq -o Yersinia\ pestis_0900/out`
Crashing with the following error:
>251.0Gb memory in total.
Using: 226.586Gb.
MEGAHIT v1.0.6
--- [Fri Jul  1 14:24:22 2016] Start assembly. Number of CPU threads 48 ---
--- [Fri Jul  1 14:24:22 2016] Available memory: 270327144448, used: 243294430003
--- [Fri Jul  1 14:24:22 2016] k list: 21,41,61,81,99 ---
--- [Fri Jul  1 14:24:22 2016] Converting reads to binaries ---
megahit_asm_core: sequence_manager.cpp:58: void SequenceManager::set_pe_files(const string&, const string&): Assertion `files_[0] != __null' failed.
Error occurs when running "megahit_asm_core buildlib"; please refer to Yersinia pestis_0900/out/log for detail
[Exit code -6]

Changing the command to
`megahit -1 "Yersinia pestis_0900/Yersinia pestis1.fq" -2 "Yersinia pestis_0900/Yersinia pestis2.fq" -o "Yersinia pestis_0900/out"` yields
>251.0Gb memory in total.
Using: 226.586Gb.
MEGAHIT v1.0.6
--- [Fri Jul  1 14:28:08 2016] Start assembly. Number of CPU threads 48 ---
--- [Fri Jul  1 14:28:08 2016] Available memory: 270327144448, used: 243294430003
--- [Fri Jul  1 14:28:08 2016] k list: 21,41,61,81,99 ---
--- [Fri Jul  1 14:28:08 2016] Converting reads to binaries ---
cat: Yersinia: input file is output file
cat: pestis_0900/Yersinia: No such file or directory
cat: pestis1.fq: No such file or directory
cat: pestis_0900/out/tmp/inpipe.pe1.0: No such file or directory
cat: Yersinia: input file is output file
cat: pestis_0900/Yersinia: No such file or directory
cat: pestis2.fq: No such file or directory
cat: pestis_0900/out/tmp/inpipe.pe2.0: No such file or directory

and actually creates a file `Yersinia` in my current working directory, which does not get deleted after the crash.
The (read) files actually exist and if the spaces are replaced with underscores the assembly runs fine

**Comment by epruesse** [comment]
Adrian,
I've added a patch above that should fix your problem. However, I would strongly suggest that you instead actually change your file and directory names to not include spaces (or other weird characters). Those spaces will just give you headache as you run into more tools that have problems with them.
Elmar

**Comment by AlphaSquad** [comment]
Thanks alot. 
And you are right about the filenames. They were automatically created by a download script and are changed by now - I just wanted to pass this strange behaviour along.
