### ISSUE TITLE
exit code -6. Is it too many reads?

### ISSUE THREAD

**Issue by swollen** [voutcn/megahit#91]
Hi 
MegaHit works for the first set of 2x100 PE reads, about 30 million of them, but when I add another 20 million it fails.  Does not matter if I compile it myself or use the pre-compiled version.  Here is what is returned:

megahit_v1.0.6_LINUX_CPUONLY_x86_64-bin/megahit \
-1 DAG.1.P.80.fq \
-2 DAG.2.P.80.fq \
--k-max 41 \
--k-min 21 \
--k-step 30 \
-t 64 \
-o out.megahit4 \
--out-prefix trial4 \
--memory 0.8  \
--tmp-dir /tmp

------------------------------------------------------------

Exited with exit code 250.

Resource usage summary:

    CPU time   :  54590.70 sec.
    Max Memory :     10529 MB
    Max Swap   :     14831 MB

    Max Processes  :         9

The output (if any) follows:

504.0Gb memory in total.
Using: 403.916Gb.
MEGAHIT v1.0.6
--- [Sun Jul  3 13:52:39 2016] Start assembly. Number of CPU threads 64 ---
--- [Sun Jul  3 13:52:39 2016] Available memory: 542126219264, used: 433700975411
--- [Sun Jul  3 13:52:39 2016] k list: 21,41 ---
--- [Sun Jul  3 13:52:39 2016] Converting reads to binaries ---
    [read_lib_functions-inl.h  : 209]     Lib 0 (DAG.1.P.80.fq,DAG.2.P.80.fq): pe, 122042314 reads, 100 max length
    [utils.h                   : 126]     Real: 273.7493        user: 149.5573  sys: 14.8747    maxrss: 155876
--- [Sun Jul  3 13:57:12 2016] Extracting solid (k+1)-mers for k = 21 ---
--- [Sun Jul  3 14:07:22 2016] Building graph for k = 21 ---
--- [Sun Jul  3 14:13:34 2016] Assembling contigs from SdBG for k = 21 ---
Error occurs when assembling contigs for k = 21, please refer to out.megahit4/trial4.log for detail
[Exit code -6]

Here is the end of the error message from the log file.

    [assembler.cpp             : 148]     Loading succinct de Bruijn graph: /tmp/megahit_tmp_qXH4GP/k21/21 megahit_asm_core: sdbg_multi_io.h:243: void SdbgReader::read_info(): Assertion `fscanf(sdbg_info, "k %d\n", &kmer_size_) == 1' failed.
Error occurs when assembling contigs for k = 21, please refer to out.megahit4/trial4.log for detail
[Exit code -6]

I have attached the complete log file.
Any suggestions?
Thanks

Bill

**Comment by voutcn** [comment]
I guess there is not enough space in `/tmp`. Could you confirm that?
If the file is still there, could you show me the first 20 lines of `/tmp/megahit_tmp_qXH4GP/k21/21.sdbg_info`?

**Comment by swollen** [comment]
Thanks, you were right and I now have it working once I found a larger place for the files.

________________________________
