### ISSUE TITLE
Makefile:243: recipe for target 'megahit_asm_core' failed

### ISSUE THREAD

**Issue by fgonzalef** [voutcn/megahit#92]
I have just cloned the megahit distribution (1.0.6) and when I try to compile it I receive the above error. I have checked for the presence in my system of the Development Tools and Libraries, as suggested in another wiki for solving a "/usr/bin/ls cannot find -lstdc++" error message that I also receive during the execution of the make instruction, but I have not been able to find a solution for the other error. 
I will appreciate any hint to solve it.
Best,
Fernando Gonzalez.

**Comment by epruesse** [comment]
Please post the entire output of the make command and the OS you are compiling on (e.g. OSX with Homebrew, RHEL6, Ubuntu 12.04, etc).
Also, please post the output of `ld -lstdc++`.

**Comment by voutcn** [comment]
Alternatively, you can download the [binary release](https://github.com/voutcn/megahit/releases).
