### ISSUE TITLE
run mgahit in centos7 docker no err log

### ISSUE THREAD

**Issue by sunxingqiang-gd** [voutcn/megahit#94]
`./megahit --verbose --12 example/readsInterleaved1.fa.gz,example/readsInterleaved2.fa.bz2,example/readsInterleaved3.fa -o example/megahit_out -t 1 -m 0.5 --mem-flag 0`

the log is below:
`
1.0Gb memory in total.
Using: 0.978Gb.
MEGAHIT v1.0.6-3-gfb1e59b
--- [Wed Aug 24 05:20:34 2016] Start assembly. Number of CPU threads 1 ---
--- [Wed Aug 24 05:20:34 2016] Available memory: 2099613696, used: 1049806848
--- [Wed Aug 24 05:20:34 2016] k list: 21,41,61,81,99 ---
`
are there some bugs or problems I have met?
What should I do next?

**Comment by voutcn** [comment]
Do you have gzip and bzip2 installed?
