### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by dturaev** [voutcn/megahit#96]
I can't compile Megahit on Fedora 24, g++ 6.1.1. (The binary release seems to work.) Relevant output of the make command is here:

g++ -g -O2 -Wall -Wno-unused-function -Wno-array-bounds -D__STDC_FORMAT_MACROS -funroll-loops -fprefetch-loop-arrays -fopenmp -I. -std=c++0x -static-libgcc -m64 -static-libstdc++ -mpopcnt -DPACKAGE_VERSION="\"v1.0.6-3-gfb1e59b\"" -c local_assembler.cpp -o local_assembler.o
In file included from /usr/include/c++/6.1.1/bits/move.h:57:0,
                 from /usr/include/c++/6.1.1/bits/stl_pair.h:59,
                 from /usr/include/c++/6.1.1/bits/stl_algobase.h:64,
                 from /usr/include/c++/6.1.1/vector:60,
                 from local_assembler.h:25,
                 from local_assembler.cpp:21:
/usr/include/c++/6.1.1/type_traits: In instantiation of 'struct std::__is_nt_constructible_impl<HashGraph, HashGraph&&>':
/usr/include/c++/6.1.1/type_traits:143:12:   required from 'struct std::__and_<std::is_constructible<HashGraph, HashGraph&&>, std::__is_nt_constructible_impl<HashGraph, HashGraph&&> >'
/usr/include/c++/6.1.1/type_traits:1200:12:   required from 'struct std::is_nothrow_constructible<HashGraph, HashGraph&&>'
/usr/include/c++/6.1.1/type_traits:1231:12:   required from 'struct std::__is_nothrow_move_constructible_impl<HashGraph, true>'
/usr/include/c++/6.1.1/type_traits:1237:12:   required from 'struct std::is_nothrow_move_constructible<HashGraph>'
/usr/include/c++/6.1.1/type_traits:143:12:   required from 'struct std::__and_<std::is_nothrow_move_constructible<HashGraph>, std::is_nothrow_move_assignable<HashGraph> >'
/usr/include/c++/6.1.1/bits/move.h:179:5:   required from 'typename std::enable_if<std::__and_<std::is_move_constructible<_Tp>, std::is_move_assignable<_Tp> >::value>::type std::swap(_Tp&, _Tp&) [with _Tp = HashGraph; typename std::enable_if<std::__and_<std::is_move_constructible<_Tp>, std::is_move_assignable<_Tp> >::value>::type = void]'
lib_idba/hash_graph.h:435:56:   required from here
/usr/include/c++/6.1.1/type_traits:1190:41: error: 'HashGraph::HashGraph(const HashGraph&)' is private within this context
                                noexcept(static_cast<_Tp>(declval<_Arg>()))>
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from local_assembler.cpp:34:0:
lib_idba/hash_graph.h:189:5: note: declared private here
     HashGraph(const HashGraph &);
     ^~~~~~~~~
Makefile:226: recipe for target 'local_assembler.o' failed
make: *** [local_assembler.o] Error 1

**Comment by dturaev** [comment]
Might be related to https://github.com/loneknightpy/idba/issues/16?

**Comment by voutcn** [comment]
Thx. May you try this? https://github.com/voutcn/megahit/tree/hotfix/gcc6.0

I don't have a gcc 6.0 on my computer.

**Comment by dturaev** [comment]
Nice, thanks! This seems to work. (Might still be a good idea to test it locally before pushing it to the master...)

**Comment by sjackman** [comment]
I'm experiencing this issue as well with MegaHit 1.0.6. I haven't yet tried the above patch. Could you please tag a stable release that includes this fix?

**Comment by voutcn** [comment]
@sjackman Please try v1.0.6-hotfix1

**Comment by sjackman** [comment]
Thanks, Dinghua. I'm testing it out now at https://github.com/Homebrew/homebrew-science/pull/4454

Would you consider renaming this release either `1.0.7` or `1.0.6.1`? Punctuation other than `.` and letters are problematic in version numbers.

**Comment by voutcn** [comment]
@sjackman Used v1.0.6.1 instead. Thank you for the suggestion.
