### ISSUE TITLE
[Exit code -6] std::bad_alloc

### ISSUE THREAD

**Issue by falkomathes** [voutcn/megahit#97]
Hi,
When running a single-end Illumina fastq file, I get the following error message:
Error occurs when running "builder build" for k = 21; please refer to DBG_MG/M7_assembled/log for detail [Exit code -6]

In said file, the last few lines are: 
    [cx1_seq2sdbg.cpp          : 452]     Before reading, sizeof seq_package: 333039268, multiplicity vector: 60552592
    [cx1_seq2sdbg.cpp          : 467]     Adding mercy edges...
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Error occurs when running "builder build" for k = 21; please refer to DBG_MG/M7_assembled/log for detail
[Exit code -6]

My problem seems to be different to similar error messages already posted by other users e.g. I should not run out memory (Host memory to be used: 18503553024) or disk space (18.8 GB free).

Interestingly, another fastq file from the same sequencing run went smoothly... So I am not sure what is going on and would appreciate any help.

Thanks and all the best,
Falko

**Comment by voutcn** [comment]
I need more information to figure out what happened. Please attach the whole log file.

Anyway, using `--kmin-1pass` option may work (though a bit slower).

**Comment by falkomathes** [comment]
Log file attached. Thanks in advance for checking

Will try the --kmin-1pass option in the meantime...

[log.txt](https://github.com/voutcn/megahit/files/467107/log.txt)

**Comment by Quicken-up** [comment]
I am consistently getting the same error (std::bad_alloc) [Exit code -6], but Error occurs when assembling contigs for k = 21. This is running through qsub/Grid Engine on a shared memory HPC cluster. In the example below I was trying 16 cores with 12GB RAM each (192 GB total). 

On the megahit command I was running with meta-sensitive presets, and 16 threads to match the core count. I was also using the -m 0.5 flag to limit memory here, but this had no impact on the point or mode of failure. This was a run on 2 samples with 30-40 million paired end 150bp illuminia reads per sample. Any help appreciated.

#!/bin/sh
# Grid Engine options (lines prefixed with #$)
#$ -N megahit
#$ -cwd
#$ -l h_rt=48:00:00
#$ -l h_vmem=12G
#$ -pe sharedmem 16
#  These options are:
#  job name: -N
#  use the current working directory: -cwd
#  runtime limit of n hrs: -l h_rt
#  memory limit of m Gbyte per node: -l h_vmem

megahit --presets meta-sensitive -t 16 -m 0.5 

[megahit_log_21012017.txt](https://github.com/voutcn/megahit/files/723163/megahit_log_21012017.txt)

**Comment by voutcn** [comment]
@Quicken-up your problem is not the same as @falkomathes 's. Your metagenome is so complex that assembly graph (not the succinct DBG) could not fit into 128G memory using k=21. Please `try --presets meta-large`. If you have more questions, please open a new issue.

**Comment by mengyuan09876** [comment]
HI, I meet the same problem, did you solve it at the end? thanks
