### ISSUE TITLE
Exit code 25 - Large mem assembly

### ISSUE THREAD

**Issue by adina** [voutcn/megahit#98]
Hi,

I'm getting an error code on what looks like k77 step of a large assembly.

cmd:  /home/ubuntu/megahit/megahit_sdbg_build read2sdbg -k 27 -m 2 --host_mem 80000000000 --mem_flag 1 --gpu_mem 0 --output_prefix soil_assembly2/tmp/k27/27 --num_cpu_threads 4 --num_output_threads 1 --read_lib_file soil_assembly2/tmp/reads.lib --need_mercy

Last 30 lines of log:

    [assembler.cpp             : 148]     Loading succinct de Bruijn graph: soil_assembly2/tmp/k77/77 Done. Time elapsed: 171.188649
    [assembler.cpp             : 152]     Number of Edges: 11002191138; K value: 77
    [assembler.cpp             : 162]     Number of CPU threads: 4
    [assembly_algorithms.cpp   : 162]     Removing tips with length less than 2; Accumulated tips removed: 79250; time elapsed: 323.0879
    [assembly_algorithms.cpp   : 162]     Removing tips with length less than 4; Accumulated tips removed: 267052; time elapsed: 319.6654
    [assembly_algorithms.cpp   : 162]     Removing tips with length less than 8; Accumulated tips removed: 587569; time elapsed: 423.6726
    [assembly_algorithms.cpp   : 162]     Removing tips with length less than 16; Accumulated tips removed: 1007079; time elapsed: 672.6567
    [assembly_algorithms.cpp   : 162]     Removing tips with length less than 32; Accumulated tips removed: 1627174; time elapsed: 1166.1930
    [assembly_algorithms.cpp   : 162]     Removing tips with length less than 64; Accumulated tips removed: 2633013; time elapsed: 2079.4034
    [assembly_algorithms.cpp   : 162]     Removing tips with length less than 128; Accumulated tips removed: 6759630; time elapsed: 3795.1394
    [assembly_algorithms.cpp   : 170]     Removing tips with length less than 154; Accumulated tips removed: 13602007; time elapsed: 3975.4786
    [assembler.cpp             : 179]     Tips removal done! Time elapsed(sec): 12756.633059
    [assembler.cpp             : 188]     unitig graph size: 18751627, time for building: 5988.153216
    [assembler.cpp             : 206]     Number of bubbles/complex bubbles removed: 1469392/205219, Time elapsed(sec): 1698.109199
    [assembler.cpp             : 230]     Unitigs removed in excessive pruning: 87698, time: 16.050425
[ERROR] Cannot open soil_assembly2/intermediate_contigs/k77.contigs.fa. Now exit to system...
Error occurs when assembling contigs for k = 77, please refer to soil_assembly2/log for detail
[Exit code 25]

Any advice?

Thanks!
Adina

**Comment by adina** [comment]
Attaching the full log here:  

[log.txt](https://github.com/voutcn/megahit/files/506230/log.txt)

**Comment by voutcn** [comment]
Something wrong with the file system. Could you whether the hard disk is running out of space?

**Comment by adina** [comment]
My apologies, this was a problem with our server and a hang up.  I'll close this issue.
